### ISSUE TITLE
[3.6.0-beta.1] label of toggle field outputs page id instead of yes/no

### ISSUE THREAD

**Issue by ralfgoeke** [k-next/kirby#3708]
**Describe the bug**  

When using the toggle field in a blueprint without providing custom yes/no text, the page id is used as label for the field. 

**To Reproduce**  

```yaml
#blueprint.yml

fields:
  toggler:
    label: Toggler
    type: toggle

```

**Expected behavior**  
yes/no should be the label per default

**Screenshots**  
![toggle-bug](https://user-images.githubusercontent.com/6228942/134482815-5440dfb7-b491-428a-82cd-1e50a28c4e84.png)

**Kirby Version**  
3.6.0-beta.1

**Console output**  
none
