### ISSUE TITLE
[3.6.0-beta.2] Preview images/icons get wrong `border-radius` in lists

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#3733]
**Describe the bug**  
Preview images/icons get wrong `border-radius` in lists.
```css
.k-list-item .k-item-figure {
  border-top-right-radius: var(--rounded-sm);
  border-top-left-radius: var(--rounded-sm);
}
```
<img width="207" alt="Screenshot-30-09-2021_14-19-43@2x" src="https://user-images.githubusercontent.com/7975568/135453743-b62fee49-2d2f-4d15-8ab8-e86d8e027b48.png">

**Expected behavior (I think)**  
```css
.k-list-item .k-item-figure {
  border-bottom-left-radius: var(--rounded-sm);
  border-top-left-radius: var(--rounded-sm);
}
```
<img width="207" alt="Screenshot-30-09-2021_14-19-17@2x" src="https://user-images.githubusercontent.com/7975568/135453756-df335bcb-3c7d-4a2c-8d29-c7b1448b3bef.png">

**Kirby Version**  
3.6.0 beta 2
