### ISSUE TITLE
Form Class is loading queries (too?) eagerly causing (unnecessary) performance bottleneck

### ISSUE THREAD

**Issue by bnomei** [k-next/kirby#3746]
**Describe the bug**  
Form class loads data even if it may be never used. it dataset is very big this causes a hugh delay for on each request. This is a common scenario in both autoid and boost plugin and currently make adding pages beyond 20k index impossible within 30sec timeout.

https://github.com/getkirby/kirby/blob/efe24a6ef4ad61010428b1cb725f8f97a633ff82/src/Cms/PageActions.php#L459

**To Reproduce**  
1) create a lot of pages of template `human`

2) create a collection that does return a site->index()
```php
<?php

return function () {
    return site()->index()->filterBy('template', 'human');
};
```

3) create a page blueprint with a field with a multiselect query
```
# other fields
human:
  type: multiselect
  options: query
  max: 1
  query:
    fetch: kirby.collection('humans') # this does a site index -> filter
    text: "{{ page.title }}"
    value: "{{ page.id }}"
```

4) create a single or a batch of new `human` page programmatically.
5) the query will be executed in php code even it is most likely only used in api/kql/panel.

**Expected behavior**  
the query should only be executed in context of api/kql/panel or when called explicitly in php.

**Kirby Version**  
3.5.7 and 3.6.0-beta.1
