### ISSUE TITLE
[3.6.0-beta.2] Writer field: can’t get the `bulletList` node to appear without also enabling the `heading` node

### ISSUE THREAD

**Issue by jonasfeige** [k-next/kirby#3749]
**Describe the bug**
Using the latest beta, in the writer field I can’t get the `bulletList` node to appear without also enabling the `heading` node. The toolbar holding the buttons does not include the dropdown on the left.

Works:
```
writer:
  type: writer
  nodes:
    - heading
    - bulletList
```

Does not work:
```
writer:
  type: writer
  nodes:
    - bulletList
```

**To Reproduce**
Setup a `writer` field in any blueprint with just the `bulletList` node.
```
writer:
  type: writer
  nodes:
    - bulletList
```

**Expected behavior**
The toolbar holding the buttons should include the dropdown on the left and a button for a bullet list.
