### ISSUE TITLE
Default block previews can not be overwritten

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#3776]
**Describe the bug**  
It's not possible to set the `preview` setting of default blocks to anything else but `false`. They are hardcoded to use their respective preview, so `image` for the image block or `text` for the text block.

**To Reproduce**  
1. Create a custom block preview plugin or use https://github.com/jongacnik/kirby-fields-block
2. Set the `preview` of a default block to your custom preview or the `fields` preview:
```yml
# site/blueprints/blocks/image.yml

name: Image
preview: fields
fields:
  image:
    type: files
    multiple: false
```
3. The image block will still use the `image` preview

**Expected behavior**  
The fields preview should be used.

**Kirby Version**  
3.5.7.1

**Additional context**  
https://forum.getkirby.com/t/default-blocks-previews-hardcoded/23612
