### ISSUE TITLE
[panel] blueprint, html tags are not interpreted (info and pages fields)

### ISSUE THREAD

**Issue by vauvarin** [k-next/kirby#3804]
**Describe the bug**  
When I pass a variable containing a string with htlml tags, these html tags are not interpreted

**pages field**
This works ...
```
type: pages
    status: draft
    templates: evaluator
    info: 'Proposals: <strong>{{page.nbrProposals}}</strong>'
```
But this does not work ...
With "nbrProposals" which is a function which return a string like "```Proposals: <strong> . count($proposals) . </strong>```"
```
type: pages
    status: draft
    templates: evaluator
    info: '{{page.nbrProposals}}'
```

**info field**
This does not work ...
With "proposalDescription" which is a textarea field from another page and containing formatting text
```
proposalDescription:
      label: Description
      type: info
      text: '{{page.parent.parent.proposalDescription}}'
```

**Expected behavior**  
html tags should be interpreted in the panel

**Kirby Version**  
3.6 beta 2
