### ISSUE TITLE
[panel] Layout field - icons overlap and weird number display in the tab

### ISSUE THREAD

**Issue by vauvarin** [k-next/kirby#3805]
**Describe the bug**  
1- When I use the Layout field in a tab, a number "1" display after the tab label
2- The icons in the right part of each section overlap each over

**To Reproduce**  
```
partnershipTabHomepage:
    label: Partnership Homepage
    icon: page
    columns:
      partnershipColumnHomepage:
        width: 1/1
        fields:
          layout:
            type: layout
            label: Mise en page
            layouts:
              - "1/1"
              - "1/2, 1/2"
              - "1/3, 1/3, 1/3"

            fieldsets:
              page:
                label: Section
                type: group
                fieldsets:
                  - header
                  - footer

              text:
                label: Module
                type: group
                fieldsets:
                  - heading
                  - text
                  - list
                  - quote
                  - markdown
                  - page
                  - contact
                  - faq
                  - description
                  - campaigns

              media:
                label: Media
                type: group
                fieldsets:
                  - image
                  - gallery
                  - video

            settings:
              fields:
                sectiontype:
                  type: radio
                  label: Type of section
                  default: module
                  options:
                    module: "Module"
                    header: "Header"
                    footer: "Footer"
```

**Screenshots**  
![panel screenshot](https://i.ibb.co/P62BQNY/Rolling-Call-2021-UNIGE-COFUNDS-1.png)

**Kirby Version**  
3.6 beta 2
