### ISSUE TITLE
[3.6.0-rc.1] When user with a limited areas access logs in, system shouldn't open the site

### ISSUE THREAD

**Issue by adamkiss** [k-next/kirby#3827]
Scenario:
I have a user setup with lesser permissions, allowing them only access to custom areas for instance:

```
permissions:
  access:
    panel: true
    site: false
    settings: false
    users: false
    custom-area1: true
    custom-area2: true
```

Situation:
When the user logs in, first thing they'll see is the Site view with a  "You've no access to this resource" message.

Expected:
- go to first available area to the user (not sure how ordering works here, though)
- allow per-role based post login urls - which I feel is fairly elegant solution

Dream:
I just can imagine doing something like:
```
panel:
  post-login-url: "/panel/custom-area/project/{{ user.project.id }}"
```
