### ISSUE TITLE
Structure field layout breaks in 1/4 or smaller width column

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#3830]
**Describe the bug**  
Having a structure field in a 1/4 width column breaks its `footer` layout. There's simply not enough space for all that padding. 
See screenshot below. 

On 1/6 width columns the form is broken too.

**To Reproduce**  

1. Use the following page or site blueprint:
```yaml
columns:
  - width: 1/4
    fields:
      structure:
        fields:
          title:
            type: text
            label: Hello Footer
```
2. Add more than one entry (so the pagination footer shows)
3. Click on one entry

**Expected behavior**  
The pagination footer should not overflow the field container. 

**Screenshots**  
1/4 width
![image](https://user-images.githubusercontent.com/6684137/138104313-c7e0abbd-15df-4a12-a271-9c9ddba64399.png)

1/6 width
![image](https://user-images.githubusercontent.com/6684137/138105867-013cb8ca-940f-493c-a49d-c5817eba9954.png)

**Kirby Version**  
Noticed in 3.6.0.rc-1, but haven't tested it elsewhere.

**Desktop:**  
 - OS: Windows 10
 - Browser: Chrome
 - Version: 94

But I guess the same happens on any supported desktop browser. 

**Smartphone**  
On smartphones the pagination footer isn't shown. Therefore the problem doesn't exist here.
