### ISSUE TITLE
Caret position in empty "Text Blocks" doesn't match placeholder and text position

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#3838]
**Describe the bug**  
The caret position of Prosemirror in empty `writer` fields, that are in `block` or `layout` fields (Text Blocks), doesn't match the real position of where the text will be and where the placeholder is shown. 

**To Reproduce**  
1. page blueprint:
```yml
title: Default Page
fields:
  layout:
    layouts:
      - "1/1"
```

2. Go to the page, add a "Text" (`writer`) block
3. Look at the caret, notice it doesn't match the placeholder. 
4. Write something
5. See the caret correcting its position. 

**Expected behavior**  
it's pretty obvious I think 😸 

**Screenshots**  
![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/6684137/138551058-d827ecc4-4930-4d3f-b4d6-a6bad355525d.gif)

**Kirby Version**  
Noticed in 3.6.0-rc.1 - haven't tested elsewhere

**Desktop (please complete the following information):**  
 - OS: Windows
 - Browser: Chrome
 - Version: latest

**Smartphone**  
Not tested

**Additional context**  
Discord thread: https://discord.com/channels/525634039965679616/901399271448920084

The CSS rule:
```css
.k-writer[data-placeholder][data-empty] .ProseMirror {
    position: absolute;
    left: 0;
    right: 0;
    bottom: 0;
    top: 0;
    padding: 0.375rem 0.5rem;
}
```
Seems to work for plain `writer` fields, but not for "Text Blocks" (removing the padding from the rule fixes "Text Block", but breaks "Writer fields").
