### ISSUE TITLE
`default: now` on date field with `time: true` doesn't return proper time

### ISSUE THREAD

**Issue by GiantCrocodile** [k-next/kirby#3842]
**Describe the bug**  

**To Reproduce**  
1. Create a field like this:
```
          test_date:
            label: Test Date Field
            type: date
            time: true
            default: now
            disabled: true
            required: true
```
2. Create a page with this blueprint field
3. Check the content of the field (it's `2021-10-23 00:00`)

**Expected behavior** 
Field should contain `2021-10-23 23:54` and not `2021-10-23 00:00`

Expected behavior is described here: https://getkirby.com/docs/reference/panel/samples/blog#single-article__result

**Kirby Version**  
v3.6 rc1

**Desktop (please complete the following information):**  
Windows 10, latest Firefox

**Additional context**  
multilang site
