### ISSUE TITLE
[3.6.0-rc.2] Blocks stuck as selected in blocks in layout field

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#3856]
**Describe the bug**  

When clicking (normal click, not multiselect) on blocks in different layouts in the layout field within the block field , it stays selected.

````yaml
# sample blueprint
fields:   
  blocks:
    type: blocks
    fieldsets:
      test:
        fields:
          layout:
            type: layout
````

### Steps

1. Add a block
2. Add multiple layouts in drawer
3. Add blocks (for ex line block to see clear) for each layout
4. Now try to click/select blocks
5. See issue

**Screenshots**  

![screen-capture-1228-Test - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/139155887-fd33a986-0b83-445f-ac38-a86c0f033e5b.png)

**Kirby Version**  

3.6.0-rc.2
