### ISSUE TITLE
[3.6.0-rc.2] Permissions issue in user blueprint

### ISSUE THREAD

**Issue by vauvarin** [k-next/kirby#3860]
**Describe the bug**  
If I set permissions in a user blueprint like this:
```
permissions:
    access:
        users: false
        ...
```
The "users" item menu is hidden but when the user go to its "Your account" panel page and try to change its (email, status, language, parameters) by clicking on these links, no pop-up appear.

**To Reproduce**  
Set permissions like this in a user blueprint:
```
permissions:
    access:
        users: false
        ...
```

**Expected behavior**  
The "users" item menu is hidden but the user can edit its own account informations (emails, status, languages, parameters)

**Kirby Version**  
3.6.0-rc.2
