### ISSUE TITLE
[3.6.0-rc.2] Missing max/min length indicator Textarea

### ISSUE THREAD

**Issue by doldenroller** [k-next/kirby#3861]
**Describe the bug** 
Textareas with length validation (min- or maxlength) are missing the indicator on how the Characters are limited

**To Reproduce**  
1. Add length validation to Textarea in Blueprint

```
intro:
  label: Intro
  type: textarea
  maxlength: 160

```

**Screenshots**  
![textarea](https://user-images.githubusercontent.com/29595303/139260413-af14337b-401e-42b9-9ac9-4780140af2aa.jpg)

**Kirby Version**  
3.6.0-rc.2
