### ISSUE TITLE
[3.6.0-rc.2] Toggle field displays as checkbox and not as toggle

### ISSUE THREAD

**Issue by e9li** [k-next/kirby#3865]
**To Reproduce**  
Add toggle field to blueprint
```
highlight:
    label: Highlight
    type: toggle
    text:
        - Nein
        - Ja
    width: 1/2
```

**Expected behavior**  
Should show as toggle and not as checkbox

![toggle](https://user-images.githubusercontent.com/1247727/139406013-20037db0-a8d1-40e2-9310-723ad38631b7.png)

**Kirby Version**  
3.6.0-rc.2
