### ISSUE TITLE
Nested blocks navigation broken after level 3 and higher

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#3871]
**Describe the bug**  

Drawer form closes when click navigation items if nested blocks level 3 and higher. 

````yaml
fields:
  test:
    type: blocks
    fieldsets:
      faq:
        name: FAQ
        icon: star
        fields:
          headline:
            type: text
          text:
            type: writer
          blocks:
            type: blocks
            fieldsets:
              faqItem: 
                name: Question / Answer
                icon: box
                fields:
                  question:
                    type: text
                    placeholder: Your question …
                  answer:
                    type: blocks
````

**Expected behavior**  

Should be go/open related block form.

**Screenshots**  

![screen-capture-1230-Test - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/139456701-92116b9b-4949-4942-834f-9956dbb944d0.png)

**Kirby Version**  

3.5.7.1 and 3.6.0-RC2
