### ISSUE TITLE
[3.6.0-rc.2] Blocks field `empty` prop not working

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#3872]
**Describe the bug**  

````yaml
fields:
  blocks:
    type: blocks
    empty: No items yet
````

**Kirby Version**  

3.6.0-rc.2
