### ISSUE TITLE
Copy blocks with Writer preview not possible in Chrome

### ISSUE THREAD

**Issue by Werbschaft** [k-next/kirby#3941]
In Chrome you can't copy blocks that have a Writer preview and they are the last element you click on. See the small video for demonstration. In Safari it works. But unfortunately not in Chrome on the Mac

![Kapture 2021-11-17 at 13 36 38](https://user-images.githubusercontent.com/2178466/142203782-dd2cbcb5-2f98-4c56-b11d-633792e877ba.gif)

**Comment by bastianallgeier** [comment]
That's so weird. It works perfectly fine for me. Is there anything in the console?

**Comment by Werbschaft** [comment]
@bastianallgeier Unfortunately the console is empty, there is simply no action. I tested a little bit, with this CSS statement it works. This prevents the Prose Mirror from being activated, because there is an overlay over it when you press the Alt or Apple key. This is, I think, not the ideal solution, but I don't know how else I could help ... 

```css
[data-multi-select-key="true"] .k-block-container:before {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    content: "";
    background: transparent;
    z-index: 1;
}
```
