### ISSUE TITLE
TypeError: Cannot read property '0' of null on Date field within Structure

### ISSUE THREAD

**Issue by plagasul** [k-next/kirby#3946]
**Describe the bug**  

When accessing a date field within a structure field, and clicking on the prev/next arrows of the calendar visualization I am getting a TypeError: Cannot read property '0' of null

**To Reproduce**  
1. You need a date field within a structure like this

```
      texts:
        type: structure
        fields:
          author:
            type: text
          title: 
            type: text
          date:
            type: date
            display: YYYY
          pdf:
            type: files
            layout: list
            max: 1
            uploads: document
          url:
            type: url
```

2. Add an entry, save it.
3. Access the added entry, click on the date field and then on the prev/next arrows of the calendar visualization

**Expected behavior**  
 
No error

**Screenshots**  

https://user-images.githubusercontent.com/13966673/142623411-44f58fbe-fa6a-4fdd-b4e3-3073265d80f6.mp4

**Kirby Version**  
 
3.6

**Console output**  

```
index.js:1 TypeError: Cannot read property '0' of null
    at a.separator (index.js:1)
    at vn.get (vendor.js:6)
    at vn.evaluate (vendor.js:6)
    at a.separator (vendor.js:6)
    at index.js:1
    at Array.map (<anonymous>)
    at a.patterns (index.js:1)
    at vn.get (vendor.js:6)
    at vn.evaluate (vendor.js:6)
    at a.patterns (vendor.js:6)
errorCaptured @ index.js:1
Bt @ vendor.js:6
Vt @ vendor.js:6
n @ vendor.js:6
i._wrapper @ vendor.js:6
```

**Desktop (please complete the following information):**  
 - OS: Linux Mint 20.1 Cinnamon
 - Browser: Chrome 
 - Version:  92.0.4515.159 (Build oficial) (64 bits)

**Additional context**  

The problem may be inconsistently happening, at one point I believe it did not happen without seeing a difference in the code or browser context, but I am unsure, after reloading it did happen consistently, at least until now.
