### ISSUE TITLE
Translation failed on select fields

### ISSUE THREAD

**Issue by plain-solutions-gmbh** [k-next/kirby#3955]
External translation not work on select fields:
```
foo:
  label: path.to.translation.label
  type: select
  options:
    option1: path.to.translation.option1
    option2: path.to.translation.option2
```
The panel shows the path in the dropdown.

**Comment by texnixe** [comment]
What is `path.to.translation`? This looks more like a feature request than something that is supposed to work?

**Comment by plain-solutions-gmbh** [comment]
I've got translations in my plugin file:
```
Kirby::plugin('my-company/my-plugin', [
  'translations' => [
    'en' => [
      'path.to.translation.label' => 'My Label',
      'path.to.translation.option1' => 'My Option1',
      'path.to.translation.option2' => 'My Option2', 
    ]
  ]
```
In this case, i'm expecting that the `options` works the same way like `label`

**Comment by texnixe** [comment]
Thanks for the clarification. Translation strings are currently not supported in options (but should be easy to implement).

**Comment by distantnative** [comment]
Since this would required some breaking changes, we decided that we could not introduce such a feature before 3.7

**Comment by distantnative** [comment]
We're thinking rather of supporting query syntax and adding a new `t()` helper to the query syntax.

```
myField:
  label: "{{ t('myfield.label') }}"
  type: select
  options:
    option1: "{{ t('myfield.option1') }}"
    option2: "{{ t('myfield.option2') }}"
```

This makes it explicit when i18n keys/string should be used. Otherwise we could have problems:

```
option1: zone
// what if there is an i18n key named `zone` that resolves to `"Timezone"` but the user actually wanted the string `"zone"`
```
