### ISSUE TITLE
Top-level options not copied when extending a blueprint

### ISSUE THREAD

**Issue by yandodov** [k-next/kirby#4014]
## Description
I have a `site/blueprints/pages/article.yml` blueprint:

```yml
title: Article
num: '{{ page.date.toDate("%Y%m%d%H%M") }}'
tabs:
  ...
```

Then, I extend it in `site/blueprint/pages/article-custom.yml`:

```yml
extends: pages/article
tabs:
  ...
```

However, the `num` option is not copied. When I publish the page, the sort number doesn't update. The `title` option is also not copied and even though that wouldn't be very useful, it's expected, since you use extend.

To fix this, I just need to specify the missing options:

```yml
extends: pages/article
title: Article Custom
num: '{{ page.date.toDate("%Y%m%d%H%M") }}'
tabs:
  ...
```

## Your setup
**Kirby Version**  
3.5.7.1
