### ISSUE TITLE
Special characters in tags field saved escaped when selected using autocomplete

### ISSUE THREAD

**Issue by silllli** [k-next/kirby#4043]
## Description
I have a tags field that gets its options from a query:

```yaml
fields:
  bikeManufacturer:
    type: tags
    max: 1
    options: query
    query: page.parent.childrenAndDrafts.pluck('bikeManufacturer', ',', true)
    required: true
```

When I save a tag featuring an ampersand (e. g. “Riese & Müller“) it gets saved correctly. But when I then go to a sibling page and select that same value from the autocomplete options, it’s getting saved and output as `Riese &amp; Müller`.

**Expected behavior**  
The value being saved just like the original.

## To reproduce

1. Create a blueprint using the YAML provided above.
2. Add a page and save a value featuring an ampersand in the tags field.
3. Create a second page and select the previously saved value from the autocomplete options.
4. Create a third page and look at the provided autocomplete options or the value in the just saved txt file of the second page.

## Your setup
**Kirby Version**  

3.6.1.1

**Console output**  

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: macOS 12.0.1
 - Browser: Google Chrome
 - Version: 96.0.4664.110

Maybe related to #4041.
