### ISSUE TITLE
Blueprint: image back option with html color names that start with 'light' don't apply

### ISSUE THREAD

**Issue by crisgfx** [k-next/kirby#4073]
I just noticed, that the back option of the image prop doesn't apply when I add a html color name that starts with 'light',
e.g. 'lightblue', 'lightseagreen' etc... 
It just renders white.

```yaml
mypages:
  type: pages
  layout: cardlets
  image: icon
    icon: check
    color: "#fff"
    back: "lightseagreen"
```

**Kirby Version**  
3.6.1.1
