### ISSUE TITLE
Duplicate file uploads possible when coming from files section and files field

### ISSUE THREAD

**Issue by silllli** [k-next/kirby#4076]
## Description

Following my [post on Nolt](https://kirby.nolt.io/388): 

When I upload a file from a files field that was already uploaded on that page before, the previously uploaded file gets replaced (or at least the creation date and time are updated), but existing metadata is attached to the new file.

This can lead to unwanted behavior. In my case, I uploaded a file from a files field that is set to use a specific template (using the query and uploads option). But that file was already added to the page using a files section—set to a different template.
The new (same) file was uploaded, but it was assigned the existing field values of the previous file including e. g. the template name, without any info or warning.

It works correctly if the file only has the same name, but not if it’s the exact same file.

**Expected behavior**  

Prevention of duplicate file uploads in that case.

## To reproduce

1. Create a blueprint having a files section and a files field set to use different templates:

```yaml
title: Default Page
sections:
  filesSection:
    type: files
    template: file-a
  fieldsSection:
    type: fields
    fields:
      filesField:
        type: files
        query: page.files.filter('template', 'file-b')
        uploads: file-b
```
2. Upload a file in the files section – it will use `file-a` as template as expected.
3. Upload that same file using the files field.

## Your setup
**Kirby Version**  

3.6.1.1

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: macOS 12.1
 - Browser: Google Chrome
 - Version: 96.0.4664.110
