### ISSUE TITLE
[Panel] Draft page - Tetxarea field - maxlength property - modal error message does not appear

### ISSUE THREAD

**Issue by vauvarin** [k-next/kirby#4078]
## Description
Draft page - textarea field :
If the user enters a number of characters greater than that indicated by the maxlength property, the modal error message does not pop-up and the page can be saved.

This bug does not append if the page is "unlisted"

**Expected behavior**  
Draft page - textarea field :
If the user enters a number of characters greater than that indicated by the maxlength property, a modal error message must pop-up and the page must NOT be saved.

**Screenshots**  

## To reproduce
(Tested in the plainkit)
In the blueprint default.yml:
```
title: Default Page
preset: page
fields:
  text:
    label: Text
    type: textarea
    size: large
    maxlength: 12
```

1. Create a new default draft page in the plainkit (with the change above in the default.yml blueprint)
2. In the textarea field, enter 15 characters for instance
3. Save the page

## Your setup
**Kirby 3.6.1.1**  

**Your system (please complete the following information)**
 - Device: Laptop
 - OS: Linux
 - Browser: Firefox 95.0.2 (64 bits)
