### ISSUE TITLE
[3.6.2-rc.1]: Date-Time Picker Very Finicky and Wonky (Especially on Safari)

### ISSUE THREAD

**Issue by neildaniels** [k-next/kirby#4100]
## Description
The new date picker is very wonky on Safari and mostly wonky on Chrome.

**Expected behavior**  
- Clicking the time field should still let you pick a date
- Clicking a date should fill in the time
- Pressing backspace in time field should delete characters (currently fights)

**Screenshots**  

https://user-images.githubusercontent.com/417182/150001046-4b813997-35aa-4904-a19a-95c817fb2099.mov

https://user-images.githubusercontent.com/417182/150001070-65e4a37e-3103-4316-bada-522cc5cc2e98.mov

## To reproduce
```yaml
          created:
            label: Published Date
            type: date
            translate: false
            time:
              step: 1
              notation: 12
            width: 1/3
```

See screen recordings.

## Your setup
**Kirby Version**  
```
3.6.2-rc.1
```

**Console output**  
None

**Your system (please complete the following information)**
 - Device: Mac
 - OS: macOS 12.1 (21C52)
 - Browser: Safari
 - Version: 15.2 (17612.3.6.1.6)

**Comment by sebastiangreger** [comment]
Adding my observation, initially posted [over in a Discord thread](https://discord.com/channels/525634039965679616/933015252910612490), here as well for more convenient tracking – it seems to be closely related:

> When I highlight the hours and try to overwrite, that doesn't work. Then, when I set the cursor to the beginning, the first digit is entered correctly, the second and subsequent are added as extra characters to the minutes part.

https://user-images.githubusercontent.com/6355217/150122118-e1cad67f-e609-4fa1-ac5e-be5dc53a5f45.mov

```yml
date:
  type: date
  time:
    step: 1
    display: HH:mm
    default: now
  default: now
  label: Created
  width: 1/3
  required: true
```

**Kirby 3.6.2-rc.1**
- Device: PC
- OS: Linux Mint
- Browser: Firefox
- Version: 96.0

**Comment by bastianallgeier** [comment]
Thanks for your help. We'll likely release an update either tonight or tomorrow.

**Comment by crisgfx** [comment]
I also get a `t is undefined` error when the display property is set and I click in the input.
It doesn't happen, when clicking on the calendar-icon (see second date field in the video).

````yaml
mydatefield:
  label: End
  type: date
  display: DD. MMMM YYYY
````
Also, the name of the month in the input is in English, while the black dropdown box shows it correctly (German).

https://user-images.githubusercontent.com/16305374/150171810-50e4f999-06d9-48c7-9203-874f5c9744eb.mp4

**Kirby 3.6.2-rc.1**
-  Browser: Firefox 96
