### ISSUE TITLE
Structure field in structure field: bug content not saved

### ISSUE THREAD

**Issue by andreasotto** [k-next/kirby#4147]
## Description
When a structure field is placed in a structure field, the content is not saved in some cases. This always happens when the modified field is not exited, but saved with `Cmd-S`. Obviously the dirty flag is set only when leaving the field or something similar. In any case, this leads to the fact that the content of the field is not saved after changing and saving via keyboard shortcut.

Unfortunately, all changes that were made before are lost.

**Expected behavior**  
Entered text should be saved when hitting `Cmd-S`.

## To reproduce

Create a blueprint with a field like this:

```
  blocks:
    type: structure
    fields:
      headline:
        type: text
        label: Überschrift
      paragraphs:
        type: structure
        label: Absätze
        fields:
          text:
            type: writer
          link:
            type: pages
            multiple: false
```

1. Then open the panel and insert some initial content.
2. Save the content.
3. Edit the content in the field `text` and hit `Cmd-S` to save => now the content is lost.

If you use your mouse to save, everything works.
If you leave the current form field and then save, everything works.
If you don't leave the field but hit `Cmd-S`, the content is lost.

**Kirby Version**  
3.6.2
