### ISSUE TITLE
page->update() resets select fields with query options  in second language

### ISSUE THREAD

**Issue by mheuschneider** [k-next/kirby#4149]
## Description
When using ``$page->update([], 'de')``, the content should not change.
But if I try the same with 'en' (second language) all select fields with a query are reseted.

The query for this select field is following: site.magazin_categories.split

Im using this function inside the ``page.changeSlug:after`` hook.

**Expected behavior**  
The same as in the default language.

**Screenshots**  
Screenshots after hook

de.txt
![image](https://user-images.githubusercontent.com/58510889/153454288-1af16614-1ae7-4df6-b3a0-7ad744c59bd2.png)

en.txt
![image](https://user-images.githubusercontent.com/58510889/153454449-146725e7-a7d4-4abf-af7f-5f1bfb74dc5d.png)

## To reproduce
1. Create a custom hook:
```php
<?php

Kirby::plugin('my/customhook', [
    'hooks' => [
        'page.changeSlug:after' => function ($newPage, $oldPage) {
            $site = site();

            $site->page('*path/to/page*')->update(array(), 'en');
        }
    ]
]);
```
2. Replace path with a page and 'en' with secondary language
3. Create an select field (with query) for this page:
```yml
fields:
    category:
        label: Category
        type: select
        options: query
        query: site.categories.split
        width: 1/3
```
4. Create an settings field for site:
```yml
fields:
    categories:
        label: Magazin categories
        type: tags
```
5. Add random category tags (in both languages)
6. Go to page and select one tag (in both languages)
7. Save and switch to main language
8. Change the slug of a page (could be a different one)

## Your setup
**Kirby Version**  
Tested with 3.6.1.1 and 3.6.2

**Your system**
 - Device: Desktop
 - OS: Windows 11
 - Browser: Chrome
 - Version: latest
