### ISSUE TITLE
Consistent styling for invalid fields (e.g. empty required)

### ISSUE THREAD

**Issue by teichsta** [k-next/kirby#4171]
## Description

As discussed in https://forum.getkirby.com/t/required-field-on-block-blueprint-image-not-shows-as-invalid/24793?u=teichsta i realised an inconsistend behaviour of required fields. Some fields like pages, files and text do show a nice red border indicating the required attribute. Other fields like writer and textarea don't

**Expected behavior**  

All field types should show the red border indicating the required attribute for better UX.

**Screenshots**  

![image](https://user-images.githubusercontent.com/2108636/155108288-7c5a3a5e-5838-48a6-8568-781b4b55f5e7.png)

```
  banner_image:
    label: field.blocks.image.name
    type: files
    multiple: false
    required: true
    image:
      back: black
    uploads:
      template: poolfile
  credits:
    label: Quellenangabe
    type: writer
    inline: true
    icon: text
    required: true
```

## Your setup
**Kirby Version**  
kirby 3.5.7.1 and 3.6.2
