### ISSUE TITLE
Second writer field content is deleted on changing page slug

### ISSUE THREAD

**Issue by tritos-design** [k-next/kirby#4181]
## Description
Precondition: Two writer fields in a single blueprint (there may be more than these two fields); both fields are filled with some data and saved
When changing the page's slug, the content of the second writer field is deleted and the orange save/dismiss bar appears. When saving, the content of the second writer field is written to disk as empty. When dismissing, the original content is restored.

**Expected behavior**  
The content of the second writer field should not be deleted.

## To reproduce
1) Create a blueprint with at least two writer fields.
2) Save some arbitrary data in the writer fields.
3) Change the page slug.
4) See that the content of the second writer field has been deleted.

## Your setup
**Kirby Version**  
3.6.2

**Console output**  
No errors logged.

**Your system (please complete the following information)**
Seen across different browsers (Firefox, Chrome) and different systems (Linux, Windows).

**Comment by afbora** [comment]
@tritos-design I couldn't reproduce the issue.

1. Do you have the same issue with [starterkit](https://github.com/getkirby/starterkit) or [plainkit](https://github.com/getkirby/plainkit)?
2. If you are having the same issue in starterkit/plainkit, can you share the content you entered in the fields with us? (maybe it's related to content)

**Comment by tritos-design** [comment]
@afbora Yes, the same happens with the latest starterkit (3.6.2).
I only made one modification in site/blueprints/pages/note.yml from
```
columns:
  - width: 2/3
    # This columns only has a single field
    fields:
      text:
        type: blocks
```
to
```
columns:
  - width: 2/3
    # This columns only has a single field
    fields:
      w1:
        type: writer
      w2:
        type: writer
      text:
        type: blocks
```
Then I start the php built-in verser via `php -S localhost:8000 kirby/router.php`, go to `http://localhost:8000/panel/pages/notes+exploring-the-universe` add the text `qwe` to w1 and `asd` to w2 and save the changes.
Then I click the page title and change the slug from `exploring-the-universe` to `exploring-the-universe2`.
Result: The orange change/revert bar appears and the content of the second writer field `w2` has disappeared.
I can get the content back by clicking `revert`, but it shouldn't disappear in the first place.

Can you reproduce this?

P.S.: I'm running PHP 8.0.16 locally, if that might be relevant.
