### ISSUE TITLE
Can select non-images in image block

### ISSUE THREAD

**Issue by moritzebeling** [k-next/kirby#4189]
## Description
When adding a new image block, I can easily select any file type, even non-image files like PDFs, ZIPs or audio. As the output snippet expects only images, I think it should only be possible to select images in the first place.

When I look into `kirby/config/blocks/image/image.yml` I can see that there is no filtering going on:

```yaml
name: field.blocks.image.name
icon: image
preview: image
fields:
  # ...
  image:
    label: field.blocks.image.name
    type: files
    multiple: false
    image:
      back: black
    uploads:
      template: blocks/image
    when:
      location: kirby
  # ...
```

The image field would need a `query: page.images` to only allow images to be selected.

## To reproduce
1. Have a blueprint with a block editor
2. Login to panel
3. Upload a non Image file
4. Create a new image block
5. Click on "Select file" and check if you can select that non-image file

## Your setup
**Kirby Version**  3.6.2
