### ISSUE TITLE
Extending core block fields removes other blocks

### ISSUE THREAD

**Issue by MacGyer** [k-next/kirby#4206]
## Description
I extended the core block `heading` like stated in the docs: https://getkirby.com/docs/reference/panel/fields/blocks#extending-core-blocks

After adding new fields via the configuration in `site/config/config.php` (to have the new fields everywhere in `heading` block) or a single blueprint all other core blocks are removed (e. g. are not available anymore). This causes errors in the panel as existing content might be using blocks now not available.

**Expected behavior**  
As the heading block is extended, all other block should not be affected in any way.

**Screenshots**  
![image](https://user-images.githubusercontent.com/2939625/159225585-6be434db-de2a-4979-b2f4-43b1698b1da5.png)

![image](https://user-images.githubusercontent.com/2939625/159225833-120eb481-5767-40d6-acc8-d2c2cc69231c.png)

![image](https://user-images.githubusercontent.com/2939625/159225875-8b73e96d-53fc-45f4-8dd6-1d13b9855f24.png)

## Your setup
**Kirby Version**  3.6.2

**Your system (please complete the following information)**
 - Device: PC
 - OS: Server running on Linux Mint 20.2 with PHP 7.4, Browser on current Win 10
 - Browser: current Chrome, current Firefox

**Comment by afbora** [comment]
Actually this is expected and known behavior. You need to add each core block type if fieldsets prop of your field is not empty. 

If you want to extend core blocks with listing all, you can create custom fieldsets blueprint file that have core blocks like:

````yaml
# /site/blueprints/fieldsets/blocks.yml
fieldsets:
    code: blocks/code
    gallery: blocks/gallery
    heading: blocks/heading
    image: blocks/image
    line: blocks/line
    list: blocks/list
    markdown: blocks/markdown
    quote: blocks/quote
    text: blocks/text
    video: blocks/video

# /site/blueprints/page/default.yml
fields:
  blocks:
    type: blocks
    extends: fieldsets/blocks
    fieldsets:
      # overwriting heading block
      heading:
        fields:
          level:
            options:
              - h2
              - h3
````

Also you can share the idea with community: https://feedback.getkirby.com/
