### ISSUE TITLE
Text field `converter` doesn't working PHP 8.1

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4226]
## To reproduce

> trim(): Passing null to parameter `#1` ($string) of type string is deprecated in file:

````yaml
fields:
  headline:
    type: text
    converter: upper
````

## Your setup
**Kirby Version**  

3.6.3.1
