### ISSUE TITLE
Panel: Multiselect field searches through literally encoded html entities (e.g. `&amp;`)

### ISSUE THREAD

**Issue by neildaniels** [k-next/kirby#4229]
## Description
When searching in the `multiselect` field for something like "a" results start showing things for `&amp;`

The might be related to #4041 and/or #4043.

**Expected behavior**  

Results should always retain their original titles and I wouldn't expect searching the encoded entities.

**Screenshots**  

<img width="331" alt="Screen Shot 2022-03-24 at 12 56 51 PM" src="https://user-images.githubusercontent.com/417182/159999609-9c348516-ee8a-4b48-8cd1-60e1ea4a93ed.png">

https://user-images.githubusercontent.com/417182/159999625-ed62974c-11f8-404b-8fa3-57e580785166.mov

## To reproduce

```yaml
          channelUIDs:
            label: Channels
            type: multiselect
            search:
              display: 10
            options: query
            query:
              fetch: 'kirby.collection("channels")'
              text: "{{ page.title }}"
              value: "{{ page.uid }}"
```

## Your setup
**Kirby Version**  

`3.6.3.1`

**Console output**  

**Your system (please complete the following information)**
 - Device: Mac
 - OS: macOS
 - Browser: Safari
 - Version: Version 15.4 (17613.1.17.1.6)

**Additional context**
