### ISSUE TITLE
Copy&Paste not working on nested blocks

### ISSUE THREAD

**Issue by owzim** [k-next/kirby#4282]
## Description
Copy&Paste not working on nested blocks

When copying blocks with keystroke or with options menu, pasting them does result in the paste dialog being shown, but cmd+v makes the dialog disappear and then nothing else happens.

On the parent block everything's working as expected.

## To reproduce

create a nested blocks setup on a page:

```yaml
fields:
  blocks:
    type: blocks
    fieldsets:
      nested:
        name: Nested
        label: Nested
        fields:
          blocks:
            type: blocks
            fieldsets:
              item:
                name: Item
                label: Item
                fields:
                  title:
                    type: text
```

## 

## Your setup
**Kirby Version**  

3.6.5

**Console output**  

no errors or warnigns in the console

**Your system (please complete the following information)**
 - OS: macOS
 - Browser: Latest stable Chrome, latest stable Firefox
