### ISSUE TITLE
Preview image from other page not shown when page child of site and status `published`

### ISSUE THREAD

**Issue by texnixe** [k-next/kirby#4297]
## Description
When using a pages section with first level pages, `status: published` and the queried preview image is from another page, the preview image is not shown.

**Expected behavior**  
The preview image should always be shown

**Screenshots**  
<img width="1191" alt="Bildschirmfoto 2022-04-29 um 21 52 58" src="https://user-images.githubusercontent.com/5312492/166060403-837aa0f8-8f7d-4bf0-a780-5086bb466f5f.png">

## To reproduce
1. Create several page with template `test` as children of the site object
2. Create a files page with template `files` with at least 1 image
3. Create a site.yml blueprint with the following content:

```
Title: Site

columns:
  left:
    width: 1/2
    sections:
      notes:
        headline: Notes (published)
        type: pages
        parent: kirby.page('notes')
        image: kirby.page('files').image('last-tree-standing.jpg')
        status: published
        layout: cards
        size: tiny
        template: note
  right:
    width: 1/2
    sections:
      published:
        headline: First level test page (Published)
        type: pages
        layout: cards
        size: tiny
        image: kirby.page('files').image('last-tree-standing.jpg')
        status: published
        templates: test
      listed:
        headline: First level test page (Listed)
        type: pages
        status: listed
        layout: cards
        size: tiny
        image: kirby.page('files').image('last-tree-standing.jpg')
        template: test
      drafts:
        headline: First level test page (Draft)
        type: pages
        status: draft
        layout: cards
        size: tiny
        image: kirby.page('files').image('last-tree-standing.jpg')
        template: test
      unlisted:
        headline: First level test page (Unlisted)
        type: pages
        status: unlisted
        layout: cards
        size: tiny
        image: kirby.page('files').image('last-tree-standing.jpg')
        template: test
```

Interestingly, the images also show up in the section with the published pages when adding page with the `files` template:

```
      published:
        headline: First level test page (Published)
        type: pages
        layout: cards
        size: tiny
        image: kirby.page('files').image('last-tree-standing.jpg')
        status: published
        templates:
          - test
          - files # template of the files page
```

Slightly different test setup can be found here: https://github.com/ersoma/starterkit-bughunt

## Your setup
**Kirby Version**  
3.6.5

Additional context:
https://forum.getkirby.com/t/page-image-is-not-displayed-in-pages-section-when-referencing-a-filtered-out-page/25352/5
