### ISSUE TITLE
[Panel] Sorting files messed up when uploading multiple files

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#4303]
## Description
Uploading multiple files at the same time makes them have all the same sorting number. 

**Expected behavior**  
Files should have sequential sorting numbers. 

## To reproduce
1. Create a files section blueprint:
```yml
    sections:
      images:
        type: files
        limit: 4
        text: "fig. {{ file.sort }}"
``` 
2. Upload 5 files (in the same drag & drop action)
3. See that all uploaded files have the same sorting number. 
4. Drag the first file to the second position
5. Notice how the dragged file is (probably) not in the second position

## Your setup
**Kirby Version**  
3.6.6

**Your system (please complete the following information)**
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Version: 101

**Additional context**  
related? https://github.com/getkirby/kirby/issues/2886
