### ISSUE TITLE
[panel] two file-fields with width 1/2 next to each other overlap at around 1040px

### ISSUE THREAD

**Issue by dennisbaum** [k-next/kirby#4307]
## Description
I have two file-fields with width: 1/2 next to each other.
around browser-width of 1040px, they overlap and there is no gap between.
bigger then 1150px it's ok. below 1040px ist ok, because they get responsive width of 1/1

**Expected behavior**  
i expect that the images are not overlapping, and the gap is correct

**Screenshots**  
1040px browser-width: images are overlapping
![grafik](https://user-images.githubusercontent.com/562826/168923221-5620d322-d107-438c-981e-442a7640a21f.png)
~1150px browser-width it's ok
![grafik](https://user-images.githubusercontent.com/562826/168923292-d7ceb39d-e9d2-43fb-91d0-7f5d5c68db85.png)

```
image1:
  label: Image1
  type: files
  layout: cards
  size: large
  width: 1/2
image2:
  label: Image2
  type: files            
  layout: cards            
  size: large            
  width: 1/2
```

## Your setup
**Kirby Version**  
3.6.6 

**Your system (please complete the following information)**
 - OS: MacOS
 - Browser: FF, Chrome
 - Version: 100, 101

**Comment by afbora** [comment]
This issue about following CSS lines:

````css
@media screen and (min-width: 65em) {
  .k-cards-items[data-size="large"] {
    --min: 32rem;
  }
}
````
https://github.com/getkirby/kirby/blob/3.6.6/panel/src/components/Layout/Items.vue#L156-L160

`32rem` is too wide (32rem x 2 columns = 64rem + some padding > 65em media query). The ideal width I tested seems to be `28rem`. Unless we have a more stable solution for padding or elsewhere.
