### ISSUE TITLE
[3.7.0-rc.1] pagedisplay section can't be loaded anymore

### ISSUE THREAD

**Issue by vauvarin** [k-next/kirby#4380]
## Description

When we add a section with the "page display" plugin, kirby can't load this section.

**Expected behavior**  
Load the page display section and display a list of pages

**Screenshots**  
This is the error message:
![Home_Mægazine](https://user-images.githubusercontent.com/664089/173858622-93198add-9677-4cdc-b56c-341d930b7576.png)

## To reproduce
Add a pagedisplay section in a blueprints
tested in the home page blueprint in the Starter-kit

```

options:
  changeStatus: false

sections:
  content:
    type: fields
    fields:
      headline:
        type: text
        width: 1/2
      gap:
        width: 1/2
      subheadline:
        type: text
        width: 1/2

#### Page section here ! #######################################################
  mysection:
    headline: Foo Pages
    type: pagesdisplay
    query: site.index.filterBy('title', '*=', 'Foo')
#########################################################################################

  photography:
    label: Photography
    extends: sections/albums
    status: listed
    size: small
    help: All projects for the homepage are being pulled from the photography page.

```

## Your setup
**Kirby Version**  
3.7.0 -rc-1

**Your system (please complete the following information)**
Linux, Firefox
