### ISSUE TITLE
Table layout: make whole row clickable

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#4388]
> Adding to the last point: the fact that pages are only accessible by clicking the link in the title field is generally not great, especially on touch devices. The structure field is visually and technically identical, it's also using the table component. There you can click on the full row.
>
> While the Panel does a great job with large enough click areas pretty much everywhere else, the link in the pages table is too small. In my opinion you should at least make the whole cell clickable.
>
> <img width="415" alt="173692498-2381dc55-22df-4abd-a62c-90d20fec7683" src="https://user-images.githubusercontent.com/3788865/173894664-587947f5-3a22-4b46-a862-953d7ce034f3.png">

Original thread: https://github.com/getkirby/kirby/issues/4374

**Comment by afbora** [comment]
I'm not sure of that. If we are going to take the table sections further, this (whole row clickable) should not be mandatory (It should at least have a disable feature). Because while the title has the edit link, we can give a different link when we put a preview or custom button next to it. So different actions can be listed in the tables.

**Comment by lukasbestle** [comment]
Also I think with the current styling (underlined link), I wouldn't expect the whole cell to be clickable. This doesn't mean we should keep it as is, maybe we can instead change the styling.

**Comment by distantnative** [comment]
I think this is two decisions:
- whole row clickable vs. Allowing different cells hosting different links
- url cell being clickable as whole cell/more padding va. just the underlined text

**Comment by jaro-io** [comment]
i am trying to update the title of the first default column from "title" to "something". so far i got here:

```yml
type: pages
layout: table
text: false
columns:
  title:
    label: something
    value: '{{ page.title }}'
```

the problem now is that i cant open the page anymore because it removes the link. any other solution you can suggest for this? if this is the only way to change the title, i guess it definitely makes sense having alternative options to open the page.

**Comment by jaro-io** [comment]
@distantnative @lukasbestle @afbora does anyone of you have an idea on how to achieve what i am trying to do above? would be lovely to get some help if you have a minute. thank youuu! 🙏🏻 ✨

**Comment by afbora** [comment]
@jaro-io Sorry for delay. Your request is not possible for stable way (something missing for `type: url` feature). But as workaround you can try following:

````yaml
test:
  label: something
  type: html
  value: '<a href="{{ page.panel.url }}">{{ page.title }}</a>'
````

**Comment by jaro-io** [comment]
@afbora great idea, i didnt think about this. so helpful! works beautifully! 🎉 

i even went one step further. in order to color the links blue (like the title), i added this:

```yml
test:
  label: something
  type: html
  value: '<p class="k-url-field-preview" style="padding: 0"><a href="{{ page.panel.url }}">{{ page.title }}</a></p>'
```
