### ISSUE TITLE
[3.7.0-rc.1] structure field with max value looks off

### ISSUE THREAD

**Issue by jaro-io** [k-next/kirby#4393]
## description
dont know if you’re aware of this already. but since updating to `3.7.0-rc.1`, my structure fields look kinda strange. the last column either needs more space or the "remove" text needs to be removed (lol). this only happens when having a `max` value set.

**Screenshots**  
<img width="807" alt="structure" src="https://user-images.githubusercontent.com/20298313/174291980-3f8b6531-7db1-4245-abc9-350d298ab25b.png">

## to reproduce
```yml
structure:
    label: Structure
    type: structure
    max: 3
    fields:
        title:
            label: Title
            type: text
        images:
            label: Carousel Images
            type: files
            query: page.images
```

then add 3 entries to the structure field.

---

hope it helps!
🙏🏻 ✨
