### ISSUE TITLE
Zip file upload throws  Call to a member function createFile() on null 

### ISSUE THREAD

**Issue by GiantCrocodile** [k-next/kirby#4416]
## Description
When you upload kirby-3.7.0-rc.2.zip to a page's file field, you get an error.

**Expected behavior**  
No error when you choose to upload this file.

**Screenshots**  
![grafik](https://user-images.githubusercontent.com/6271057/175168029-591ee96a-03be-4d80-b6af-a69544d8ca18.png)

![grafik](https://user-images.githubusercontent.com/6271057/175169271-37ffe7a7-7503-4a13-b9ec-3a35a4b6896d.png)

## To reproduce

1. Go to a page with a Files field
2. decide to upload the zip file "kirby-3.7.0-rc.2.zip"
3. Error occurs in browser console and as a popup/dialog

## Your setup
**Kirby Version**  
[3.7.0-rc.2]

**Console output**  
```
GEThttp://localhost/kirby/api/pages/blog+test/fields/files?page=0
[HTTP/1.1 400 Bad Request 314ms]

Object { status: "error", message: "Your query must return a set of files", code: 400, exception: "Kirby\\Exception\\InvalidArgumentException", key: "error.invalidArgument", file: "/kirby/kirby/src/Cms/FilePicker.php", line: 65, details: [], route: "pages/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)/fields/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)(?:/(.*))?" }
[index.js:1:6580](http://localhost/kirby/media/panel/0c54e85478d4103bb6683e538994010d/js/index.js)
XHRPOSThttp://localhost/kirby/api//pages/blog+test/fields/files/upload
[HTTP/1.1 500 Internal Server Error 314ms]

XHRPOSThttp://localhost/kirby/api//pages/blog+test/fields/files/upload
[HTTP/1.1 500 Internal Server Error 394ms]
```

**Your system (please complete the following information)**
Windows 11 WAMP setup

**Additional context**  
If you choose to select a file from a list of existing files, it throws an "Your query must return a set of files" error if the query returns no files. That one might be on purpose/by design.

**Comment by afbora** [comment]
I can't reproduce the issue. Do you have any plugins? Do you still get same error on plain/starter kit?

**Comment by GiantCrocodile** [comment]
@afbora I tried with starterkit and it did work there without issues (3.6.6 and 3.7.0 rc2). Then I retried my own page and I think I found the issue but I don't understand it yet.

Try to select a already uploaded file (instead of upload) which will cause because there are no files uploaded previously (query will fail). If you then try to upload a zip file for first time, it tells you there was an internal error and when you try it a second time with a different zip file, you get the error I have posted in this issue.

I suspect this is related to this query in my blueprint:

```
          children:
            type: pages
            query: page.childrenAndDrafts
          files:
            type: files
            query: page.children.find('test').images
            uploads:
              parent: page.children.find('test')
```

I'm not sure why I have this in (looks like some old code) but I suspect it shouldn't break it?

EDIT: This would then be linked to my tiny comment hook plug in .... looks like I have to investigate this next few days :/.

**Comment by afbora** [comment]
@GiantCrocodile Did you try `childrenAndDrafts` instead `children`. I'm pretty sure this issue related with this.

````yaml
fields:  
  download:
    type: files
    query: site.childrenAndDrafts.find('test').images
    uploads:
        parent: site.childrenAndDrafts.find('test')
````

**Comment by GiantCrocodile** [comment]
@afbora I tried your query and parent example (not just replacing `children` with `childrenAndDrafts ` but also the `site` part). This does throw the same error as before. When I just take `childrenAndDrafts` instead `children` it doesn't help as well.

In case you are interested, I've sent you a minimal example.

**Comment by afbora** [comment]
This was just example. You need to adapt based your application. `childrenAndDrafts` didn't work because `test` page is not in `root` but under the blog page `blog/test`. 

⚠️ Note that regular queries cannot find draft pages. You need to use custom queries like `index(true)` or `childrenAndDrafts`. Following examples should work (tested on your app):

````yaml
files:
  type: files
  query: site.index(true).find('blog/test').images
  uploads:
    parent: site.index(true).find('blog/test')
````

or

````yaml
files:
  type: files
  query: kirby.page('blog').childrenAndDrafts.find('test').images
  uploads:
    parent: kirby.page('blog').childrenAndDrafts.find('test')
````
