### ISSUE TITLE
Image card overflows grid container

### ISSUE THREAD

**Issue by foxacid** [k-next/kirby#4460]
## Description

On files fields with a card layout there seems to be a conflict between `size` and `width` properties. When both are set, images may overflow the container width. I believe this is a regression introduced with `3.7`.

**Expected behavior**  

I would expect the field grid container to constrain the size of the image card, no matter if it's set to `large` or `small`.

**Screenshots**  

![image](https://user-images.githubusercontent.com/12812201/176871719-5fa9975c-5a22-45ae-8752-6016ceb9fbf1.png)

## To reproduce

```
type: files
layout: cards
multiple: false
query: page.images
uploads:
  template: image
image:
  ratio: 3/2
  cover: true
width: 1/2
size: large
```

**Comment by afbora** [comment]
This issue also exists in 3.6.6, so no regression.

**Comment by distantnative** [comment]
# Summary

General CSS rules for the size of cards etc are hard with many variables (width, column size,e browser windows width...). We've really tried to fine-tune this but there will always pop up situations where they still fail.

Once container queries are available in more browsers, we can replace this logic with a container query that bases the decision on what width to use for which `size` setting based on the the actual width of its parent.

**Comment by foxacid** [comment]
Thank you for your efforts and the information. 

Excuse my ignorance but wouldn't a simple `max-width: 100%` do the job in this case?

**Comment by distantnative** [comment]
I don't think so as it's not a problem of width but of the grid template columns. But maybe I'm just trying in the wrong places. Always appreciate a PR if someone has a fix.

**Comment by moritzebeling** [comment]
As of 3.9.1 the issue persists. In my case I have 2 columns, both with 50% width. Inside one of them a file field like this:

```yml
type: files
layout: cards
size: large
```

The problem does not occur with all other size values like `small`, `medium` or `huge`.

**Huge, works:**

```html
<div class="k-draggable k-items k-cards-items" data-layout="cards" data-size="huge">
```
```css
@media screen and (min-width: 30em){
    .k-cards-items[data-size=huge],
    .k-cards-items[data-size=large],
    .k-column[data-width="1/4"] .k-cards-items,
    .k-column[data-width="1/5"] .k-cards-items,
    .k-column[data-width="1/6"] .k-cards-items {
        --min: 1fr;
    }
}
```

**Large, breaks container:**

```html
data-size="large"
```

This css rule overwrites the rule above. When removing it, everything looks nice:

```css
@media screen and (min-width: 65em){
    .k-cards-items[data-size=large] {
        --min: 32rem;
    }
}
```

However I am not sure if simply removing that rule is the right way of "solving" the problem or if it will cause some inconsistency somewhere else...
