### ISSUE TITLE
Options field 'preview' does not accept per-user permissions

### ISSUE THREAD

**Issue by herrbischoff** [k-next/kirby#4552]
## Description

According to the [page blueprint reference](https://getkirby.com/docs/reference/panel/blueprints/page#options)

> Each option can be set on a per user role for fine-grained permissions

However, when I set

```yml
options:
  preview:
    admin: true
    editor: false
```

The panel throws the following error:

```
Kirby\Cms\Page::previewUrl(): Return value must be of type ?string, array returned 
```

The panel apparently expects either a boolean or a template string but no array of users, like the other options do.

**Expected behavior**  

Either make the behavior consistent with the other options or change the reference documentation to reflect this inconsistency. This should affect supplying different template strings for different users as well.

## Your setup
**Kirby Version**  

3.6

**Comment by afbora** [comment]
@getkirby/kirby-staff Do you think is it an intended, a bug, or an improvement that needs to be made?

Also note that preview can be a string. I'm not sure how it can be disabled for both string and some roles. Applicable for non-string values, but seems difficult for string values.

**Comment by lukasbestle** [comment]
I agree that ideally there should be a way to set different values per role, e.g. like this:

```yaml
options:
  preview:
    admin: true
    editor: "{{ page.parent.url }}/#{{ page.slug }}"
    translator: false
```

The options are unfortunately inconsistent at the moment. E.g. there is also the `changeTemplate` option that supports an array, however not an array of roles but an array of target templates.

I think this is something to reconsider after the upcoming blueprint refactoring.
