### ISSUE TITLE
Structure field performance

### ISSUE THREAD

**Issue by mynameisfreedom** [k-next/kirby#4554]
Hi, structure field is great field, and very usable for many situations, but it is by far the slowest field. If there are several structure fileds in the panel page, it becomes very slow. It loads very slow, and it saves changes even slower. 

It is easy to reproduce with two approaches:
- By adding 2-3 structure fields on one page and adding 3-4 items in them
- By creating one block with one structure field, adding that block to page and adding several items in block structure field

It works slow in every Kirby 3+ version. 
If there is any option to improve performance of that field it will be super welcomed.

**Comment by afbora** [comment]
Could you share your blueprint file please?

**Comment by mynameisfreedom** [comment]
Hi, @afbora, can't do it today, but I will as soon as possible. Thank you!

**Comment by mynameisfreedom** [comment]
Hi, sorry for the delay, here is a blueprint for testing. 
It is a block blueprint, just add it as a new block in your blocks. It is a simplified slider block, where the structure field has options for one image, a blocks field for content, and a few options fields.

```

name: Slideshow
icon: layers

tabs:
  # content tab
  content:
    label: 
      en: Content
      de: Inhalt
    icon: edit
    fields:
      # slideshow
      slideshow:
        label: 
          en: Slideshow items
          de: Slideshow-Elemente
        type: structure
        columns: 
          slideImage: 
            width: 2/3
          slideContentPosition:
            width: 1/3
        max: 5
        help: 
          en: Maximum 5 items allowed.
          de: Maximal 5 Artikel erlaubt.
        fields:
          # slide image
          slideImage:
            label: 
              en: Slide image
              de: Slide Bild
            type: files
            query: site.images.add(page.images)
            layout: cards
            size: small
            multiple: false
            width: 1/2
            image:
              cover: true
          # kirbytext
          slideContent:
            label: 
              en: Slide content
              de: Slide Inhalt
            type: blocks
            width: 1/2
          # content position
          slideContentPosition:
            label: 
              en: Slide content position
              de: Position des Inhalts verschieben
            type: select
            default: " uk-position-bottom-left"
            options:
              " uk-position-top-left": Top left
              " uk-position-bottom-left": Bottom left
              " uk-position-top": Top
              " uk-position-left": Left
              center: Center
            width: 1/2
          slideContentPositionCenter:
            label: 
              en: Slide content position center
              de: Schieben Sie die Inhaltsposition in die Mitte
            type: select
            default: " uk-position-center"
            options:
              " uk-position-top-center": Top center
              " uk-position-center-left": Center left
              " uk-position-bottom-center": Bottom center
              " uk-position-center": Center
            width: 1/2
            when:
              slideContentPosition: center
          slideContentWidth:
            label: 
              en: Slide content width
              de: Breite des Folieninhalts
            type: select
            placeholder: Auto
            options:
              " uk-width-1-3@s": 1/3
              " uk-width-1-2@s": 1/2
              " uk-width-2-3@s": 2/3
            width: 1/2

```

**HOW TO TEST:**
- Add it to the page, and populate its structure field with several items. Add one image and some simple content blocks. 
- Then duplicate that block a few times, to have 3-4 duplicated blocks on a page
You will see that page saving and page loading will slow down significantly. 

**NOTE**
I think that the blocks field inside structure field is making the biggest slowdown. A structure field in a block that have Kirby markdown instead of blocks field is a lot faster. It slows down too, but not that much.
