### ISSUE TITLE
Extending core block blueprints

### ISSUE THREAD

**Issue by ovenum** [k-next/kirby#4560]
## Description

When extending Kirbys core image block it’s not possible to limit the ratio options. 

```yaml
testBlocks:
  type: blocks
  fieldsets:
    image:
      extends: blocks/image
      fields:
        ratio:
          options:
            1/1: "1:1"
            16/9: "16:9"
            7/5: "7:5"
```

**Expected behavior**  

The only options for the `ratio` should be the ones passed from the blueprint. (1/1, 16/9, 7/5)

As described in the cook book recipe [Modifying blocks types and custom blocks / Extending existing fields](https://getkirby.com/docs/cookbook/panel/block-basics#extending-core-blocks__extending-existing-fields) it should be possible to limit the options.

## Your setup
**Kirby Version**  
3.7.2.1

**Additional context**  

The difference between the example given in cook book recipe and the one above is the use of an _non-associative array_ for the level options in the recipe and a _associative array_ for ratio options. 

```yaml
[…]
fieldsets: 
  heading:
    extends: blocks/heading
    fields:
      level:
        # non-associative array, does overwrite the core block options
        options:
          - h2
          - h3
  image:
    extends: blocks/image
    fields:
      ratio:
        # associative array, does not overwrite the core block options
        options:
          1/1: "1:1"
          16/9: "16:9"
          7/5: "7:5"   
```

This is probably the only possible behaviour? [Kirby/Cms/Blueprint,php:210](https://github.com/getkirby/kirby/blob/main/src/Cms/Blueprint.php#L210) is merging the core blocks blueprint settings with the extension by calling `A::merge($mixin, $props, A::MERGE_REPLACE)`. 
With `A::MERGE_REPLACE` only non-associative arrays will be replaced, so it’s not possible to remove keys from an associative array and that’s what you want 99.9% of the time when using extends with blueprints. 

Maybe the cook book recipe should make a note of this?

**Comment by ovenum** [comment]
If required i can create a PR to fix extending the core gallery block ratio options by supplying a non-associative array for the ratio options. This would allow extending the core gallery block with custom ratio values.

Not sure what the way forward is regarding #4555. 

```yaml
    options:
      - value: 1/1
        text: "1:1"
      - value: 16/9
        text: "16:9"
      - value: 10/8
        text: "10:8"
      - value: 21/9
        text: "21:9"
      - value: 7/5
        text: "7:5"
      - value: 4/3
        text: "4:3"
      - value: 5/3
        text: "5:3"
      - value: 3/2
        text: "3:2"
      - value: 3/1
        text: "3:1"
```
