### ISSUE TITLE
Broken preview of toggles field value inside structure field

### ISSUE THREAD

**Issue by foxacid** [k-next/kirby#4566]
## Description
When using the new toggles fields inside a structure, the structure preview outputs only the option, not the value. 
In case the options are translated, nothing is output at all.

**Expected behavior**  
It should behave like a select or toggle field, i.e. the preview outputs the (translated) value, not the option.

**Screenshots**  

![k3_structure_select](https://user-images.githubusercontent.com/12812201/184326040-9ff5c043-8453-4a79-aa9a-459287d25851.png)

![k3_structure_toggles](https://user-images.githubusercontent.com/12812201/184326044-7a7318eb-9870-47a5-abf7-bd55af8b8d3c.png)

## To reproduce
```
gallery:
  type: structure
  label:
    en: Gallery
    de: Galerie
  fields:
    image:
      label:
        en: Image
        de: Bild
      type: files
      multiple: false
      image:
        back: black
      uploads:
        template: blocks/image
    size:
      label:
        en: Size
        de: Größe
      type: toggles
      required: true
      options:
        xs: XS
        s: S
        m: M
        l: L
        xl: XL
      default: l
      width: 1/2
    alignment:
      label:
        en: Align
        de: Ausrichtung
      type: toggles
      required: true
      options:
        left:
          en: Left
          de: Links
        right:
          en: Right
          de: Rechts
      default: left
      width: 1/2
```
## Kirby Version 
3.7.3
