### ISSUE TITLE
`changeTemplate` not working in home blueprint

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#4571]
## Description

While it works for every other blueprint, you can't use the [changeTemplate](https://getkirby.com/docs/reference/panel/blueprints/page#change-templates) option on the home page.

You can find some more information in this old thread: https://forum.getkirby.com/t/how-to-change-template-in-backend/17895/8

**Expected behavior**  
It should be possible to use this option for every blueprint.

## To reproduce

1. Add some blueprints to your installation
2. Add changeTemplate to the home blueprint listing some of your previously created blueprints
3. Look at the options in the panel, the change template option is still greyed out 😢

```yml
# site/blueprints/home.yml
options:
  changeTemplate: 
    - video-post
    - link-post
    - text-post
```
