### ISSUE TITLE
`pattern` property not working with url fields

### ISSUE THREAD

**Issue by silllli** [k-next/kirby#4597]
## Description

The `pattern` property to validate input doesn’t work with url fields.

**Expected behavior**  

Setting a regex pattern that validates user input in the panel should prevent saving differing values.

## To reproduce

1. Create a blueprint featuring a url field
2. Set this pattern to match Vimeo links `pattern: '^(http\:\/\/|https\:\/\/)?(www\.)?(vimeo\.com\/)([0-9]+)$‘`
3. Enter anything but a Vimeo url, e. g. `https://getkirby.com`
4. Save the value despite not matching the pattern

```yaml
someUrl:
  type: url
  pattern: '^(http\:\/\/|https\:\/\/)?(www\.)?(vimeo\.com\/)([0-9]+)$'
```

## Your setup
**Kirby Version**  

**Your system (please complete the following information)**
 - Device:  MacBook Pro
 - OS:  macOS 12.5.1
 - Browser:  Safari
 - Version:  15.6.1

**Additional context**  

Changing the field type to `text` makes the pattern validation work.
