### ISSUE TITLE
[develop] tags field escaping issue when editing the tag

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4664]
simple tags field escaping when editing

````yaml
tags:
  label: Tags
  type: tags
````

![tags-field-issue](https://user-images.githubusercontent.com/3393422/190991093-5b557144-0d6c-4fe1-bceb-0e610f4b2fc0.gif)

_Originally posted by @afbora in https://github.com/getkirby/kirby/issues/4624#issuecomment-1250802381_
