### ISSUE TITLE
[develop] Error on tags field when related field is empty

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4665]
If the related field is empty, it gives an error. Instead, the field is expected not to offer any options.

> Invalid query result data: Kirby\Cms\NestObject in file: test\kirby\4624\kirby\src\Option\OptionsQuery.php line: 143

````yaml
tags:
  label: Tags
  type: tags
  
tags_from_other_field:
  label: Tags (Options from other fields)
  type: tags
  options: query
  query: page.tags.split
````

_Originally posted by @afbora in https://github.com/getkirby/kirby/issues/4624#issuecomment-1250802381_
