### ISSUE TITLE
[3.8.0-rc.1] new object field some console errors

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4681]
Sorry for overlooking the errors in the console before the PR merged.

### Few issues 

1. When first click add and open the drawer

> Uncaught TypeError: Cannot read properties of undefined (reading 'isOpen')
> Uncaught TypeError: Cannot read properties of undefined (reading 'open')

2. When click `tags` field

> Uncaught TypeError: Cannot read properties of undefined (reading 'focus')

### Sample blueprint

````yaml
fields:      
  person:
    label: Person
    type: object
    fields:
      category:
        label: Category
        type: multiselect
        options:
          design: Design
          architecture: Architecture
          photography: Photography
          3d: 3D
          web: Web
      name:
        type: text
      pages:
        type: pages
      files:
        type: files
      tags:
        type: tags
````
