### ISSUE TITLE
[3.8.0-rc.1] Fields of type "gap" are shown in object field preview

### ISSUE THREAD

**Issue by fabianmichael** [k-next/kirby#4688]
## Description
When the `fields` property of an object field contains a gap field, it is rendered as preview.

**Expected behavior**  
As the gap field is only a visual placeholde, it should not show up in the preview.

**Screenshots**  
<img width="209" alt="Bildschirmfoto 2022-09-23 um 08 40 40" src="https://user-images.githubusercontent.com/395617/191905328-f9c2711c-6f0b-4961-b1d7-ba266b6ffb1f.png">

Blueprint:
```yaml
test_object:
  type: object
  fields:
    […]
    anchor_gap:
      type: gap
      width: 1/2
      when:
        link_type: anchor
    […]
```

## Your setup

**Kirby Version**  
3.8.0-rc.1
