### ISSUE TITLE
[3.8.0-rc.1] blocks and layout field issues within object field

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4690]
Getting following error when using blocks and layout fields within object field

> Cannot read properties of null (reading 'length')

````yaml
fields:      
  person:
    label: Person
    type: object
    fields:
      blocks:
        type: blocks
      layout:
        type: layout
````

**Additional context**  

Seems to happen when the field is named `blocks` and `layout`, works if you give it another name.
