### ISSUE TITLE
[3.8.0-rc.1] UUID as option value is not casted as string

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#4701]
>  I had another issue, which I was able to solve but was unintuitive… I had a blueprint select using autoid plugin to define a relation (basically define a query and use {{ page.autoid }} as the value). Changing value to page.uuid didn't work, I had to change to page.uuid.id…  I would expect the "toString" of an UUID field to compute to the actual UUID, without needing to access it via id… (if I'm understanding this correctly)

**Comment by distantnative** [comment]
Tried to reproduce, but this does work for me

```yaml
testy:
  type: select
  options:
    type: query
    query: site.children
    value: "{{ page.uuid }}"
```
