### ISSUE TITLE
Error: rmdir Directory not empty

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4705]
![captures_chrome-capture-2022-8-27](https://user-images.githubusercontent.com/3393422/192490818-73960a3c-db8a-4d7f-8d0d-5292aebca512.png)

## To reproduce

1. Copy/paste below blueprint
2. Add new sandbox page
3. Fill all fields
4. Do not save the page
5. Try to delete the page
6. See issue

````yaml
title: Sandbox

fields:     
  category:
    label: Category
    type: multiselect
    options:
      design: Design
      architecture: Architecture
      photography: Photography
      3d: 3D
      web: Web
  name:
    type: text
  pages:
    type: pages
  files:
    type: files
  tags:
    type: tags   
````

**Kirby Version**  
3.7.5 & 3.8.0-RC.1
