### ISSUE TITLE
[3.8.0-rc.2] Blueprint option with translated labels not working

### ISSUE THREAD

**Issue by doup** [k-next/kirby#4726]
## Description

Blueprint field `select` with translated label options is not working anymore. This was working in `3.7.0`.

**Expected behavior**  

It should show the label.

**Screenshots**  

<img width="300" alt="image" src="https://user-images.githubusercontent.com/188612/193105534-e1dc58cd-a8e4-4ccc-bc35-f6ca67cd7619.png">

![image](https://user-images.githubusercontent.com/188612/193105689-1813b39f-9f15-45f6-8a5f-84ebff497bae.png)

## To reproduce

I'm using the following blueprint config:

```
    fields:
      type:
        type: select
        translate: false
        label:
          eu: Ekitaldi mota
          es: Tipo de evento
        width: 1/3
        default: single
        required: true
        options:
          single:
            eu: Egun bakarrekoa
            es: Día único
          multiple:
            eu: Egun anitzekoa
            es: Multiples dias
```

## Your setup

**Kirby Version**: `3.8.0-rc.2`
