### ISSUE TITLE
[3.8.0-rc.2] Missing polyfill for tags field with query for plain array values

### ISSUE THREAD

**Issue by sebastiangreger** [k-next/kirby#4739]
Regretfully, I don't have the resources right now to create a complete ticket with reproducible step-by-step code etc., but want to mention this nevertheless as this was a really hard nut to crack:

In 3.7 I was using this blueprint field definition, pulling in a plain array of tags using a site method:

```
tags:
  type: tags
  label: Tags
  options: query
  query:
    fetch: site.fieldcache('tags')
    text: "{{ arrayItem.value }}"
    value: "{{ arrayItem.value.slug }}"
```

The data returned by `$site->fieldcache('tags')` is of format:

```
[
  0 => 'tag1',
  1 => 'tag2',
  2 => 'tag3',
  // etc.
]
```

Related to: #4624 this no longer works in 3.8.0-rc.2 and actually leads to a very long loading time for the panel pages baring such field (is the server side of the Fiber exchange getting choked up on this in the background?). I had to change it to this in order to get my tag suggestions back and get rid of the long loading times:

```
tags:
  type: tags
  label: Tags
  options: query
  query: site.fieldcache('tags')
```

**Comment by bastianallgeier** [comment]
✅

**Comment by arnoson** [comment]
Is this supposed to work again?
I still can't use this syntax in Kirby 3.8
```yaml
query:
  fetch: site.fieldcache('tags')
  text: "{{ arrayItem.value }}"
  value: "{{ arrayItem.value.slug }}"
```

**Comment by afbora** [comment]
@arnoson Do you have `options: query` prop?

**Comment by arnoson** [comment]
I'm using [kirby-color-palette](https://github.com/sylvainjule/kirby-color-palette) like this:
```yaml
palette:
  type: color-palette
  options: query
  query:
    fetch: site.colorVariables
    value: 'var({{ arrayItem.key }})'
```

`site.colorVariables` is a site method that returns an array in the format of:
```php
[
  '--my-color' => '#ffffff',
  // ...
]
```

I have defined the corresponding css variables in a custom panel.css. This used to work before 3.8
kirby-color-palette displays the correct number of options (color tiles), but somehow can't access the arrayItem key
