### ISSUE TITLE
Title not showing up in Structure field page preview in block drawer.

### ISSUE THREAD

**Issue by teichsta** [k-next/kirby#4788]
## Description
I create a structure field which contains a pages field. While all page title are shown when selecting a page the page title is not shown in the page preview bubble.

The blueprint:

```
  entries:
    label: 'Kategorien'
    type: structure
    max: 4
    fields:
      headline:
        label: Überschrift
        type: writer
      article:
        label: Beitrag
        type: pages
        image: page.previewImage
        max: 1
        required: true
        options: query
        query: site.children.template('blog').first.articles
```

**Screenshots**  

![image](https://user-images.githubusercontent.com/2108636/195976848-be29c868-08eb-449c-8835-d3fe57dcfd29.png)
