### ISSUE TITLE
Selected image get's removed from content block when changing status directly draft to listed

### ISSUE THREAD

**Issue by teichsta** [k-next/kirby#4824]
## Description

It seems the files field knows different options to store the URL of the selected image. There are different pages in my content which either shows an url like `"61tup44laul._ac_sl1000.jpg"` or `"news/1654862078883/img_7327.jpeg"` (see more complete example below). As long as the parent page doesn't change this makes no different. However when changing the URL of the page or duplicating the page this leads to problems.

**Expected behavior**  

I would expect to see the image URL without the page part of the URL as this would help duplicating pages and alike.

**Screenshots**  

Blueprint of the image block

```
name: field.blocks.image.name
icon: file-image
preview: image

tabs:
  main:
    label: Datei
    fields:
      image:
        label: field.blocks.image.name
        type: files
        search: false
        multiple: false
        required: true
        query: page.images
        image:
          back: black
        uploads: poolfile
      caption:
        label: Bildunterschrift
        type: text
        icon: text
      credits:
        label: Quelle
        type: hidden
        icon: text
```

```
[
    {
        "content": {
            "image": [
                "61tup44laul._ac_sl1000.jpg"
            ],
            "caption": "",
            "credits": null,
            "headline": "",
            "link": "",
            "ratio": "",
            "crop": "false",
            "width": "col-lg-auto",
            "width_mobile": "col",
            "no_padding_top": "false",
            "no_padding_bottom": "false"
        },
        "id": "4c63e77e-13d0-4bbb-b204-64b75ea0b017",
        "isHidden": false,
        "type": "image"
    }
]
```

and in another file (same blueprint)

```
[
    {
        "content": {
            "image": [
                "news/1654862078883/img_7327.jpeg"
            ],
            "caption": "",
            "credits": "Klasse 2c",
            "headline": "",
            "link": "",
            "ratio": "",
            "crop": "false",
            "width": "col-lg-auto",
            "width_mobile": "col"
        },
        "id": "3cdf314c-48a3-416e-8082-a8c97dd0a21f",
        "isHidden": false,
        "type": "image"
    },
    [...]
```

## To reproduce

unfortunately i cannot really tell … 

## Your setup

php 8.1, kirby 3.7.5.1

Thanks for having an educated look into this. If i can assist with any more details, please let me know.
