### ISSUE TITLE
Blocks in the Structure Field in combination with Textarea delivers JSON in the Panel

### ISSUE THREAD

**Issue by Werbschaft** [k-next/kirby#4825]
## Description

If you create a textarea field in the blocks within a structure field, the JSON is returned in the panel. However, only if more than one line is entered in the textarea field, so the break or a hidden character seems to create that issue. In the video you can see quite well what I mean.

A question in general: why is the structure field saved as YAML and the blocks as JSON? Wouldn't it generally make sense and be more compliant to switch to JSON for the structure field? We have massive performance problems when we use the structure field. We don't have this problem with the blocks. YAML is a great thing, but in my eyes more for simple content. For more complex nesting, JSON should be more performant, right?

**Video**  

https://user-images.githubusercontent.com/2178466/198822278-8bf05ef6-b061-4dd7-aa68-c9485d7819ea.mp4

## To reproduce

Just use the following blueprint, so you can reproduce it in a plainkit. **To get the JSON back in the panel, you have to refresh the site!**

```yaml
fields:
  myStructure:
    type: structure
    fields:
      myBlocks:
        type: blocks
        fieldsets:
          myBlock:
            name: Textarea
            fields:
              myTextarea:
                type: textarea
```
