### ISSUE TITLE
Select field has no initial value in structure/object fields

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#4838]
## Description

When using a [select](https://getkirby.com/docs/reference/panel/fields/select) field inside of a [structure](https://getkirby.com/docs/reference/panel/fields/structure) or [object](https://getkirby.com/docs/reference/panel/fields/object), the field doesn't initially have a value — compared to using it directly in the page blueprint.

### Why is this bad?

Let's say you're using a select field and other fields react to it via field conditions:

```yml
select:
  options:
    - Option A
    - Option B
    - Option C
text:
  when:
    select: ""
```

The text field is not shown initially. Only when changing the select field to some option and back to nothing it's shown. Interestingly enough it also works by saving the empty value and opening the structure/object again. I tried to set `default: ""` but it didn't work either.

![select-when](https://user-images.githubusercontent.com/7975568/201051459-77bd2e3d-acd7-401d-8908-56e15bd3d932.gif)

**Expected behavior**  

I'd expect the select field to have an initial value of `""` just like it does outside of structure or object fields.

## To reproduce

1. Add a structure or object field to your blueprint
2. Add a select field to the structure/object field
3. Add a field with a when condition for the select field to the structure/object

```yml
structure:
  fields:
    select:
      options:
        - Option A
        - Option B
        - Option C
    text:
      when:
        select: ""
# or:
object:
  fields:
    select:
      options:
        - Option A
        - Option B
        - Option C
    text:
      when:
        select: ""
```

## Your setup
**Kirby Version**  
3.8.1.1
