### ISSUE TITLE
Multiselect field with query options from structure field: Error after deleting structure field entry

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [k-next/kirby#4848]
## Description
A multiselect field loads options from a structure field. After deleting an entry from the structure field, the multiselect field show the error `this.state.map is not a function`.

**Screenshots**

![1_before](https://user-images.githubusercontent.com/77532479/202239649-a7c81e23-a03d-49d5-9dc6-0958c3baf268.png)

After deleting the first entry in the structure field (and reloading the page):
![2_after](https://user-images.githubusercontent.com/77532479/202239653-7b1a5c82-cd1d-41c2-acb6-3af527c8e857.png)

## To reproduce
I took the example code from the [docs](https://getkirby.com/docs/reference/panel/fields/multiselect#options-from-other-fields__options-from-structure-field) and added it to the Kirby starterkit.

```yml
fields:
  category:
    label: Category
    type: multiselect
    width: 1/2
    options:
      type: query
      query: page.twitter.toStructure
      text: "{{ item.name }}"
      value: "{{ item.twitter }}"

  twitter:
    label: Follow the Kirby Team on Twitter …
    type: structure
    width: 1/2
    fields:
      name:
        label: Team Member
        type: text
      twitter:
        label: Twitter Username
        type: text
```
To keep it simple, both fields are on the same page. But it also happens when the structure field is on a different page.

The error is **not** displayed when I delete the last entry in the structure field. 

## Your setup
**Kirby Version**  
3.8.2

**Console output**  
```
TypeError: this.state.map is not a function
    at s.tags (index.js:1:126729)
[...]

```
Probably refers to this line in the MultiselectInput.vue file: https://github.com/getkirby/kirby/blob/main/panel/src/components/Forms/Input/MultiselectInput.vue#L211
