### ISSUE TITLE
Turn off WYSIWYG editing for the quote block

### ISSUE THREAD

**Issue by MoritzLost** [k-next/kirby#4852]
## Description

I'm trying to modify the core `quote` block. In particular, I want to allow only plaintext instead of formatted text for the `text` and `citation` fields. So I've copied over the blueprint from the core (`config/block/quote/quote.yml`) to my own blueprints directory (`blueprints/blocks/quote.yml`) and modified it to fit my needs:

```yaml
name: field.blocks.quote.name
icon: quote
wysiwyg: false
preview: quote
fields:
  text:
    label: field.blocks.quote.text.label
    placeholder: field.blocks.quote.text.placeholder
    type: textarea
    buttons: false
    icon: quote
  citation:
    label: field.blocks.quote.citation.label
    placeholder: field.blocks.quote.citation.placeholder
    type: text
    icon: user
```

Now the fields that are displayed in the modal window use those settings correctly. But the preview still show the HTML formatting toolbar when I select text in the preview (see screenshots below). This also causes further problem – in the modal, I can see the `<p>` tags generated by the preview. When I try to delete them, the preview editor insert `&lt;` once I delete the `/p>` from the modal editor and so on.

![quote-modal](https://user-images.githubusercontent.com/10146880/202508590-bc9aa893-3d39-42fc-aef7-d98eebbc784d.png)

![quote-preview](https://user-images.githubusercontent.com/10146880/202508597-22a278bd-c38b-4b13-b7de-452788e23855.png)

**Expected behavior**  

I would expect the preview to use the same settings defined for the `text` and `citation` fields. So if I set those to `text` fields, the preview should not show a `writer` interface.

Alternatively, I thought the `wysiqyg` option would turn off the formatting toolbar. But as far as I can change, setting that option to false has absolutely no effect. Does that option do anything at all?

I also tried to keep the two fields as `writer` fields, but disable all nodes and marks to only allow plain text in the preview:

```yaml
    type: writer
    nodes: false
    marks: false
```

For some reason, this gets rid of all the inline formatting options (`strong`, `italic`, etc) but still shows the nodes dropdown:

![quote-nodes-marks-disabled](https://user-images.githubusercontent.com/10146880/202508914-563fb546-086b-4feb-98bd-610624b83792.png)

## To reproduce

1. Copy the full quote blueprint included above to `blueprints/blocks/quote.yml`. 
2. Open an entry with a blocks field that includes this `quote` block and try to edit it in both the modal window and the preview.

**Kirby Version**  

3.8.1.1

**Additional context**  

Besides not being able to fully customize this behaviour, I would argue that the current default is pretty unusable. It will _never_ make sense to have an `h1` inside a `quote` block, but the default happily allows this.
