### ISSUE TITLE
No HTML output in table layout in the panel

### ISSUE THREAD

**Issue by mountbatt** [k-next/kirby#4856]
## Description
If you use `layout:table` in the panel you cant output HTML from a page model as described here:
https://getkirby.com/docs/guide/blueprints/query-language#querying-information-to-display__escaping-html
It workd in List, Cards and Cardlets but not in a column of a table layout.

**Screenshots**  
![Bildschirm­foto 2022-11-19 um 13 12 37](https://user-images.githubusercontent.com/2411246/202850289-940db348-1165-49a2-ae5e-fb3c6da1e919.png)

## Your setup
**Kirby Version**  
3.8.2

**Comment by distantnative** [comment]
Have you tried https://getkirby.com/docs/reference/panel/sections/pages#layout__table-layout ?

```
layout: table
columns:
  html:
    label: HTML
    type: html
    value: "{{ page.someSafeHTML }}"
```
