### ISSUE TITLE
Writer field: Not possible to wrap to words in one link if one contains an inline style

### ISSUE THREAD

**Issue by baalej** [k-next/kirby#4866]
## Description
I am using a Layout with Writer blocks and I realized that if I want to add a link with the inline toolbox to two different words for example:

“… the [professor of design at ELISAVA] discusses the ethics …”

It works works fine as long as there are no other tags on any of the words wrapped in the link.

If add oblique to any of them, the link splits in two, one for the oblique word and another one for the rest.

“… the [professor of design at] [ELISAVA] discusses the ethics …”

Is there a way to wrap them together in a link using Writer?

**Expected behavior**  
There is one link that wraps all the words, even if they include different inline styles/tags.

**Screenshots**  
Without inline styles/tags (Panel)
<img width="264" alt="Captura de Pantalla 2022-11-26 a las 16 27 49" src="https://user-images.githubusercontent.com/38941353/204096512-cbe131bc-408e-48d9-b7b4-fd63e0441c83.png">

Without inline styles/tags (Template)
<img width="455" alt="Captura de Pantalla 2022-11-26 a las 16 27 40" src="https://user-images.githubusercontent.com/38941353/204096580-eb7da6ca-b0e3-4656-bc8d-68461d212b6b.png">

With inline styles/tags (Panel)
<img width="259" alt="Captura de Pantalla 2022-11-26 a las 16 28 09" src="https://user-images.githubusercontent.com/38941353/204096619-9bc9361b-30e7-4bf9-aacb-81ec5aac0783.png">

With inline styles/tags (Template)
<img width="435" alt="Captura de Pantalla 2022-11-26 a las 16 28 22" src="https://user-images.githubusercontent.com/38941353/204096639-1df843dc-4738-4792-be97-15dc44ef0c1e.png">
<img width="452" alt="Captura de Pantalla 2022-11-26 a las 16 28 26" src="https://user-images.githubusercontent.com/38941353/204096644-6de6541a-9bb8-4d66-b666-f207e0a19927.png">

## To reproduce
Using a Writer field. 
1. Select at least two separate words.
2. Add a Link.
3. Select one of the two words.
4. Add an inline style: e.g. oblique
5. The link in the template is split in two different words.

**Console output**  
No console output.

**Comment by distantnative** [comment]
@baalej I cannot reproduce this

https://user-images.githubusercontent.com/3788865/206898258-b1e6f455-206f-4620-ae79-bfea18f92d91.mov

Result:
<img width="593" alt="Screenshot 2022-12-11 at 11 22 50" src="https://user-images.githubusercontent.com/3788865/206898265-f10a011e-5742-4678-8d07-968c65059287.png">

Are you using any custom blocks, custom inline styling...? How does your template output look like?

**Comment by baalej** [comment]
Hello,

I am using layouts + blocks. You are right @distantnative, the block has a custom blueprint based on the default one where I just added few more options.

Here is the blueprint:
```
name: field.blocks.text.name
icon: text
wysiwyg: true
preview: text
fields:
  indent:
    type: toggle
    label: Text Indent
    width: 1/2
  paragraphmargin:
    type: toggle
    default: false
    label: Paragraph spacing
    width: 1/2
  size:
    label: Text Size
    type: radio
    width: 1/2
    default: medium
    options:
      small: Small
      medium: Medium
  align:
    label: Text Align
    type: radio
    width: 1/2
    default: left
    options:
      left: Left
      center: Center
  adaptable:
    type: toggle
    label: Adaptable height
    help: Toggle for long Bio texts
  text:
    type: writer
    nodes: false
    placeholder: field.blocks.text.placeholder
```

And here is the block snippet:
```
<?php /** @var \Kirby\Cms\Block $block */ ?>
<?php 
$class = $block->indent()->toBool() == true ? 'indent ' : '';
$class .= $block->paragraphmargin()->toBool() == false ? 'no-margin-paragraphs ' : '';
$class .= $block->adaptable()->toBool() == true ? 'adaptable ' : '';
$class .= $block->size();
$class .= ' block-type-text';
?>

<div class="<?= $class ?>" style="text-align: <?= $block->align() ?>">
<?= $block->text(); ?>
</div>
```

Here is a video demonstration:

https://user-images.githubusercontent.com/38941353/206899364-3e227872-ea01-4826-8112-55bb0e38326c.mov

Here is the template output:
```HTML
<strong>
  <a href="[https://www.elisava.net/es/profesores/dr-ariel-guersenzvaig](view-source:https://www.elisava.net/es/profesores/dr-ariel-guersenzvaig)" rel="noopener noreferrer">
    professor
  </a>
</strong>
<a href="[https://www.elisava.net/es/profesores/dr-ariel-guersenzvaig](view-source:https://www.elisava.net/es/profesores/dr-ariel-guersenzvaig)" rel="noopener noreferrer">
   of 
</a>
<s>
  <a href="[https://www.elisava.net/es/profesores/dr-ariel-guersenzvaig](view-source:https://www.elisava.net/es/profesores/dr-ariel-guersenzvaig)" rel="noopener noreferrer">
    design
  </a>
</s>
<a href="[https://www.elisava.net/es/profesores/dr-ariel-guersenzvaig](view-source:https://www.elisava.net/es/profesores/dr-ariel-guersenzvaig)" rel="noopener noreferrer">
   at 
</a>
<em>
  <a href="[https://www.elisava.net/es/profesores/dr-ariel-guersenzvaig](view-source:https://www.elisava.net/es/profesores/dr-ariel-guersenzvaig)" rel="noopener noreferrer">
  ELISAVA
  </a>
</em>
```

I am using Kirby 3.7.5 and PHP 8.0.8
