### ISSUE TITLE
Radio field in custom dialog: issues with options

### ISSUE THREAD

**Issue by adamkiss** [k-next/kirby#4902]
## Description
When using `radio` field in a custom dialog, options in `value: text` format[1] are not loaded. If these options are expanded to the format defining "value" and "text" separately[2], default option is ignored if the field's value in the `value` props isn't defined.

[1] simple format:
```yaml
default: opt1
options:
  opt1: Option 1
```

[2] alternative format:
```yaml
default: opt1
options:
  - text: Option 1
    value: opt1
```

**Expected behavior**  
1. Options are correctly loaded for the simple format 
2. If the `dialog.props.value.[field-name]` isn't defined, default value is correctly selected 

**Screenshots**  

![CleanShot 2022-12-07 at 20 21 34@2x](https://user-images.githubusercontent.com/481362/206275909-c3926c0d-01fa-45b4-966d-cd48089bddef.jpg)

## To reproduce

1. Create a simple plugin to create a custom dialog ([example replacing `site:page.changeStatus`](https://github.com/adamkiss/virtual-pages-test/blob/main/site/plugins/custom-dialog-test/index.php))
2. Try to change status
3. Observe bugs

## Your setup
**Kirby Version**  
3.8.3
