### ISSUE TITLE
PHP 8.1: ->words() method breaks in loop

### ISSUE THREAD

**Issue by bensanlau** [k-next/kirby#4904]
## Description
After upgrading to php 8.1, when wanting get total word count over a set of blocks, it returns an error: 
`strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated`

(Use case: to tally word count of an article consisting of different block types, then calculate reading time)

## To reproduce
Working off the plainkit, I simply added a blocks field:
```yaml
columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
            size: huge
          blocks:
            type: blocks
```
And in default.php, I tried to tally up all words:
```php
Word count in textarea: <?= $page->text()->words(); // this works ?>
<br>
<?php
  $counter = 0;
  foreach($page->blocks()->toBlocks() as $block) {
    $counter += $block->text()->words(); // error
  };
  echo 'Word count in blocks: ' . $counter;
?>

```

This running php 8.1.13.
Switching back to php@8.0, word count returns as expected.

Playing around with the [`words()` method](https://github.com/getkirby/kirby/blob/3.8.3/config/methods.php#L328), it works if value is not passed as argument:
```php
'words' => function (Field $field) {
  return str_word_count(strip_tags($field));
},
```
But, I'm not so versed in PHP to suggest this as the solution 😬

## Your setup
**Kirby Version**  
Kirby 3.8.3

**Your system (please complete the following information)**
PHP 8.1.13 on MacOS Ventura
