### ISSUE TITLE
Options from query not working in tags field?

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#4947]
```
         category:
            type: tags
            options:
              type: query
              query: site.eventCategories.toStructure
              text: "{{ item.name }}"
              value: "{{ item.name }}"
```

```
      eventCategories:
        type: structure
        fields:
          name: 
            type: text
          color: 
            type: colors
```

> UPDATE: It's working perfectly fine with a Select field. I'll be using that for my use-case (unique category) but it does absolutely nothing when used with the Tags field (old or new syntax).
