### ISSUE TITLE
`undefined` error on structure field with required field

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5000]
**Screenshots**  

![screen-capture-1498-Exploring the universe - Kirby Demo-localhost](https://user-images.githubusercontent.com/3393422/212060294-681b2cac-8a37-4541-a074-ba41c447cf2e.png)

## To reproduce

1. Use following blueprint

````yaml
fields:
  test:
    type: structure
    fields:
      foo:
        type: text
````

2. Add some data more than one
3. Add new required field to structure field like following:

````yaml
fields:
  test:
    type: structure
    fields:
      foo:
        type: text
      bar:
        type: text
        required: true
````

4. Refresh page form in panel
5. Click and open a row form
6. Try to navigate to other page form via pagination without any changes
7. See issue

## Your setup
**Kirby Version**  

Tested on 3.8.2, 3.8.4 and 3.9.0-RC2

**Console output**  

No console error.

**Your system (please complete the following information)**
 - OS: Windows 10
 - Browser: Chrome
 
**Additional context**
