### ISSUE TITLE
 Options type API not working with .slug Query

### ISSUE THREAD

**Issue by isaactopo** [k-next/kirby#5020]
## Description
I have updated to Kirby 3.9 and I have a Nationality custom field for the users blueprint as follows:

```yaml
nationality:
  label: Nacionalidad
  type: select
  translate: false
  options:
    type: api
    url: https://raw.githubusercontent.com/Dinuks/country-nationality-list/master/countries.json
    text: "{{ item.en_short_name }}"
    value: "{{ item.en_short_name.slug }}"
```
As you can find on the forum: https://forum.getkirby.com/t/options-type-api-not-working/27672/7
When not using  `.slug` for the value, is all working as expected but when using it the select only gets the latest item:

![panel image](https://europe1.discourse-cdn.com/standard20/uploads/getkirby/optimized/2X/4/4b5db12694fced8ab97f90afd6b0e82f8aa1ddb1_2_690x217.png)

This is explained on the docs:
https://getkirby.com/docs/reference/panel/fields/select#options-via-api

It's a Bug or we can't use `.slug` for the API queries and it's a documentation thing?

This is the JSON I’m using:
https://raw.githubusercontent.com/Dinuks/country-nationality-list/master/countries.json 

## My setup
**Kirby Version**  3.9.0

 - Device: MacBook Pro M1 Pro
 - OS: macOS Ventura 13.1 
 - Browser: Brave/Chrome

Thanks!

**Comment by afbora** [comment]
Not sure but I think field method usages for `query` calls not for `api` 🤷‍♂️ 
https://github.com/getkirby/kirby/blob/3.9.0/src/Option/OptionsApi.php#L118

**Comment by texnixe** [comment]
@isaactopo mentioned in the linked forum thread that it worked in versions prior to 3.9, in which case it would be a regression, but I haven't verified yet.

If it never worked, then this example in the [docs](https://getkirby.com/docs/reference/panel/fields/select#options-via-api) is not correct, it currently doesn't work either.
```
category:
  label: Category
  type: select
  options:
    type: api
    url: https://example.com/companies.json
    query: Companies
    text: "{{ item.name }}"
    value: "{{ item.name.slug }}"
```

**Comment by texnixe** [comment]
In 3.7.5, this works fine

```
fields:
  nationality:
    label: Nacionalidad
    type: select
    options: api
    api:
      url: 'https://raw.githubusercontent.com/Dinuks/country-nationality-list/master/countries.json'
      text: "{{ item.en_short_name }}"
      value: "{{ item.en_short_name.slug }}"
```

So I would expect this to work also in 3.9.
