### ISSUE TITLE
Content in structure fields nested in block is not kept as draft unless ✔️ of said structure is clicked.

### ISSUE THREAD

**Issue by vincentrouleau** [k-next/kirby#5031]
## Description
Content in structure fields nested in block is not kept as draft unless their ✔️ is clicked .
Every other piece of content is automatically saved as draft, so having this specific case behave differently can lead to some frustration.

**Expected behavior**  
Content is expected to be kept as draft when closing the block drawer.

## To reproduce

1. Create a block containing a structure, like this one.
```
name: Cards
fields:
  title:
    type: text
  items:
    type: structure
    fields:
      title:
        type: text
      text:
        type: writer
```
2. Add content
3. Exit said block by clicking "outside" the block drawer, the "esc" key or the ✔️ of the whole block.
4. Changes are lost.
5. Content is kept if the ✔️ button of the structure field is used or ENTER key with structure field focussed.

## Your setup

**Kirby Version**  
3.8.1, 3.9

**Console output**  
none

**Your system (please complete the following information)**  
macOS, Windows.
