### ISSUE TITLE
pretty: true for layout field

### ISSUE THREAD

**Issue by plain-solutions-gmbh** [k-next/kirby#5056]
## Description
Nice feature in block `pretty: true`. Makes the content files more readable. Thank you for that. 🤗

**Expected behavior**  
I wish the same feature for the layout field. It outputs json as well, and it would be nice it's there too

## To reproduce
```
layout:
        label: Inhalt
        pretty: true
        type: layout
        layouts:
          - "1/1"
          - "1/2, 1/2"
          - "1/3, 1/3, 1/3"
          - "1/3, 2/3"
          - "2/3, 1/3"
```

## Your setup
**Kirby Version**  
3.9.1
