### ISSUE TITLE
Files: `accept` not working

### ISSUE THREAD

**Issue by nelhop** [k-next/kirby#5057]
## Description
The [accept](https://getkirby.com/docs/reference/panel/blueprints/file#accept) option to restrict file types is not working. All images can be selected.

```yml
# /site/blueprints/site.yml
fields:
  image:
    type: files
    accept:
      mime: image/svg+xml
      extension: svg
```

**Expected behavior**  
Only svg files should be possible to upload or select.

**Kirby Version**
 3.9.1

**Comment by afbora** [comment]
`accept` prop works for file blueprint (for ex: `/site/blueprints/files/svg.yml`) not for `files` field:
https://getkirby.com/docs/reference/panel/fields/files#upload-options__restricting-uploads-to-certain-file-types

````yaml
# /site/blueprints/pages/default.yml
fields:
  image:
    type: files
    uploads: svg # refers to `/site/blueprints/files/svg.yml`
````

````yaml
# /site/blueprints/files/svg.yml
accept:
    mime: image/svg+xml
    extension: svg
````

**Comment by nelhop** [comment]
Thanks for clarifying @afbora!

So there is no way to restrict the file type which can be selected, only the one that is uploaded?

**Comment by afbora** [comment]
- You can use `accept` prop in file blueprint to restrict file type in upload process.
- You can use `query` prop in files field to show specific file types:
https://getkirby.com/docs/reference/panel/fields/files#querying-files

````yaml
# /site/blueprints/pages/default.yml
fields:
  image:
    type: files
    uploads: svg # refers to `/site/blueprints/files/svg.yml`
    query: page.images.filterBy('extension', 'svg')
````
