### ISSUE TITLE
Blocks field: isn't fully disabled

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5100]
## Description

When blocks field is disabled (with `translate: false` or `disabled: true`), editable blocks are still editable like text-heading-quote blocks.

## To reproduce

Use following blueprint for blocks field:

````yaml
fields:
  text:
    type: blocks
    disabled: true
````

Or you can use `translate: false` on secondary language.
Then try to edit the editable fields like text-heading-quote blocks. 

## Your setup
**Kirby Version**  

3.6.x - 3.9.x
