### ISSUE TITLE
`image` info (e.g. files field) gets stored in localStorage, doesn't pick up blueprint changes

### ISSUE THREAD

**Issue by fvsch** [k-next/kirby#5103]
## Description

It looks like the `files` field type caches the config used to render image cards in a way that makes it near impossible to modify a page or section blueprint and see the results of changes in the panel.

When trying to modify field options like `info`, `image.ratio` or `image.back`, changes are not picked up, even when restarting the development server.

Changes are picked up when:

1. Renaming the field (e.g. from `my_image` to `my_image2`).
2. Removing the selected image and adding a new one.

Changes to other field options such as `label` or `layout` are picked up with a page refresh.

**Expected behavior**

It should be possible to work on blueprints and see the results in the panel, especially during development. Ideally that should happen automatically, without specific config tricks.

## To reproduce

1. Create a new plainkit project with `composer create-project getkirby/plainkit`

2. Start a development server with `composer start`

3. Create a `site/blueprints/pages/test.yml` blueprint with:

```yaml
title: Test page
fields:
  my_image:
    label: My Image
    type: files
    layout: cards
    max: 1
    image:
      ratio: 3/2
      back: green
```

4. In the panel, create a page of type “Test page”, and upload an image for the “My Image” field.

5. Change the blueprint to:

```yaml
title: Test page
fields:
  my_image:
    label: Very Cool Image
    type: files
    layout: cards
    max: 1
    info: "{{ file.dimensions }}"
    image:
      ratio: 1/1
      back: orange
```

6. In the panel, refresh the page. What I'm seeing is:
    - The label updates
    - The info footer doesn't appear
    - The image ratio and background don't change

## Your setup

**Kirby Version**  
3.9.2

**Console output**  
None

**Your system (please complete the following information)**
 - Device: Mac Air M1
 - OS: macOS 13.2.1
 - PHP: 8.2.3 (via Homebrew)
 - Browser: Chrome (stable)
