### ISSUE TITLE
Structure dropdown not loading correctly when content with `options` key is stored.

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5106]
## Description
When storing content in a structure with the options key the dropdown/context menu for the structure item is broken.

**Expected behavior**  
Correct dropdown would be shown, no matter the content keys.

**Screenshots**  
Broken
![image](https://user-images.githubusercontent.com/29142128/225379647-fe04c7a1-c33c-4e4c-bfa1-c2ad8259b023.png)

Correct
<img width="148" alt="CleanShot 2023-03-15 at 17 42 16@2x" src="https://user-images.githubusercontent.com/29142128/225380564-aabd6bf2-5268-4c9f-942d-885a2c19b50d.png">

## To reproduce

Sample code: 
Blueprint
```yaml
              filters:
                type: structure
                columns:
                  filter:
                    width: 1/6
                  options:
                    width: 5/6
                fields:
                  fieldid:
                    type: slug
                    required: true
                    width: 1/3
                    wizard:
                      field: filter
                      text: Sukurti ID
                    help:
                      en: Do not change this id, if you want the data to persist.
                  filter:
                    type: text
                    width: 1/6
                  options:
                    type: tags
                    width: 5/6
```

Content
```
Filters:

- 
  fieldid: color
  filter: Spalvytė
  options: >
    White, Black, Yellow, Purple, Blue,
    Green, Pink, Lime, Orange, Color in
    English, Baltų rožių spalva
- 
  fieldid: size
  filter: Size
  options: Small, Normal, Big
- 
  fieldid: length
  filter: Length
  options: Short, Normal, Long
- 
  fieldid: brand
  filter: Gamintojas
  options: >
    Daikin, Immergas, Midea, Zehnder,
    Hokkaido, Viessmann, Genova, Brink,
    Alpha Innotec, MGF Tools
- 
  fieldid: pastatymo-tipas
  filter: Boilerio tipas
  options: >
    Su integruotu boileriu, Su šalia
    pastatomu boileriu
- 
  fieldid: siurblio-tipas
  filter: Siurblio tipas
  options: Oras-vanduo, Geoterminis, Oras-oras
- 
  fieldid: dar-vienas-filtras
  filter: Dar vienas filtras
  options: Opcija vienas, Opcija du
```

## Your setup
**Kirby Version**  3.9.2
