### ISSUE TITLE
Using default values in a block that's in a structure bugs the block system

### ISSUE THREAD

**Issue by samzzi** [k-next/kirby#5111]
## Description
If you add default values to a blocks field that it is in a structure then the blocks start showing some weird behaviour. (until full page refresh)
If you don't add the default values it works as expected.

**Expected behavior**  

Blocks to behave like they always do 😊

**Screenrecording**  

https://x.gnx.li/Hxz46NyQ

## To reproduce
1. Create a structure field
2. Create a block field in the structure
3. Give the block field default values
4. Use it and see it fail 😅

```yaml
title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          test:
            type: structure
            fields:
              text:
                type: blocks
                default:
                  - type: heading
                    content:
                      level: h2
                      text: This is a test
                  - type: text
                    content:
                      text: This is a test
```

## Your setup
**Kirby Version**  
Latest plainkit install (3.9.2)

**Your system (please complete the following information)**
 - Device: Mac Studio
 - OS: Ventura 13.2.1
 - Browser: Chrome
 - Version: Latest (111.0.55, arm64)
