### ISSUE TITLE
Blueprints: inconsistent template(s) properties for Files and Pages sections

### ISSUE THREAD

**Issue by fvsch** [k-next/kirby#5125]
## Description

The [Pages section (reference)](https://getkirby.com/docs/reference/panel/sections/pages#section-properties) and [Files section (reference)](https://getkirby.com/docs/reference/panel/sections/pages#section-properties) have a similar feature where you can set the template(s) to be used to:

1. Filter the list by template
2. Set the template(s) that can be used when creating a new item

Sadly they're implemented rather differently:

- Pages section:
  - `templates` property, which takes an array of strings
  - but if you provide a single string (`templates: foo`), that works too
  - and if you use `template` instead of `templates`, that works too
- Files section:
  - `template` property, which takes a single string
  - if you provide an array of strings, that's an error
  - if you use `templates` instead of `template`, it's ignored

**Expected behavior**  

It would be great if this API could be a bit more consistent. When you've just set up a Pages section, you kinda expect that similar features would be available for the Files section, but those subtle differences will get in the way.

Though I understand that for file _creation_, only one template name can be used, because there's no UI shown to users to let them pick a template for the file.

Maybe that's a problem, and a modal UI asking to select a template (one more than one is configured) should be shown on upload? Or maybe just use the first template if a list is provided?

## To reproduce

Create a page blueprint with:

```yaml
sections:
  cover:
    type: files
    label: Cover image
    # correct
    template: cover-image
    # unsupported, might be good to also support?
    # template: [cover-image]
    # templates: cover-image
    # templates: [cover-image]
  gallery:
    type: pages
    label: Gallery
    # correct
    templates: [gallery]
    # also supported
    templates: gallery
    template: [gallery]
    template: gallery
```

## Your setup

**Kirby Version**  
3.9.3-rc.1

**Console output**  
none
