### ISSUE TITLE
Select field with default value in multi language site not filled

### ISSUE THREAD

**Issue by Small-Systems** [k-next/kirby#5140]
## Description
If you have a select field which has a default option, and this field is set not to translate, when you create a page in a non-default language in a multi language setup, the field remains empty. In my case the field is required, and the options are pages pulled dynamically from a query, with one page being set as the default.

**Expected behavior**  
Even in a non-default language I would except the value to be filled for the default language, otherwise the field remains empty, and is not automatically select once switching to the default language.

**Screenshots**  
<img width="420" alt="Screenshot 2023-04-07 at 09 03 18" src="https://user-images.githubusercontent.com/2116283/230559313-1c893402-8759-4799-8f74-8c4ec0e1e956.png">

## To reproduce

1. Multi-language site
2. Create page in non-default language
3. Select field is not filled with default value

**Field example**
```
fields:
  category:
    label: Category
    translate: false
    required: true
    type: select
    default: architecture
    options:
      design: Design
      architecture: Architecture
      photography: Photography
      3d: 3D
      web: Web
```

## Your setup
**Kirby Version**  
3.9.3
