### ISSUE TITLE
user permissions: changeRole has no effect

### ISSUE THREAD

**Issue by jaro-io** [k-next/kirby#5146]
**hey there lovely kirby team 🌻**
i am struggling with two things related to user permissions. i don’t know if they are related.
[this](https://github.com/getkirby/kirby/issues/5147) is the other issue. feel free to merge if needed.

## description
i would like to control what roles users with a certain role are allowed to change. for example a `manager` should be able to change roles for other users. but an `assistant` shouldn’t be able to do that. when i set the `changeRole` permissions to `true` or `false` in my user blueprints it doesn’t seem to have any effect.

also it seems like there is a difference between [this](https://getkirby.com/docs/reference/panel/blueprints/user) doc and [this](https://getkirby.com/docs/guide/users/permissions) doc. in the first one it seems like `changeRole` is only available for `user`, not `users`. in the second one it seems like it’s available for both.

<img width="1097" alt="Screenshot 2023-04-13 at 18 40 22" src="https://user-images.githubusercontent.com/20298313/231827473-a81a7011-b5e6-466a-8639-3a3e27318a17.png">

<img width="568" alt="Screenshot 2023-04-13 at 18 38 58" src="https://user-images.githubusercontent.com/20298313/231827288-f0601ca6-edad-4ec2-a983-8aad06828d26.png">

## to reproduce
start with a clean starterkit. add a new user blueprint with the following permissions.

```yml
permissions:
    user:
        delete: false # works, this user can’t delete itself
        changeRole: true # doesn’t work, this user can’t change its role
    users:
        changeRole: true # doesn’t work, this user can’t change other user’s roles
```

<img width="1457" alt="Screenshot 2023-04-13 at 18 27 13" src="https://user-images.githubusercontent.com/20298313/231824469-d5d9f5df-c85c-451b-8e14-e9b4f7ae627a.png">

## your setup
kirby 3.9.3

thank you for your help!
🤍 ✨
