### ISSUE TITLE
Models with namespaces not working

### ISSUE THREAD

**Issue by owzim** [k-next/kirby#5160]
## Description

an example pages section to test it out:

```yaml
somepagesection:
  type: pages
  layout: table
  templates:
    - event
  columns:
    foo:
      value: '{{ page.foo() }}'
```

Working:

```php
use \Kirby\Cms\Page;

class EventPage extends Page
{
    public function foo(): string
    {
        return 'foo';
    }
}
```

Not working:

```php
namespace Foobar\BarBaz;

use \Kirby\Cms\Page;

class EventPage extends Page
{
    public function foo(): string
    {
        return 'foo';
    }
}
```

**Expected behavior**  

The model should be used no matter what namespace

## Your setup
**Kirby Version**: 3.9.4
**PHP**: 8.1.16

**Your system (please complete the following information)**
 - OS: macOS 12.5.1
