### ISSUE TITLE
Panel: `default` value not working for toggles field

### ISSUE THREAD

**Issue by owzim** [k-next/kirby#5163]
## Description

It is neither highlighting the respective toggle, nor is it actually assigning it, hence not saving the value on save.

## To reproduce

use this simple toggle field

```yaml
footoggles:
  type: toggles
  label: Foo
  default: one # also tested `default: 0`, because options is an array, but also not working
  options:
    - value: one
      icon: bars
    - value: two
      icon: wand
```

... also tried assoc array style, but the bug persists, plus the icons disappear

```yaml
options:
  one:
    icon: bars
  two:
    icon: wand
```

## Your setup
**Kirby Version**: 3.9.4
**PHP Version**: 8.1.16

**Your system (please complete the following information)**
 - OS: macOS 12.5.1 
 - Browser: Firefox 112.0.2
