### ISSUE TITLE
Structure field: sort/move items via keyboard

### ISSUE THREAD

**Issue by FTB-Volmarstein** [k-next/kirby#5172]
## Description
Hi there, great job, we love Kirby quite a lot.
We have following structure table:
```
      answerOptions:
        label: Antwortmöglichkeiten
        type: structure
        columns:
          optionImage:
            width: 1/4
          optionLabel:
            width: 1/4
          optionValue:
            width: 1/4
```
and we would like to be able to edit (and change the order of) the items without the need of using a pointer device like a mouse.

**Expected behavior**  
Either the list items should be in tab-order and the edit-dialog should open on keypress, or the 3-dot-menu should additionally to "Duplicate" and "Remove" contain the actions "Edit", "Move Up", and "Move down".

**Screenshots**  

## To reproduce

1. Login to the panel at https://trykirby.com
2. Go to panel/pages/restaurant
3. Try to edit an entry at "Starter" without using the touchpad or mouse.

## Your setup
**Kirby Version**  
3.8.2 (https://trykirby.com: 3.9.4)

**Your system (please complete the following information)**
Should be platform independent

We absolutely appreciate your efforts in maintaining Kirby as an accessible CMS-solution and therefore this hint to fix even the last problems. Thanks a lot.
