### ISSUE TITLE
[v4] New File Picker not working inside Block

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5184]
## Description
With Kirby 4.0, I now get an error when I try to open the file picker inside a Block:
<img width="480" alt="CleanShot 2023-05-25 at 11 54 03@2x" src="https://github.com/getkirby/kirby/assets/29142128/92e3cf80-3570-4c35-a7c6-c26d424d478d">
The same blueprint works fine when placed outside a block.

```json
{
    "status": "error",
    "message": "Call to a member function filepicker() on array",
    "code": 500,
    "exception": "Error",
    "key": null,
    "file": "../kirby/config/fields/files.php",
    "line": 95,
    "details": [],
    "route": "pages/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)/fields/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)(?:/(.*))?"
}
```

**Expected behavior**  
The File picker should open normally.

## To reproduce
Use my example blueprint for a field inside a block:
```yaml
      images:
        label:
          de: Hintergrundbilder
          en: Background images
        type: files
        uploads:
          parent: site.find('assets')
          template: image
        image:
          cover: false
        text: '{{ file.alt }} ({{ file.filename }})'
        info: '{{ file.tags.join(", ") }}'
        query: site.find('assets').images.filterBy('template', 'image')
        multiple: true
        layout: cards
        size: medium
```
I tested it with, and without a query, and it seemingly doesn't matter.
The same blueprint works fine on page level.

## Your setup
**Kirby Version**  4.0-alpha.1
