### ISSUE TITLE
[v4] Files field inside a block: drawer closes after upload

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#5214]
1. Have a files field inside a block:

```yml
fields:
  bar:
    type: blocks
    fieldsets:
      foo:
        fields:
          images:
            type: files
```

2. Open block, upload new file
3. Block drawer gets closed too after upload

Expected: Drawer remains open, files field updated with newly uploaded file
