### ISSUE TITLE
[v4] Any page can be moved under the site

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5218]
I can move a note or album page under to site/root on starterkit. This should not happen.

````yaml
columns:
  - width: 1/2
    sections:
      albums: sections/albums

  - width: 1/2
    sections:
      notes: 
        extends: sections/notes
        parent: kirby.page("notes")

      pages:
        type: pages
        create: default
        templates:
          - about
          - home
          - default
````

_Originally posted by @afbora in https://github.com/getkirby/kirby/issues/5211#issuecomment-1567483766_
