### ISSUE TITLE
[v4] Textarea toolbar overflow with too many buttons

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#5254]
## Description
I noticed overlapping toolbar buttons when using too many (custom) buttons, putting the field in a smaller column or a blocks field, or viewing the Panel on a mobile screen. Toolbar buttons can become inaccessible this way.

**Expected behavior**  
I'd expect the toolbar to become scrollable or the toolbar buttons to wrap to a new line. Technically a solution could be to prevent the `k-input-element` parent (a flex item) to lose its `min-width: auto` style. Otherwise the toolbars `max-width` won't have an effect.

**Screenshots**  

<img width="379" alt="CleanShot 2023-06-07 at 16 25 30@2x" src="https://github.com/getkirby/kirby/assets/7975568/66be518a-5e5f-4bb2-a1b5-633d5f5c2332">

## To reproduce

1. Add a textarea field to your blueprint
2. Register some custom buttons, put the textarea in a small column or view it on a mobile screen
3. Notice how the buttons overlap

## Suggestion

Here's my quick panel.css fix that might be helpful to you:

```css
.k-toolbar {
  flex-wrap: wrap; /* allow toolbar buttons to wrap to a new line */
}
.k-input-element {
  min-width: 0; /* overwrite the default value flex items get */
}
.k-toolbar-button {
  flex-shrink: 0; /* prevent the buttons from shrinking */
}
```

I noticed you dropped the `k-toolbar-buttons` wrapper in this release for some reason. When setting `overflow-x: auto` on `k-toolbar` we have a problem with the heading dropdown. Maybe you'll have to reintroduce this wrapper?

## Your setup
**Kirby Version**  
4.0.0-alpha.2

**Your system (please complete the following information)**
 - OS: macOS 13.4
 - Browser: Chrome
 - Version:  114.0.5735.106
