### ISSUE TITLE
Stats section: Support for translation arrays in the `value` and `link` props

### ISSUE THREAD

**Issue by herrajon** [k-next/kirby#5256]
## Description
**The beautiful stats section is pretty useful in displaying info for the backend users. It also comes in very handy when making shortcuts to various backend pages for the editors.**

### **Ze Problem**  
There is no problem with this when displaying the backend only in one language. But when two or more languages come into play then the shit hits the fan. The reports have few properties. Most of them are translateable thankfully. The value property reports error when used with translation strings in the blueprint and hide the stats section alltogether while at it.

This:

```

          stats:
            type: stats
            size: huge
            label: 
              is: Hraðbergið
              en: Shortcuts
            reports:
              - label:
                  is: Tilgangurinn með þessu öllu 
                  en: The purpose of our efforts
                value:
                  is: Markmið 
                  en: Goal
```

Produces this error:

<img width="473" alt="image" src="https://github.com/getkirby/kirby/assets/182769/eab2d4d1-1102-4031-94f5-6bde0a21427a">

But not this one:

```

          stats:
            type: stats
            size: huge
            label: 
              is: Hraðbergið
              en: Shortcuts
            reports:
              - label:
                  is: Tilgangurinn með þessu öllu 
                  en: The purpose of our efforts
                value: Markmið

```

The trigger being the translationstring belonging to value (is:markmið & en:goal) in the reports part. Works fine if value is in Icelandic or English (not translated). The value field undoubtably not intented for text but it works with it while there is only one language.

### The link property

Another one of the reports properties that would be very nice to have in translated version is the link property. 

This works fine:

```
                link: /pages/corvus

```

But this breaks it (with or without quotation marks):

```
                link: 
                  is: /pages/hrafn
                  en: /pages/corvus

```

In many cases there is a different path needed for different language.

### Closing

This is a very steep shot I know. But this is so damn handy. Would be a nice to have.

Tested on Kirby CMS 3.9.5 locally iMac Ventura 13.4/nGinx 1.21.6/PHP 8.1.3 in Safari.

Thanks for reading.

-j

**Comment by lukasbestle** [comment]
A translation array is currently only supported in the `label` and `info` props of the stats section. For `value` and `link` you can use a query to make those props dynamic based on the language (or in fact based on any dynamic information):

```yaml
stats:
  type: stats
  size: huge
  label: 
    is: Hraðbergið
    en: Shortcuts
  reports:
    - label:
        is: Tilgangurinn með þessu öllu 
        en: The purpose of our efforts
      link: "{{ page.statsLink }}"
      value: "{{ page.statsValue }}"
```

You can then use a page model or page method to define those methods and use `I18n::translate(['is' => ..., 'en' => ...])` inside to return the translated value you need.

I still agree that direct support for translation arrays in the blueprint could be a nice enhancement.
