### ISSUE TITLE
[v4] File field with custom upload template throws error when in File blueprint

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5261]
## Description
When using a file field with a custom upload template specified (e.g. `uploads: image`), the file field will not load and throw an error. The same blueprint works fine on pages or the site - it also previously worked in v3.9.4.

**Expected behavior**  
The file field would work the same as on pages or the site.

**Screenshots**  
![CleanShot 2023-06-10 at 01 52 39@2x](https://github.com/getkirby/kirby/assets/29142128/367d1eea-e875-4739-b656-6e66adee5bfa)

## To reproduce
Add a file field to your page blueprint and specify a template via the `uploads.template` or `uploads` property - both fail to load the blueprint.

My example blueprint - but should also fail with others:
```yaml
label:
  de: Bild
  en: Image
type: files
uploads:
  parent: page('page://assets')
  template: image
multiple: false
image:
  cover: false
text: '{{ file.alt }}'
info: '{{ file.filename }}'
query: site.find('assets').images.filterBy('template', 'image')
```

It works in a page but fails on a file blueprint.

## Your setup
**Kirby Version**  4.0.0-alpha.2
