### ISSUE TITLE
If you use a layout with multiple rows in a structure field the "layout dropdown" disappears 

### ISSUE THREAD

**Issue by samzzi** [k-next/kirby#5267]
## Description
When using the layout field within a structure field, the options dropdown menu from the layout field disappears behind the next row, except for the last layout row where it is shown as expected.

**Expected behavior**  
The options dropdown menu from the layout field should be displayed on top of the other blocks, allowing easy selection of layout options.

**Screenshots**  
![2023-06-11_19 33 12@2x](https://github.com/getkirby/kirby/assets/32242279/96dd865e-9474-4a90-aecb-d4ba65b5322f)

## To reproduce
1. Create a page with a structure field containing a layout field
2. Add multiple layout rows within 1 structure row
3. Notice that when you click on the options dropdown menu of the layout field in the first few rows, it disappears behind the next block, making it difficult to select an option.
4. Scroll down to the last row of the structure field and click on the options dropdown menu of the layout field.
5. Observe that the options dropdown menu is displayed as expected, on top of the other blocks.

## Example blueprint used in plainkit
```yaml
title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          structureField:
            type: structure
            label: Structure field
            columns:
              lblStep:
                width: 2/3
              form:
                width: 1/3
            fields:
              layoutField:
                type: layout
                layouts:
                  - "1/1"
                  - "1/2, 1/2"
                  - "1/3, 1/3, 1/3"
                  - "1/4, 1/4, 1/4, 1/4"
                  - "2/3, 1/3"
                  - "1/3, 2/3"
                  - "1/2, 1/4, 1/4"
                  - "1/4, 1/4, 1/2"
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files
```

## Your setup
**Kirby Version**  : 3.9.5

**Your system (please complete the following information)**
 - Device: Apple Studio
 - OS: macOS Ventura 13.4
 - Browser: Chrome
 - Version: 114.0
