### ISSUE TITLE
[v4] Keyboard shortcuts for Nested Blocks field get applied to parent

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5272]
## Description
When using nested blocks inside a field, hotkeys will be applied both to the selected blocks field and the parent blocks field.

https://streamable.com/idlffi

**Expected behavior**  
Keyboard shortcuts would not apply to parent if selecting a nested blocks field

## Your setup
**Kirby Version**  4.0.0-alpha.2

**Comment by distantnative** [comment]
@tobimori your video unfortunately expired. Could you give me a few more details

I tried it with this, but so far haven't reproduced it

```yml
foo:
  type: blocks
  fieldsets:
    - heading
    bar:
    fields:
      foofoo:
        type: blocks
```

Then added some blocks in `foo`, one of type `bar`, opened `bar` in the drawer and added some blocks there. When I now do keyboard shortcuts inside the drawer, `foo` remains unaffected.

Are you doing something differently? Or what browser etc. are you using?
