### ISSUE TITLE
Query: default `$entries` not available when overwritten by provided `$data`

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5276]
## Description
Since upgrading to v4-alpha.3, my file fields with custom uploads template don't work anymore.

I'm using the following blueprints - it works perfectly fine when removing the `uploads.template` setting.
```yaml
label:
  de: Bild
  en: Image
type: files
uploads:
  parent: page('page://assets')
  template: image
multiple: false
image:
  cover: false
text: "{{ file.alt }}"
info: "{{ file.filename }}"
query: site.find('assets').images.filterBy('template', 'image')
```

![CleanShot 2023-06-13 at 12 46 54@2x](https://github.com/getkirby/kirby/assets/29142128/b8fb0ca7-49fb-4bb5-b8d2-4de39d5f9402)

## Your setup
**Kirby Version** 4.0.0-alpha.3
