### ISSUE TITLE
[v4] Link Field: Allow custom queries for Pages/Files links

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5279]
## Description

I use a lot of "pseudo-pages" that have no real content but are instead only used for e.g. storing files.

![CleanShot 2023-06-13 at 13 05 28@2x](https://github.com/getkirby/kirby/assets/29142128/f4b639f0-a9e6-4073-8f94-01984ac08fdf)

It's impossible that a Page like Home can contain any assets in my setup, which is why I want to limit my users to be only able to select files in pages where files can be uploaded to.

In the same manner, I don't want my users to be able to select a page that has the template for such a "pseudo-page" as they never have any content and just redirect in the frontend.

![CleanShot 2023-06-13 at 13 07 59@2x](https://github.com/getkirby/kirby/assets/29142128/7bd240a9-1099-4374-9b48-7138aa242b57) 

## Your setup
**Kirby Version**  4.0.0-alpha.2 (alpha-3 broke the file picker in the link field)

**Comment by distantnative** [comment]
I think we're sliding into feature request territory here to be honest. I think these should rather go on Nolt to be honest.

**Comment by tobimori** [comment]
I'm happy to share this on Nolt too, yet I don't think this would fit there as it's not really a new feature request, but rather embracing collaboration & discussion about features in active development. 

You can kinda compare it to when you released the List field: Why was there no option to force it to a `bulletList` or `orderedList`, when the Writer field could do that? Having queries, toggling Link Field types, or other configuration options are expected from a Core feature that wants to replace plugins - it's not that such configuration options are new to Kirby, other fields had them from the beginning.

**Comment by lukasbestle** [comment]
I'd say we can treat this as an enhancement. If we still have time before the launch after all bugs are fixed, we can try to tackle this, otherwise we can move it to Nolt.

**Comment by afbora** [comment]
What would be syntax?

### Option 1
````yaml
fields:
  link:
    type: link
      options:
        page: site.children.filterBy('template', 'default')
        - anchor
````

### Option 2
````yaml
fields:
  link:
    type: link
      options:
        - page
        - anchor
      query:
        page: site.children.filterBy('template', 'default')
````
