### ISSUE TITLE
Users field: current user stored unless default set to false

### ISSUE THREAD

**Issue by texnixe** [k-next/kirby#5284]
## Description
With a users field like this

```
Title: Test

fields:
  mentor:
    type: users
    query: kirby.users.filterBy('role', 'in', ['student', 'teacher'])
```

When you create a new page via the frontend, not matter what you pass to `mentor` or don't set the field, the current users is always stored. The same happens when creating a new Page via the Panel.

Example frontend code:

```
kirby()->impersonate('kirby');
$page = Page::create([
  'slug'     => 'new-page',
  'template' => 'test',
  'content' => [
    'title'  => 'New Page',
  ]
]);
```
It needs:
```
  mentor:
    type: users
    query: kirby.users.filterBy('role', 'in', ['student', 'teacher'])
    default: false
```
to prevent that behavior.

**Expected behavior**  
The field should stay empty when no default user is explicitly set.

## Your setup

Tested with Kirby 3.9.5
