### ISSUE TITLE
[v4] Translations for label of title field not working in page create dialog

### ISSUE THREAD

**Issue by ralfgoeke** [k-next/kirby#5286]
## Description

In the default.yml blueprint, we can overwrite the title field's label for the page creation dialog like so:

```yaml
create:
  title:
    label: Megacooler Seitentitel
```
![title-no-translations](https://github.com/getkirby/kirby/assets/6228942/fcdc64ed-a70d-4b82-a7eb-c4fab7443fc1)

The above code works fine, but adding translations result in this:

```yaml
create:
  title:
    label:
      de: Megacooler Seitentitel
      en: Superduper page title
```

![title-translations](https://github.com/getkirby/kirby/assets/6228942/a45cf85e-3b0d-48eb-a5e5-ae4c2248a883)

**Expected behavior**  
Translations for labels should work in all places

## Your setup
**Kirby Version**  
4.0.0-alpha.3

**Console output**  
none

And... *cough*... it would be wonderful to be able to restrict the maxlength of the title, see [Nolt 281](https://kirby.nolt.io/281). Just in case it's easy to do in V4. 😇️
