### ISSUE TITLE
[v4] Page picker not correctly centered when info text is too long

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5321]
## Description
When having a very long info text, even if truncated, it results in the page picker not being centered correctly due to an issue with using grid for centering.

**Screenshots**  

![CleanShot 2023-06-22 at 17 27 23@2x](https://github.com/getkirby/kirby/assets/29142128/9c7dd5f4-fb96-4ccc-bf13-562c5bfb350d)

For more context, you can read through this [Discord conversation.](https://discord.com/channels/525634039965679616/1111220342522904706/1121455863203385465)

**Solutions**
Switch `.k-overlay` to centering with flex:

```css
.k-overlay[data-centered="true"] {
  display: flex;
  align-items: center;
  justify-content: center;
}
```
**or** (suggested by @medienbaecker)

Add `min-width: 0;` to `.k-dialog`.
More info here: https://defensivecss.dev/tip/grid-min-content-size/

## Your setup

**Kirby Version**  4.0.0-alpha.3
