### ISSUE TITLE
[v4] Image field overflows grid in block

### ISSUE THREAD

**Issue by pxlrbt** [k-next/kirby#5326]
## Description

Inside a block the image field overflows the containing grid when width is `1/2` or less and size is `large`.

**Expected behavior**  
Maximum width of image field within grid column.

**Screenshots**  
<img width="598" alt="image" src="https://github.com/getkirby/kirby/assets/22632550/2ecc4ce5-c0c9-4e1a-9bfa-77f42a4313db">

## To reproduce

1. Add an image field in a blocks fields
2. Set `width: 1/2`
3. Set `size: large`
4. Set browser window size to a value between 1040px and 1240px

## Your setup
**Kirby Version**  
4.0.0-alpha.3

**Your system**
 - Device: Macbok Air
 - OS: macOS
 - Browser: Chromium based

**Additional context**  

The following CSS var definition is the source of the issue:

```css
@media screen and (min-width: 65em) {
    .k-cards-items[data-size=large] {
        --min: 32rem;
    }
}
```
