### ISSUE TITLE
[v4] File Upload to a FilesField inside a FormDrawer will close the Drawer

### ISSUE THREAD

**Issue by ovenum** [k-next/kirby#5345]
## Description
When uploading a file to a `Files` subfield displayed in the FormDrawer of an ObjectField, the FormDrawer closes after the upload is completed.

**Expected behavior**  
The Drawer stays open after the upload is completed.

**Screenshots**  

https://github.com/getkirby/kirby/assets/47149622/f5d7f59c-0afe-4748-ae75-c50813b700fe

## To reproduce
Create a simple page blueprint with an object field that contains a files subfield and upload a new file to that field via the open FormDrawer.

```yaml
objectUploadTest:
  type: object
  fields:
    uploadTest:
      type: files
      multiple: false
```
## Your setup
**Kirby Version**  
Kirby 4.0.0-alpha.4

**Console output**  

**Your system (please complete the following information)**
 - OS: macOS
 - Browser: Chome 
 - Version: 114.0.5735.198 (Official Build) (arm64)
