### ISSUE TITLE
[v4] Opening the Drawer of an Object field inside a Block field is not working

### ISSUE THREAD

**Issue by ovenum** [k-next/kirby#5347]
## Description

Trying to edit an Object field that is part of a Kirby Block field will cause the Panel to to display an error message: `Cannot read properties of undefined (reading 'show')`. Also the object fields subfields are not rendered inside the FormFieldsDrawer, instead the notifcation _This drawer has no fields_ is shown.

This works in 3.9.5.

**Expected behavior**  
The Object field Drawer to open and the Drawer breadcrumb path to display the current location.

**Screenshots**  

https://github.com/getkirby/kirby/assets/47149622/1def410d-35dc-4d98-aad1-0039b854ace1

## To reproduce
Create a simple pages blueprint that contains a Blocks field with a  Block that has a object subfield and try to edit the subfields of the object field. (see video above)

```yaml
sections:
  fields:
    type: fields
    fields:
      objectInBlocksTest:
        type: blocks
        fieldsets:
          - type: text
            fields:
              text:
                type: writer
              objectfield:
                type: object
                fields:
                  objectTextField:
                    type: writer
```

## Your setup
**Kirby Version**  
Kirby 4.0.0-alpha.4

**Your system (please complete the following information)**
 - OS: macOS
 - Browser: Chrome
 - Version: 114.0.5735.198 (Official Build) (arm64)
