### ISSUE TITLE
[v4] Additional divider at end of Node list when disabling nodes

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5351]
## Description
![CleanShot 2023-07-06 at 00 14 39@2x](https://github.com/getkirby/kirby/assets/29142128/51cd26f3-a234-49d8-a736-e322d0bdc18d)

Example config:
```yaml
writer:
	type: writer
	label: Text
	marks:
	  - bold
	  - link
	  - email
	nodes:
	  - heading
	  - paragraph
	headings:
	  - 2
```

## Your setup
**Kirby Version**  4.0.0-alpha.4
