### ISSUE TITLE
[v4] Issue with `object` field's drawer in block

### ISSUE THREAD

**Issue by apademide** [k-next/kirby#5354]
## Description
After trying to use `object` fields in a custom block, I got an error with the drawer:
<img width="800" alt="undefined is not an object (evaluating 'this.$refs.drawer.show')" src="https://github.com/getkirby/kirby/assets/63295420/dad9ad1f-d542-4225-89f8-9d563f8f8a31">

After testing a few variants, it only appears within objects in blocks.
I tried with both "plugin-custom" and "blueprint-custom" blocks:

```yml
main:
  type: blocks
  label: Test
  translate: false
  required: true
  fieldsets:
    test:
      label: Test
      type: group
      fieldsets:
        # custom from a plugin, blueprint below
        test1: true
        test2:
          name: Test block 2
          fields:
            object:
              fields:
                text: true
```
`blocks/test.yml` in plugin:
```yml
name: Test block
tabs:
  main:
    fields:
      size:
        type: object
        fields:
          text: true
```

## To reproduce
Minimal page blueprint sufficient to get the error: 
```yml
fields:
  test:
    type: blocks
    fieldsets:
      test:
        name: Test block
        fields:
          object:
            type: object
            fields:
              text: true
```
Then add a block of type Test and try to enter the object field.

Using the exact same object outside a block works as expected.

## Your setup
**Kirby Version**  
4.0.0-alpha.4

**Console output**
<img width="483" alt="index.js:1:368579" src="https://github.com/getkirby/kirby/assets/63295420/e564ec09-9372-4777-8e0b-6f56385e2871">

**Your system (please complete the following information)**
 - OS: macOS 13.0
 - Browser: Safari 16.1
