### ISSUE TITLE
[v4] Nested structure loses content

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#5385]
## Description
When using a structure field inside of a structure field, the content of the entries in the nested structure field seems to get lost.

![nested-structure](https://github.com/getkirby/kirby/assets/7975568/21c3f384-e79a-49c2-a4be-822237b26c91)

## To reproduce

1. Create a nested structure field:
```yml
structure:
    fields:
      structure:
        label: Nested Structure
        type: structure
        fields:
          text: true
```
2. Add a structure entry to the top-level structure field
3. Add an entry to the nested structure field with some content
4. Close the drawer, click the little checkmark button or hit ⌘S 
5. The content is gone

## Your setup
**Kirby Version**  
4.0.0-alpha.5

**Your system (please complete the following information)**
 - OS: macOS Ventura 13.4.1
 - Browser: Chrome
 - Version: 115

**Comment by bastianallgeier** [comment]
I've just set up a test setup to reproduce it and unfortunately it happens for me as well. Just to confirm, do you already notice that the content will stay as soon as you try again?

**Comment by medienbaecker** [comment]
> Just to confirm, do you already notice that the content will stay as soon as you try again?

@bastianallgeier Sorry, I'm afraid I don't understand your question. It looks like the content is just cosmetic. When editing the nested structure field I don't even get the "Revert/Save" prompt.

**Comment by afbora** [comment]
As far as I have tested, the last added row is not emitted. The input is triggered but not saved to localStorage. But I could not find the cause of the issue.

**Comment by MathiasGmeiner** [comment]
For me it happens for nested blocks as well.

**Comment by bastianallgeier** [comment]
@MathiasGmeiner nested blocks in a structure field?

**Comment by MathiasGmeiner** [comment]
@bastianallgeier no, sorry for being so vague. I'm dealing with nested blocks in a blocks field. Could this be a different issue altogether? My first try was a structure field within a block field, and then I tried a block inside a block field.

**Comment by bastianallgeier** [comment]
@MathiasGmeiner I'll try to reproduce this, but in our current nested blocks test setup I didn't notice this so far.

**Comment by MathiasGmeiner** [comment]
@bastianallgeier ok, let me know if I can help.

**Comment by vincentrouleau** [comment]
I have the same issue in nested structures. I can send you my BPs if needed.

**Comment by MathiasGmeiner** [comment]
I'm not sure if I'm doing something wrong with the nested block setup. 
This is my setup:

test.yml
```yml
name: Test
fields:
  blocks:
    type: blocks
    fieldsets:
      - test-item
```

test-item.yml
```yml
name: Test Item
fields:
  text:
    label: Test
    type: text
```
![CleanShot 2023-07-21 at 07 44 37](https://github.com/getkirby/kirby/assets/103595/acfd5be8-13b8-4ac5-b3a7-cee22230b52e)
