### ISSUE TITLE
[v4] Create page dialog: custom status fails when fields are required

### ISSUE THREAD

**Issue by vauvarin** [k-next/kirby#5397]
## Description
Create unilsted page directly with the new option "create" display an error message when the blueprint has required fields
```
title: Project
create:
  status: unlisted
  redirect: false

...

fields:
  f_website_dev:
    label: URL du site de développement
    type: url
    required: true
```

A page is created but in draft mode.

**Expected behavior**  
A new unlisted page is created.

**Screenshots**  
https://imgtr.ee/image/1b4h7

**Your system (please complete the following information)**
 - Device: Desktop
 - OS: Linux
 - Browser: Firefox
