### ISSUE TITLE
[v4] longer help text ignores margin to pages section

### ISSUE THREAD

**Issue by elyukai** [k-next/kirby#5406]
## Description
The collection footer seems to be limited in height so that longer content exceeds the space and due to flexbox layout it overflows on both top and bottom, ignoring the top margin from the `<footer>` element.

**Expected behavior**  
The `<footer>` element should grow if the content grows. Or at least the margin should still be present.

**Screenshots**  
<img width="475" alt="image" src="https://github.com/getkirby/kirby/assets/11094577/80be40bb-d39c-4e93-b98b-824c26a3d81b">
<img width="447" alt="image" src="https://github.com/getkirby/kirby/assets/11094577/9e45e2dd-077b-4367-ad34-676431123447">

## To reproduce

```yml
title: Einfache Seite

columns:
  main:
    # ...
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        label: Weitere Seiten
        template: default
        help: Gelistete Seiten werden bis Hierarchieebene 2 in der Navigation angezeigt. Gelistete Seiten werden aber immer als Unterseiten auf der Seite angezeigt. Ihre Sortierung wird an allen Orten beibehalten.
```

## Your setup
**Kirby Version**  
4.0.0-alpha.5

**Console output**  
N/A

**Your system (please complete the following information)**
 - Device: MacBook Pro 2021
 - OS: macOS 13.4.1 (c)
 - Browser: Safari
 - Version: 16.5.2

**Additional context**  
N/A
