### ISSUE TITLE
[v4] Block field preview: Different layout depending on column or field width

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [k-next/kirby#5417]
## Description
The layout of the block field preview is different inside a `1/2` field compared to a `1/2` column. In a `1/2` field, the fields should probably also be displayed below one another.

## Screenshots
```yml
columns:
  - width: 1/1
    fields:
      blocks:
        type: blocks
        width: 1/2
```
![1](https://github.com/getkirby/kirby/assets/77532479/aef916e6-32e4-49bf-9eb5-13529faccb11)

---

```yml
columns:
  - width: 1/2
    fields:
      blocks:
        type: blocks
        width: 1/1
```
![2](https://github.com/getkirby/kirby/assets/77532479/48887a1c-cd68-44e2-8f59-970844089af1)

## Your setup
**Kirby Version**  
4.0.0-alpha.5
