### ISSUE TITLE
[v4] You can't use an object in a structure field

### ISSUE THREAD

**Issue by samzzi** [k-next/kirby#5427]
## Description
If you add a field of type object in a structure the panel doesn't seem to be able to save its values.

**Expected behavior**  
To be able to save the values of the object. It does work in 3.x

## To reproduce

Add following blueprint:

```yaml
fields:
  mystructure:
    type: structure
    fields:
      myfield:
        type: object
        fields:
          title:
            type: text
          label:
            type: text
```

And try to fill the object via the panel.

## Your setup
**Kirby Version**  
4.0.0-alpha.5

**Your system (please complete the following information)**
 - Device: Macbook pro
 - OS: macOS Ventura 13.5
 - Browser: Chrome
 - Version: 115
