### ISSUE TITLE
[v4] Adding a sortBy to a structure crashes the browser when accessing it via the panel

### ISSUE THREAD

**Issue by samzzi** [k-next/kirby#5448]
## Description
When you add a sort to a structure field and open the structure item via the panel the browser completely crashes / hangs. (Nothing works anymore, I need to close it to carry on)

You'll see the bug in action in this video, at the end you will see that the browser becomes unresponsive. https://x.gnx.li/8Xgk1TWp

**Expected behavior**  
No crashing browser.

## To reproduce
* Add a sortBy to a structure field.

ex.:
```yaml
title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          structureField:
            type: structure
            label: Structure field
            sortBy: test asc
            fields:
              test:
                type: text
                label: Test
```

* Go to the panel and try to add or edit an item in the structure
* Browser hangs

## Your setup
**Kirby Version**  
4.0.0-alpha.6

**Console output**  
Nothing

**Your system (please complete the following information)**
 - Device: Apple studio
 - OS: macOS Ventura 13.4.1
 - Browser: Tested on chrome and safari (latest)
