### ISSUE TITLE
Files: Default from Template not set on upload

### ISSUE THREAD

**Issue by plain-solutions-gmbh** [k-next/kirby#5454]
## Description
If you upload an image via panel, the default field values thats given in the file blueprint will be not saved in the content file

**Expected behavior**  
Prefill fields on upload

## To reproduce
1. Create a file blueprint 'image'

```
accept:
  type: image
fields:
  cropable:
    type: toggle
    default: true
    width: 1/2
```
2. create a file field:

```
fields:
  image:
    type: files
    uploads:
      template: image
```
3. Upload a file
4. Take a look at the content file of the image:

```
Uuid: 9lubd3aMxbIwLWcD

----

Template: image
```

The information `cropable`is missing!

## Your setup
**Kirby Version**  
4.0.0-alpha.5
