### ISSUE TITLE
[v4] Date field in Structure field crashes browser

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5455]
## Description
When adding a new entry to a Structure field or opening the Date view, my browser tab crashes in 4.0-alpha.6. It works fine in 4.0-alpha.5.

Blueprint
```yaml    
         dates:
            label:
              de: Termine
              en: Dates
              fr: Dates & Horaires
            type: structure
            min: 1
            sortBy: date desc
            columns:
              date:
                width: 1
            fields:
              date:
                label:
                  de: Startdatum
                  en: Start date
                  fr: Date de début
                type: date
                time: true
                width: 2/3
                default: now
                required: true
              endTime:
                label:
                  de: Endde
                  en: Ende
                  fr: Fin
                type: time
                width: 1/3
```

## Your setup
**Kirby Version**  4.0-alpha.6
