### ISSUE TITLE
[v4] Custom marks always receive latest editor instance (not their own editor)

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5456]
## Description
[See Video](https://cdn.discordapp.com/attachments/1111220342522904706/1136298520274542672/CleanShot_2023-08-02_at_16.04.07.mp4)

This uses a custom mark (not tested with others) inside a Writer field, that's inside a group field which is used in a block fieldset. All fields have the same name and the same settings.
```js
window.panel.plugin("sew-morlaix/extended", {
  writerMarks: {
    highlight: {
      get button() {
        return {
          icon: "palette",
          label: window.panel.$t("accent-color")
        }
      },

      commands() {
        return () => this.toggle()
      },

      get name() {
        return "highlight"
      },

      get schema() {
        return {
          parseDOM: [{ tag: "mark" }],
          toDOM: () => ["mark", 0]
        }
      }
    }
  }
})
```

## Your setup
**Kirby Version**  4.0.0-alpha.6

**Comment by distantnative** [comment]
@tobimori could you please provide the blueprint too. my head already starts hurting trying to parse the hierarchy of nesting there 🤣

**Comment by tobimori** [comment]
> @tobimori could you please provide the blueprint too. my head already starts hurting trying to parse the hierarchy of nesting there 🤣

It's a bit complex to share (because a lot of different block types) - broken down it looks like this:

- Layout field (Single column only)
  - Fieldset A w/ Fields Preview
    - Group Heading + Toggle
      - Writer Field with Issue
    - Other Fields
  - Fieldset B w/ Fields Preview
    - Group Heading + Toggle
      - Writer Field with Issue
    - Other Fields
  - Fieldset C (etc)

**Comment by distantnative** [comment]
What does `Group Heading + Toggle` exactly refer to?

**Comment by tobimori** [comment]
> What does `Group Heading + Toggle` exactly refer to?

A `type: group;` fields snippet so I can include more than one field. I don’t think it's relevant but I included it just in case.

**Comment by distantnative** [comment]
Hmm, can't even get your custom mark to work. Trying to replicate this is really hard with this little info. Please provide the full plugin incl styling for the highlight mark and the blueprint.

**Comment by distantnative** [comment]
## Replication

Tobi shared the repo with me which helped me to create this minimal reproducible case:

#### Plugin

```php
<?php

use Kirby\Cms\App;
use Kirby\Sane\Html;

// Custom allowed tags so they don't get stripped out by the sanitizer
Html::$allowedTags['mark'] = true;

App::plugin('sew-morlaix/extended', []);
```

```js
window.panel.plugin("sew-morlaix/extended", {
	writerMarks: {
		highlight: {
			get button() {
				return {
					icon: "palette",
					label: window.panel.$t("accent-color"),
				};
			},

			commands() {
				return () => this.toggle();
			},

			get name() {
				return "highlight";
			},

			get schema() {
				return {
					parseDOM: [{ tag: "mark" }],
					toDOM: () => ["mark", 0],
				};
			},
		},
	},
});
```

```css
.ProseMirror mark {
	color: gold;
	background: none;
	font-weight: bold;
}
```

#### Blueprint

```yaml
layout:
  type: layout
  fieldsets:
    a:
      wysiwyg: true
      preview: fields
      fields:
        text:
          type: writer
          nodes: false
          marks:
            - highlight
    b:
      wysiwyg: true
      preview: fields
      fields:
        text:
          type: writer
          nodes: false
          marks:
            - highlight
```

#### Steps
1. Add one layout row
2. Add a block A
3. Try out highlight mark, works
4. Add a block B in the same layout row
5. Highlight mark functionality either broken or triggers change in block B when editing block A
