### ISSUE TITLE
[v4] link field with options leads to error t.currentType is undefined

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#5467]
```yml
media:
  label: Image or Video
  type: link
  options:
    - file
```

```yml
item:
  label: Menu Item
  type: link
  options:
    - page
    - anchor
```

All lead to:

![Screenshot 2023-08-07 at 20 22 39](https://github.com/getkirby/kirby/assets/60777/ed31bef5-b95e-4201-b18e-b838eff0d529)

Kirby Version: alpha.6
