### ISSUE TITLE
[v4] Year and month selector in date picker is white on white - Windows PC

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#5469]
## Description
The text of `<selects>` in the date picker is not visible because it's white on white (Chrome) or barely visible white on gray (Firefox). 

**Expected behavior**  
Change either the text color or the background of *this* `<select>` element. 

**Screenshots**  
Chrome:
<img width="224" alt="image" src="https://github.com/getkirby/kirby/assets/6684137/76961d33-88f4-407b-a6fa-feb44ad66324">

Firefox:
<img width="216" alt="image" src="https://github.com/getkirby/kirby/assets/6684137/ed642f9f-5d4c-4fd4-a72c-d9781e962614">

## To reproduce

1. Have a date field 
2. Turn on Windows, open Chrome
3. Login to panel 
4. Open the date field calendar widget, then the year select. 

## Your setup
**Kirby Version**  
4.0.0 alpha 6 (but I think it's any V4; V3 didn't have this problem)

**Your system**
 - Device: PC
 - OS: Windows
 - Browser: Chrome

**Additional context**  
On Windows, the `color` and `background` CSS properties for `<select>` elements are respected (on Mac they're probably not). 
The element in question inherits the color from the "white on black" calendar widget because of this rule:
```css
:where(input,button,textarea,select) {
    background: none;
    border: 0;
    color: inherit;
    font: inherit;
    line-height: inherit;
}
```

Setting also the `background` to `inherit` however does **not** work, because it would inherit the `background` of it's immediate parent (which is transparent and not black, because background isn't inherited by default).

I guess one approach could be to directly target them with something like:
```css
.k-dropdown-content select {
    background: var(--dropdown-color-bg);
    color: var(--dropdown-color-text);
}
```
Which gives me this result:
<img width="221" alt="image" src="https://github.com/getkirby/kirby/assets/6684137/90d1bb54-762e-4864-8993-35e076716bb6">
