### ISSUE TITLE
User role permissions: non editable field is editable with Safari/Chrome but works with Firefox?

### ISSUE THREAD

**Issue by nicolasbulb** [k-next/kirby#5474]
## Description
When you define user role permissions and for a specific user, you're now allowing any edits, it works well with FireFox but strangely, a field like "list" is still editable with Safari (16) ou Chrome (115) browser?

**Expected behavior**  
The field shouldn't be editable. 

**Screenshots**  
![SCR-20230809-nfno](https://github.com/getkirby/kirby/assets/2143471/2687e646-2107-4518-ae49-391445d0317f)

![SCR-20230809-ngaf](https://github.com/getkirby/kirby/assets/2143471/80df0c8f-60fa-4caa-840e-4358f2045f4d)

## To reproduce
Create a page with users permissions, and a specific one that can't edit but only read like so:
```yaml
permissions:
  access:
    account: false
    panel: true
    site: true
    languages: false
    system: false
    users: false
  files:
    *: false
    read: true
  languages: false
  pages:
    *: false
    read: true
  site:
    update: false
  user: false
  users: false
```

1. Create a field type: list
2. login with FireFox with the reader only user → it works as expected. The user can't edit anything. It's read only
3. login with either Safari or Chrome with the reader only user → the field is stangely still editable
4. if you're logged in with the admin, the specific page is telling you, the page has been unsaved. We don't want that.

## Your setup
**3.9.4**  

**Console output**  
None

**Your system (please complete the following information)**
 - Device: MacBookPro M1Max 16inches
 - OS: macOS Monterey 12.6.8
 - Browser: Chrome, Safari
 - Version: Safari 16 and Chrome 115
