### ISSUE TITLE
[v4] writerMarks don't work in Block with preview: text

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#5477]
## Description
When custom marks are used on a block with `preview: text`, clicking on the custom mark's button doesn't do anything. 
But when opening the same block in the "Edit drawer", the custom mark button works.

**Expected behavior**  
Custom marks should work in block which use `preview: text`

**Screenshots**  
![custommarks](https://github.com/getkirby/kirby/assets/6684137/0694a678-c8a8-4432-94f7-af4ac66a7fda)

## To reproduce

1. Recover the minimal setup from https://github.com/getkirby/kirby/issues/5456#issuecomment-1666442697
2. Change the blueprint to:
    ```yml
    layout:
      type: layout
      fieldsets:
        a:
          # wysiwyg: true # comment this
          preview: text # change this
          fields:
            text:
              type: writer
              nodes: false
              marks:
                - highlight
    ```
3. Try using the custom writer mark on the preview
4. Open the edit drawer and use it there

## Your setup
**Kirby Version**  
Kirby 4 alpha 6

**Console output**  
Nothing :(
The function I define in `commands()` is run, but `this.toggle()` doesn't seem to do anything visible. 

**Your system (please complete the following information)**
 - Device: Windows PC
 - OS: Windows 11
 - Browser: Chrome
 - Version: 115
