### ISSUE TITLE
[v4] Writer field: nodes selector doesn't show up when using toolbar option

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#5482]
## Description
When choosing to show only some nodes in the toolbar, by using the toolbar option in the blueprint for a writer field, the "node" selector button doesn't show up. 

**Expected behavior**  
Selector should be shown with the selected nodes. 

**Screenshots**  
<img width="225" alt="image" src="https://github.com/getkirby/kirby/assets/6684137/1294c4ce-f951-41a6-b8b6-8acb12406ec9">

## To reproduce

1. Use this blueprint:
```yml
fields:
  writer:
    nodes:
      - paragraph
      - orderedList
      - bulletList
    toolbar:
      nodes:
        - paragraph
        - bulletList
```
2. Go into panel and trigger the toolbar to show up
3. Nodes selector is missing

## Your setup
**Kirby Version**  
4.0.0.alpha-6

**Console output**  
*Nothing*

**Your system**
 - Device: PC
 - OS: Windows 11
 - Browser: Chrome
 - Version: 115
