### ISSUE TITLE
[v4] Structure field: Titles in structure tables in multiple languages not working properly

### ISSUE THREAD

**Issue by dviate** [k-next/kirby#5483]
## Description
When working with columns to show the panel user the necessary date, you can use the `columns` to determine which structure items are initially visible. That's a great option, but the titles of the columns don't seem to accept multiple languages **when you're trying to display a structure table inside a structure table**; the lines below don't give the expected outcome:

```
label:
    nl: Menuitems
    en: Menu items

type: structure

columns:
    dish:
        width: 5/6
        label:
            nl: Gerecht
            en: Dish
    price:
        width: 1/6
        label:
            nl: Prijs
            en: Price
        before: €
        align: right
```

... whereas this works, but doesn't give me the option to write in multiple languages:

**Expected behavior**  
To see the right label, not what's visible on the screenshot below.

```
label:
    nl: Menuitems
    en: Menu items

type: structure

columns:
    dish:
        width: 5/6
        label: Dish
    price:
        width: 1/6
        label: Price
        before: €
        align: right
```

**Screenshots**  
![image](https://github.com/getkirby/kirby/assets/2322938/0e375ad8-de01-4c01-a5f9-e162cace847f)

## Setup
4.0.0.alpha-6
