### ISSUE TITLE
[v4] Following a link in drawer does not close drawer

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#5497]
## Description
When you click a link in the drawer (like the preview button of a pages field), the drawer stays open. 

**Expected behavior**  
The drawer should close when the route changes

**Screenshots**  
![drawer-not-closing](https://github.com/getkirby/kirby/assets/6684137/744f4232-b992-4fb5-bdfb-811762478d98)

## To reproduce
1. Blueprint:
    ```yml
    fields:
      struct:
        type: structure
        label: Add item to open drawer
        fields:
          page:
            type: pages
            label: Select a page
            multiple: false
            help: ...then click on it
    ```
2. Open panel, add a structure item, select a page
3. Click on the page preview button
4. The page loads, the drawer stays open

## Your setup
**Kirby Version**  
v4 alpha 7

Chrome 116
