### ISSUE TITLE
[v4] Writer Toolbar in Block Drawer jumps down on focus.

### ISSUE THREAD

**Issue by ovenum** [k-next/kirby#5501]
## Description
The new Writer _non-inline-toolbar_ jumps down when the writer field, rendered inside the a BlockFormDrawer, recieves focus.

**Expected behavior**  
The Toolbar to be aligned with the top of the field when the field is focused.

**Screenshots**  
<img width="826" alt="image" src="https://github.com/getkirby/kirby/assets/47149622/af1a053b-e09a-4e8a-919b-a8654308ff1a">

## To reproduce
Create a blocks field with the blueprint below and edit the field in the BlockFromDrawer (?)
```yaml
type: blocks
fieldsets:
  text:
    name: field.blocks.text.name
    icon: text
    wysiwyg: true
    preview: text
    fields:
      text:
        type: writer
        label: Text
        headings:
          - 2
          - 3
        toolbar:
          inline: false 
```

## Your setup
**Kirby Version**  
4.0.0-alpha.7

**Your system (please complete the following information)**
 - Browser: macOS Chrome 116.0.5845.110
