### ISSUE TITLE
[v4] New sticky Writer Toolbar in Block Text preview inconsistent with Writer Field

### ISSUE THREAD

**Issue by ovenum** [k-next/kirby#5502]
## Description
The new _sticky_ Writer Toolbar behaves differently when rendered within the WriterField component or within a Block Text preview component. 

**Expected behavior**  
The TextPreview Toolbar position, size and spacing to be more consistent with the Writer Field toolbar.
- More spacing between the toolbar and field content.
- The Toolbar to extent across the available horizontal space. Like it does in the Field. 

**Screenshots**  
<img width="795" alt="image" src="https://github.com/getkirby/kirby/assets/47149622/9358fa99-6c29-4d9e-9444-edb6e7c2ee09">
WriterField Toolbar with good spacing to the fields text content and stretching across horizontally.

<img width="777" alt="image" src="https://github.com/getkirby/kirby/assets/47149622/630873aa-1bbe-4e04-98ee-51e60a6cd317">

Toolbar rendered inside TextPreview component has not enough spacing to text content and does not fill the available horizontal space, which looks odd.

## To reproduce
Create a blocks field with the blueprint below and add a new Text Block with some content.
```yaml
type: blocks
fieldsets:
  text:
    name: field.blocks.text.name
    icon: text
    wysiwyg: true
    preview: text
    fields:
      text:
        type: writer
        label: Text
        headings:
          - 2
          - 3
        toolbar:
          inline: false 
```

## Your setup
**Kirby Version**  
4.0.0-alpha.7
