### ISSUE TITLE
YAML inline comment breaks when conditions with empty strings

### ISSUE THREAD

**Issue by cstmth** [k-next/kirby#5503]
## Description
When you add a YAML inline comment on the same line of a when condition whose desired value is an empty string, there seems to be some parsing error and the condition does not work anymore (the corresponding field does not appear even though the option is selected).

**Expected behavior**  
The condition works as expected, irrelevant of whether an inline comment is placed on the line of its definition.

## To reproduce

1. Create a field that allows you to set when condition key value pairs (e.g. `radio`). Set one of the options keys to an empty string like so:

```yml
some_field:
  type: radio
  options:
    "": First option
    second_otpion: Second option
```

2. Create a second field that is told to only appear when the empty string option is selected:

```yml
other_field:
  type: text
  when:
    some_field: ""
```

This works as expected.

3. Place an inline comment on the line of the when condition:

```yml
other_field:
  type: text
  when:
    some_field: "" # this is an inline YAML comment
```

Now, `other_field` does not appear anymore even when `some_field: ""` is true.

## Your setup
3.9.61

**Console output**  
None

**Your system (please complete the following information)**
 - Device: Computer
 - OS: Windows 11 (Kirby runs on Ubuntu 20.04 Docker)
 - Browser: Chrome
 - Version: 116

**Additional context**  

The necessity of "" being an option is disputable. Nonetheless, it working only in certain conditions is undesirable.
