### ISSUE TITLE
Uploader creates images with wrong extension if format is converted

### ISSUE THREAD

**Issue by marcojakob** [k-next/kirby#5530]
I'm using the new [Uploader](https://getkirby.com/releases/4.0/uploader#optimize-files-on-upload). When I tell it to convert images to another format, the resulting file extension is wrong.

This is my file blueprint:

```
accept:
  type: image

create:
  width: 500
  height: 500
  format: "webp"
```

Now if I upload an `image.jpg` it is converted to the **webp** format but the filename in the content folder stays `image.jpg`. 

I think it should be `image.webp` instead.

## Your setup
**Kirby Version**  
4.0.0-alpha.7
