### ISSUE TITLE
Files field: preview url stored in localStorage incorrect after replacing file in section

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5566]
https://github.com/getkirby/kirby/assets/3393422/89384fbc-56e8-40e5-9a21-c8a97a09c65a

> abb-76x.jpg:1     GET /media/pages/photography/test/2335848fdf-1693746160/abb-76x.jpg 404 (Not Found)

Kirby 3.9.6

**Comment by distantnative** [comment]
@afbora this is a files field or section?

**Comment by afbora** [comment]
This is album blueprint of starterkit:

````yaml
columns:
  - width: 1/3
    # The first column contains a set of fields to store
    # information about the album.
    #
    # List of all available field types:
    # https://getkirby.com/docs/reference/panel/fields
    fields:
      # If you need the same field in multiple locations, you can define them once and reuse whereever needed.
      # Here we use a files field defined in `/site/blueprints/field/cover.yml`
      cover: fields/cover
      headline:
        type: text
        placeholder: "{{ page.title }}"
        help: Leave empty to use the title as headline
      subheadline:
        type: text
      text:
        type: writer
      tags: true

  - width: 2/3
    sections:
      # The `images` files section shows all images of
      # the current page that use the `image` template
      images:
        type: files
        layout: cards
        template: image
        info: "{{ file.dimensions }}"
        image:
          ratio: 5/4
          cover: true
        min: 1
        size: small
````
