### ISSUE TITLE
[v4] Nested blocks: Selecting and merging multiple blocks not possible

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [k-next/kirby#5626]
## Description
Splitting blocks inside a nested blocks field works. But I can’t select multiple blocks by holding down CMD and clicking. So merging blocks is not possible.

https://github.com/getkirby/kirby/assets/77532479/843dea0a-ca77-4a27-9e1f-91300fc0ad28

We use nested blocks to build modular pages. For example, the top level blocks are `hero`, `article` and `feature`. Inside the `hero` is an image field and a blocks field with fieldsets for headline, subline and button. Inside the `article` is blocks field with headline, text, quote, ... and so on.

## Your setup
v4-beta.1

Edit: Browsers tested: Chrome, Safari, Firefox on **macOS**

**Comment by afbora** [comment]
I think you can't select multiple blocks even standart (not nested) blocks field, right?

**Comment by SebastianEberlein-JUNO** [comment]
You can select multiple blocks by clicking while holding CMD / CTRL. If the blocks have the same block type, the "Merge" button appears.

![Screenshot](https://github.com/getkirby/kirby/assets/77532479/509cdc53-64db-44fc-b911-32275a4869bc)

**Comment by afbora** [comment]
Weird! I can't select multiple blocks for any blocks field (Windows 10 & Chrome 116)

**Comment by SebastianEberlein-JUNO** [comment]
I only tested Chrome, Safari, Firefox on macOS. But when I use https://saucelabs.com/products/cross-browser-testing to test Chrome on Windows 10, I also can’t select multiple blocks in a regular (not-nested) blocks field.

**Comment by distantnative** [comment]
It would be super helpful if you could add blueprint examples to reproduce it. Especially with all the nested block/structure etc. topics, it pushes the barrier for debugging a lot higher when one first have to reconstruct the setups from screenshots etc. thanks 🙏 :)

**Comment by SebastianEberlein-JUNO** [comment]
Sure, here is a simple blueprint that can reproduce the issue in the Plainkit:

`site/blueprints/pages/default.yml`
```yml
title: Default Page
fields:
  blocks:
    type: blocks
    label: Blocks
    fieldsets:
      article:
        name: Article
        preview: fields
        wysiwyg: true
        fields:
          nestedBlocks:
            type: blocks
            label: Nested Blocks
            fieldsets:
              - text
```
