### ISSUE TITLE
[v4] files section overflows grid

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#5633]
## Description
The files section in cards layout, when put in anything that's smaller than a 1/3 column (1/4, 11/5, 1/6, etc), overflows its columns in certain widths (e.g. vertical iPad: 768px). 
<img width="259" alt="image" src="https://github.com/getkirby/kirby/assets/6684137/fb2f91bb-1d60-4224-b9ac-85b615248d01">
Screenshot shows a files section in a 1/4 column, alongside a 3/4 column. The files section overflows its assigned 3 columns of 12. 

**Expected behavior**  
<img width="209" alt="image" src="https://github.com/getkirby/kirby/assets/6684137/d794a89d-7047-4d48-a603-4b6fce42603c">
The files section should stay in the assigned space. Or the grid should wrap earlier. 

## To reproduce
```yml
columns:
  left:
    width: 1/4
    sections:
      pic:
        type: files
        label: Picture
        layout: cards
  right:
    width: 3/4
    fields:
      name:
        label: Name
        type: text
      surname:
        label: Surname
        type: text
```

## Your setup
**Kirby Version**  
4.0.0 beta 1

**Your system (please complete the following information)**
 - Device: PC
 - OS: Win 11
 - Browser: Chrome 
 - Version: 117

**Additional context**  
```css
.k-items[data-layout=cards] {
    display: grid;
    gap: 1.5rem;
    grid-template-columns: repeat(auto-fill,minmax(var(--items-size,12rem),1fr));
}
```
This rule gives the columns in a cards layout a minimum absolute column width which is larger than the 3/12 of the parent columns.  

I guess one approach could be something like this:
```css
/* sadly no support for: max-width: var(--items-size,12rem) */
@container (max-width: 12rem) {
  .k-items[data-layout=cards] {
      grid-template-columns: 1fr;
  }
}
```
Maybe the same can be done with a single `grid-template-columns` property, but I wouldn't know how..
