### ISSUE TITLE
[v4] Sticky column doesn't stop at end of column

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5664]
## Description
![CleanShot 2023-09-19 at 12 17 26@2x](https://github.com/getkirby/kirby/assets/29142128/5806a1a0-f7ec-4fad-8135-f815307dbe4d)

```
    columns:
      - width: 1/4
        sticky: true
        fields:
          tagsHeadline:
            label: blabla
            type: headline
      - width: 3/4
        fields:
			[...]
      - width: 1 # here the column should stop being sticky
        fields:
          line1:
            type: line
      - width: 1/4
        fields:
          contentHeadline:
            label: blabla2
            type: headline
      - width: 3/4
        fields:
			[...]
```

## Your setup
**Kirby Version**  v4.0-beta.1
