### ISSUE TITLE
[v4] Blueprint Field width not respected inside 1/2 width Columns

### ISSUE THREAD

**Issue by rottstegge** [k-next/kirby#5665]
## Description
I'm having an issue in setting fields to a specific width inside a blueprint. For fields inside a narrow column (`1/2` or `1/3`) it seems like Kirby does not respect the field `width` set inside the blueprint. This might well be expected behavior to prevent cluttered layouts or too narrow fields (especially on mobile), but in my case and especially with the amount of horizontal space that Kirby 4 offers it seems unintuitive.

In its current form this prevents some field layouts that would work well visually.  If it can't be changed, this behavior should be mentioned in the docs.

**Expected behavior**  
A Field set to `width: 1/3` or `width: 1/4` should take up that amount of space in relation to its parent column.

```
title: Blueprint-Title

columns:
  left:
    width: 1/2
    sections:
      leftcolumn_fields:
        type: fields
        fields:
          field_a:
            type: text
            label: Hello Text
            width: 1/2           <- will be ignored

  right:
    width: 1/2
    sections:
      rightcolumn_fields:
        type: fields
        fields:
          field_b:
            type: toggle
            label: Hello Toggle
            width: 1/3          <- will be ignored

  wide:
    width: 1/1
    sections:
      widecolumn_fields:
        type: fields
        fields:
          field_c:
            type: date
            label: Hello Date
            width: 1/3          <- will be respected but becomes extremely small on Kirby 4
```

**Screenshots**  
<img width="1440" alt="image" src="https://github.com/getkirby/kirby/assets/25906628/76423883-19d3-4750-8f8f-b5610c24974a">

## To reproduce

1. Set up a page blueprint containing a column set to `width: 1/2` , `width: 1/3` or `width: 1/4`
2. Inside that column, add a field width width of `1/2`, `1/3` or `1/4`

The field will only start to respect its given width once its parent column is wider than `1/2`. There seem to be some additional issues with Kirby 4, where the last Field in my example code becomes extremely small, once the screen size gets larger.

## Your setup
**Kirby Version**  
Kirby 4 beta 1

**Your system (please complete the following information)**
 - Device: Macbook Pro 13'
 - Browser: Chrome
 - Version: 116

**Additional context**
