### ISSUE TITLE
[v4] Panel - multiple custom blocks with preview:fields collapse issue

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#5669]
## Description
When you have multiple custom blocks in a blocks field, which all use `preview: fields`, and you collapse one of them and then refresh, all blocks are collapsed. If you then open one block, refresh, all blocks are opened. 

**Expected behavior**  
Only the collapsed block should stay collapsed when reloading the page. 

## To reproduce

1. Blueprint:
```yml
fields:
  blocks:
    fieldsets:
      one:
        preview: fields
        wysiwyg: true
        fields:
          foo:
            type: text
      two:
        preview: fields
        wysiwyg: true
        fields:
          bar:
            type: text
```
2. Go to the page in the panel
3. Create 2 blocks
4. Collapse 1 of them
5. Refresh
6. notice both blocks have been collapsed

## Your setup
**Kirby Version**  4.0.0.beta-1

**Additional context**  
The status of the collapsed blocks is saved in session storage, the key for this state however is the same for all blocks of a single blocks field. See: 

https://github.com/getkirby/kirby/blob/4.0.0-beta.1/panel/src/components/Forms/Blocks/Types/Fields.vue#L62
```js
		state(collapsed) {
			const id = `kirby.fieldsBlock.${this.endpoints.field}`;

			if (collapsed !== undefined) {
				sessionStorage.setItem(id, collapsed);
			} else {
				return JSON.parse(sessionStorage.getItem(id));
			}
		},
```

`this.endpoints.field` here seems to be `/pages/<page-id>/fields/<field-name>`, or in the example above `/pages/home/fields/blocks`.
I guess something more unique to the actual block would be useful. Idk if the uuid of the block is accessible from a field preview... if not, it might be useful to pass that down to it. 

Otherwise you could access it via dom: `this.$el.closest('[data-id]')?.dataset.id`...
