### ISSUE TITLE
Blocks in structure crushes if text context have line break in the Panel

### ISSUE THREAD

**Issue by iigen** [k-next/kirby#5690]
## Description
If you add a line break to text input in a block in the structure, all blocks of this element in the structure will be damaged when page saving.
To be sure this is not affect of some plugin, I made a clean install of Kirby plainkit (https://github.com/getkirby/plainkit) with the last Kirby version. When I tested it, I noticed this is happens when input field contains line break "\n". 
Seems it's working with "text" block type, but I working on custom block type and behavior is absolutely the same as for default "markdown" block type.

**Video**  
https://github.com/getkirby/kirby/assets/17764993/74c1fac2-ef2e-455e-b9e1-fa7d70efdfe3

**Blueprint (home.yml)** 
```
title: Homepage

columns:
  main:
    width: 1
    sections:
      fields:
        type: fields
        fields:
          block_group:
            label: Block groups
            type: structure
            fields:
              blocks:
                label: Blocks
                type: blocks
                fieldsets:
                  - markdown
```

## To reproduce

1. Please use the blueprint above
2. Add some blocks in that structure (with inline text) and save it
3. Add the linebreak to one of blocks and save it
4. Press browser "refresh page" / F5

## Setup
**Kirby Version**  
3.9.6.1

**Console output**  
No any output

**Your system**
 - Device: Laptop
 - OS: Win 11
 - Browser: Chrome
 - Version: 

Thanks!
