### ISSUE TITLE
[v4] Heading block: `toolbar` option for text writer field ignored

### ISSUE THREAD

**Issue by lukaskleinschmidt** [k-next/kirby#5703]
## Description
I found some issues using the `writer` field marks.

```yml
# config A

text:
  label: Text
  type: writer
  inline: true # Does not change anything here
  marks:
    - italic
    - underline
    - strike
  toolbar:
    marks:
      - italic
      - underline
      - strike
      - "|"
      - clear

```
**Actual result (Config A)**

![grafik](https://github.com/getkirby/kirby/assets/10027897/38db67cc-75be-4a47-8244-ee8742bca644)

**Expected result (Config B)**

![grafik](https://github.com/getkirby/kirby/assets/10027897/b6dd5824-6edb-4983-a1f5-d9f6a2c7efe1)

I can get the expected result by using the following config:
```yml
# config B

text:
  label: Text
  type: writer
  inline: true
  marks:
    - italic
    - underline
    - strike
    - "|"
    - clear

```

As far as I can tell from the source code and [current informations](https://getkirby.com/releases/4.0/writer-field-improvements) available the first config (config A) should actually work?

----

### Using it in a Block
For this I used a updated `heading` block.
```yml
  …
  text:
    label: field.blocks.heading.text
    type: writer
    inline: true
    placeholder: field.blocks.heading.placeholder
    marks:
      - italic
      - underline
      - strike
      # - "|"
      # - clear
    toolbar:
      marks:
        - italic
        - underline
        - strike
        - "|"
        - clear

```

Similar behaviour but on top of this the order of the marks is also messed up.

**Config A**

![grafik](https://github.com/getkirby/kirby/assets/10027897/24e02da3-eb59-4338-8e78-22b026e207ae)

**Config B**

![grafik](https://github.com/getkirby/kirby/assets/10027897/e4d91acb-a480-45ad-be0f-e11452344a08)

## Your setup
**Kirby Version**  
`4.0.0-beta.1`

Sorry for the unaligned Screenshots 😅

**Comment by distantnative** [comment]
I am not 100% clear what you are trying to achieve.

```yml
  marks:
    - italic
    - underline
    - strike
  toolbar:
    marks:
      - italic
      - underline
      - strike
      - "|"
      - clear
 ```
 
 Reads as if you want to only enable 3 marks and no others, but then in the toolbar you actually want to list the `clear` mark that you don't want to enable though.
 
 Maybe you can give some more insight into what you are trying to achieve and what would be expected.

**Comment by lukaskleinschmidt** [comment]
I was under the impression the the top level `marks` are the actual marks that the field will accept/allow when for example you paste in some html. And the `toolbar.marks` are the ones you can use to define what is shown/available in the toolbar.

![grafik](https://github.com/getkirby/kirby/assets/10027897/7df9050f-3378-4176-8e74-f3891a27ac37)
https://getkirby.com/releases/4.0/writer-field-improvements

**Comment by distantnative** [comment]
Yes, but if you don't include clean in the top-level option (and thus it's not accepted/allowed), how should it work in the toolbar? You're basically trying to add a mark that you just excluded from being supported.

**Comment by lukaskleinschmidt** [comment]
The problem here specifically might be that `clear` is not a mark (HTML tag) in that sense as it just removes formatting. So I probably misunderstood the implementation.

**Comment by distantnative** [comment]
mark !== HTML tag, sometimes. clear is indeed a mark https://github.com/getkirby/kirby/blob/v4/develop/panel/src/components/Forms/Writer/Marks/Clear.js

If you exclude it from the top-level option, it does not get registered. When you then try to reference it in the toolbar option, Kirby cannot find it as it wasn't registered.

**Comment by lukaskleinschmidt** [comment]
Makes sense. Thanks for clearing that up. Just got a bit confused with the naming I guess 😅

**Comment by distantnative** [comment]
Regarding your using in block, that does work for me correctly or I am overlooking something

<img width="311" alt="Screenshot 2023-10-07 at 15 46 28" src="https://github.com/getkirby/kirby/assets/3788865/c9c1dc88-0102-48dd-9604-f582fde63abf">

```yml
type: blocks
fieldsets:
  heading:
    fields:
      text:
        label: field.blocks.heading.text
        type: writer
        inline: true
        placeholder: field.blocks.heading.placeholder
        marks:
          - italic
          - underline
          - strike
          - clear
        toolbar:
          marks:
            - italic
            - underline
            - strike
            - "|"
            - clear
```

**Comment by lukaskleinschmidt** [comment]
Yes, seems to be fixed in `4.0.0-beta.2`. Although one thing I just saw (`4.0.0-beta.2`).
I looks like I get a double border when only including the `clear` mark. I think it is the same in your screenshot as well.

![grafik](https://github.com/getkirby/kirby/assets/10027897/33bb0267-9382-4292-85b0-110d36898948)

If I put the `link` mark back in the borders look fine.

![grafik](https://github.com/getkirby/kirby/assets/10027897/37e0a086-8996-420d-857d-93af08c581f5)

## Edit
In addition to that I somehow can't disable the `link` (or `clear`) mark in the toolbar. Please forgive me if this looks like nit-picking. It's just that I get a lot of (at least for me) unexpected behaviour. Maybe it is just something I would need to wait for a more detailed documentation.
```yml
# Results is the same output as shown in the second screenshot.
# I expected the result to be like the first screenshot.
text:
  label: field.blocks.heading.text
  type: writer
  inline: true
  placeholder: field.blocks.heading.placeholder
  marks:
    - italic
    - underline
    - strike
    - link
    - clear
  toolbar:
    marks:
      - italic
      - underline
      - strike
      - "|"
      - clear
```

## Edit 2
It seems to be related to the `wysiwyg: true` mode when editing blocks inline. Will try to investigate to see if this is actually a bug…
