### ISSUE TITLE
Tags field should hide "Add" button when disabled

### ISSUE THREAD

**Issue by chinochano** [k-next/kirby#5723]
## Description
The tags field has the ability to query tags from other fields or pages and allow the user to select from those values. When adding tags on the fly is disabled, the Add button doesn't disappear which is confusing.

**Expected behavior**  
When using the tags field with `accept: options`, the "Add" button and also the "Create" button should disappear.

**Screenshots**  
![Screenshot 2023-10-03 at 11 06 15](https://github.com/getkirby/kirby/assets/23634681/e6f9494c-efa0-4216-9c5a-cf18df45ae81)
![Screenshot 2023-10-03 at 11 15 48](https://github.com/getkirby/kirby/assets/23634681/4a3fe6e3-eeb1-4c7a-9d84-5da812bd378b)

Add a tag field using this code:

````yaml
years:
  type: tags
  accept: options
  options: query
    type: query
    query: page('people').yeartags.split # replace for a working query
````

## Your setup
Kirby 4 Beta 1

**Comment by afbora** [comment]
I can't reproduce the issue on beta.2 with following setup:

````yaml
tags:
  type: tags
  accept: options
  options: query
  query:
    fetch: site.tags.split
````
