### ISSUE TITLE
Select field ignores 'default' parameter when it's multilingual

### ISSUE THREAD

**Issue by dviate** [k-next/kirby#5725]
## Description
When using a multilingual setup and the options inside a `select`-field are multilingual too, the `default` parameter is being ignored. See example below, whereas [the sample code from this link](https://getkirby.com/docs/reference/panel/fields/select#default-value) works perfect but it's not [a multilingual example](https://getkirby.com/docs/reference/panel/fields/select#translating-options).

```
demo:
    label:
        nl: Hallo?
        en: Hello?
    type: select
    options:
        yessir:
            nl: Ja
            en: Yes
        ohhellno:
            nl: Nee
            en: No
    default: ohhellno
    required: false
```

## Your setup
**Kirby Version**  
4.0.0-beta.2

**Console output**  

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: macOS Sonoma
 - Browser: Microsoft Edge
 - Version: 117.0.2045.47 (Official build) (arm64)

**Comment by distantnative** [comment]
@dviate have you tested whether this is new to v4 or also exists in v3?

**Comment by dviate** [comment]
@distantnative I did a test on the latest v3 release and I have the same issue. So yes, it's not related to v4.

**Comment by afbora** [comment]
@dviate Could you test it like following (with double quoted labels)?

````yaml
  test:
    label:
        nl: "Hallo?"
        en: "Hello?"
    type: select
    options:
        yessir:
            nl: "Ja"
            en: "Yes"
        ohhellno:
            nl: "Nee"
            en: "No"
    default: ohhellno
    required: false
````

I guess, this issue is related with `yes` and `no` strings as options.
