### ISSUE TITLE
[v4] Selecting spesific custom `writerMarks` doesn't work

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5731]
I'm not sure this is a bug or I'm missing some setup. Selecting spesific custom `writerMarks` doesn't work for writer field.

### Plugin

````js
panel.plugin("my/writer-mark", {
  writerMarks: {
    smile: {
      get button() {
        return {
          icon: "smile",
          label: "Smile"
        }
      }
    }
  }
});
````

### Blueprint
````yaml
fields:
  writer:
    type: writer
    marks:
      - bold
      - smile
    toolbar:
      inline: false
      marks:
        - bold
        - smile
````

### Result
![screen-capture-1691-Test - Mægazine-localhost](https://github.com/getkirby/kirby/assets/3393422/b46107fb-b50f-4242-b035-6ab611791fe0)

## Additional Context

I can see the button when `marks: true`

````yaml
fields:
  writer:
    type: writer
    marks: true
    toolbar:
      inline: false
````

![screen-capture-1692-Test - Mægazine-localhost](https://github.com/getkirby/kirby/assets/3393422/3218808b-86e7-4804-a2b3-895a63b465ac)

Kirby 4.0.0-beta.2
