### ISSUE TITLE
[v4] Writer field: non-paragraph node isn't recognised in the dropdown

### ISSUE THREAD

**Issue by philipmarnef** [k-next/kirby#5751]
When I turn a line into an unordered list with the toolbar dropdown, it's marked as Paragraph in the toolbar and I can't revert it or set it to something else. This is also true if I omit the nodes option in the blueprint below.

This is not how it behaved in v3 where it was marked as unordered list and you could revert it to a paragraph in the dropdown.

**Screenshots**  
<img width="657" alt="Screenshot 2023-10-07 at 18 20 33" src="https://github.com/getkirby/kirby/assets/1675017/8067a328-9288-4fab-baf0-cb8771cc2078">
<img width="661" alt="Screenshot 2023-10-07 at 18 20 43" src="https://github.com/getkirby/kirby/assets/1675017/43ef27e4-6583-4d3f-b454-021ef24b3259">

**Yaml**
```
type: writer
label:
  nl: Tekst
  en: Text
  fr: Texte
nodes:
  - paragraph
  - bulletList
toolbar:
  inline: false
  marks:
    - bold
    - italic
    - "|"
    - link
    - email
    - "|"
    - clear
```

Tested in **Kirby 4.0.0-beta.2**
Chrome Version 117.0.5938.132 (Official Build) (arm64)
