### ISSUE TITLE
Bubbles field preview always splits on commas

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#5800]
## Description
When the "text" of a select field is shown as preview in a structure field, that preview text is split up on commas. 

**Expected behavior**  
The preview of a select field should never be split 

**Screenshots**  
<img width="158" alt="image" src="https://github.com/getkirby/kirby/assets/6684137/ca8e8f34-8687-4a88-bddd-417bafaf59eb">
This is showing the text "Netherlands, Kingdom of the" which is a single value, but is represented as 2. 

## To reproduce

1. Blueprint:
```yml
fields:
  structure:
    fields:
      select:
        options:
          "Netherlands, Kingdom of the": "Netherlands, Kingdom of the"
```
2. Create an entry and select `Netherlands, Kingdom of`
3. Close the drawer
4. See the preview

## Your setup
**Kirby Version** 
4.0.0 beta.2

**Comment by distantnative** [comment]
Sure this isn't even a v3 issue?

**Comment by rasteiner** [comment]
> Sure this isn't even a v3 issue?

nope, haven't tested it in v3. It for sure is *also* a v4 issue

**Comment by rasteiner** [comment]
Edited the repro steps, as there is a different issue interfering....

```yml
options:
  type: query
  query: site.countries
```

site.countries returns an associative array like:

```php 
[
  'NL' => 'Netherlands, Kingdom of the'
]
```
But the select actually saves the value, and not the key, in the content file.

So the simplified reproduction would be:

```yml
fields:
  structure:
    fields:
      select:
        options:
          "Netherlands, Kingdom of the": "Netherlands, Kingdom of the"
```
