### ISSUE TITLE
[v4] Role description has the wrong language

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5819]
## Description
![CleanShot 2023-10-19 at 00 07 26@2x](https://github.com/getkirby/kirby/assets/29142128/0ea89fe0-2055-4614-915f-fd9821d1876e)

```yaml
title: Editor
description:
  de: Hat ausschließlich Rechte für das Anlegen & Bearbeiten von Vierbeinern.
  en: Has rights to create & edit animals only.
 ```

My account is German:
![CleanShot 2023-10-19 at 00 08 19@2x](https://github.com/getkirby/kirby/assets/29142128/7c080435-1036-4ea2-8941-8d8c6ec8dbf4)

## Your setup
**Kirby Version**  v4.0-beta.2
