### ISSUE TITLE
[v4] Color field inside block stops structure field from saving content

### ISSUE THREAD

**Issue by blaaaaaaam** [k-next/kirby#5835]
## Description
I've created a custom block type that contains a structure field and a color field using the new Kirby4 color field.
When I first create the custom block (either in a layout field or blocks field), I'm able to create new entries in the structure and save the contents. When I go back into the block to make changes, the content doesn't save.

**Screenshots**  
Here's a quick screen recording. You can see that when I click the save button it immediately reverts back to the old value.

![Kirby4-ColorStructure-Bug](https://github.com/getkirby/kirby/assets/5779080/d56def06-d8ed-436c-8eee-03bfd380442f)

## To reproduce
Here is the custom block type code. The structure field works fine when I tested without the colour field:
```
name: Custom
tabs:
  main:
    fields:
      structure:
        type: structure
        fields:
          text:
            type: text
      colour:
        type: color
```

## Your setup
**Kirby Version**  
4.0.0 beta 2
