### ISSUE TITLE
[v4] Toggles input: focus background glitch

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#5843]
https://github.com/getkirby/kirby/assets/3788865/ddf377ae-6d45-409a-8bab-b383ef535067

Source is this CSS - not sure what was really intended her @bastianallgeier 

```css
.k-toggles-input input:focus:not(:checked) + label {
	background: var(--color-gray-200);
}
```

- Should be different color than normal background
- Should it be changing the background color and not focus outline?
- Probably needs to use `:focus-within` or so
