### ISSUE TITLE
[v4] Image card size doesn't working correctly in drawer

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5849]
## Description

Image card size doesn't working correctly in drawer due to `@container` queries.

````yaml
fields:
  blocks:
    type: blocks
    fieldsets:
      test:
        name: Test
        icon: image
        fields:
          image:
            label: Image
            type: files
            layout: cards
            size: huge
````

**Screenshots**  

![image (8)](https://github.com/getkirby/kirby/assets/3393422/6cd376fd-6fdc-4373-a470-a11c2d6902a2)

Kirby Version
Beta.3 (v4/develop)

**Comment by afbora** [comment]
I realized that this issue not only for drawer:

````yaml
fields:
  logo:
    type: files
    label: "Logo"
    multiple: false
    query: page.images
    uploads: image
    layout: cards
    size: huge
    width: 1/2

  logoInverse:
    type: files
    label: "Logo inverse"
    multiple: false
    query: page.images
    uploads: image
    layout: cards
    size: huge
    width: 1/2
````

![screen-capture-1710-Test - Mægazine-localhost](https://github.com/getkirby/kirby/assets/3393422/c843afb2-fdd0-4388-9214-cb653b4f0263)
