### ISSUE TITLE
[v4] Image Blocks preview shows line in caption Writer toolbar even without nodes

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5851]
## Description
In the Image Blocks preview:
![CleanShot 2023-10-22 at 14 43 22@2x](https://github.com/getkirby/kirby/assets/29142128/bcdb8509-f489-4ed2-ac83-8a7154563f3e)

In the sidebar:
![CleanShot 2023-10-22 at 14 43 50@2x](https://github.com/getkirby/kirby/assets/29142128/d059fc22-ee66-4df5-9890-8d81a5540b3a)

Blueprint:
```yaml
name: field.blocks.image.name
icon: image
preview: image
wysiwyg: true

fields:
  location:
    type: hidden
    default: 'kirby'
  image:
    extends: fields/image
    layout: cards
    size: xl
  caption:
    label: field.blocks.image.caption
    extends: fields/writer
```

## Your setup
**Kirby Version**  4.0-beta.2
