### ISSUE TITLE
[v4] Can not remove/change Quote node in Writer field once it’s created

### ISSUE THREAD

**Issue by ovenum** [k-next/kirby#5867]
## Description

Once a Quote node is created via the WriterField toolbar, it is not possible to turn it into a paragraph or clear its format options with the clear button. 
The only way to remove it is to delete the text and then re-type it.

Also the Writer Field seems not to detect that a quote node is selected. When i select a paragraph, the node icon in the writer toolbar changes to the paragraph icon. This does not happen when i select a quote node. 

**Screenshots**  
![Screenshot 2023-10-24 at 10 30 05](https://github.com/getkirby/kirby/assets/47149622/b58231da-646d-42db-8d7e-c505707da64f)

**Expected behavior**  

The inverse from above : )

## To reproduce
```yaml
# Writer field blueprint with quote node enabled
type: writer
nodes:
  - paragraph
  - quote
toolbar:
  inline: false
```

Create a writer field
Insert some text with paragraphs.
Select one of these paragraphs and use the node selection menu from the toolbar to create a quote node.
Try to remove the quote node formating or try to turn it into a normal paragraph again.

## Your setup
**Kirby Version**  
4.0.0-beta.2
