### ISSUE TITLE
[v4] Blocks field: links can't be clicked in help text with preview and wysiwyg option

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5880]
## Description

````yaml
name: Test block
preview: fields
wysiwyg: true
fields:
  text:
    type: text
    help: >
        Try to <a href='https://getkirby.com/' target="_blank">Click here</a>.
````

## To reproduce

1. Create custom block with sample above blueprint
2. Add this block type to the field
3. Try to click to link in help text
4. See nothing happened

## Your setup
**Kirby Version**  
Beta.2
