### ISSUE TITLE
[V4] 3D Model upload not working anymore in Kirby 4

### ISSUE THREAD

**Issue by squareclouds** [k-next/kirby#5881]
Hello, i am trying to upload GLTF and GLB files in the panel, and unlike in Kirby 3, in V4 it is not working anymore. I think the panel is trying to test the MIME type, which sadly is still a complicated thing with 3D models (besides OBJ). GLTF and GLB are becoming quite standard for the web due to their file sizes. In the workflow for my clients I use model-viewer form Google and a couple of js libraries for model compression. This files are not getting accepted anymore. But it seems that regular programs like Blender etc export the same type of files, since those are not being accepted either, so I think it has to do with the file type itself, and not from where it came from.

models tested:
- my own that i compress form OBJ using js libraries and google model-viewer. here is model-viewer from google, GLTFs for test purposes can be generated here
https://modelviewer.dev (use editor to generate some test files, just select a model from the dropdown and export the scene: https://modelviewer.dev/editor/)
- models from turbo squid, which are produced in blender, etc.

This is the error I am getting while uploading.

```
Kirby\Filesystem\Mime::matches(): Argument #1 ($test) must be of type string, null given, called in /Users/santiagoduque/Documents/WEBPROJECTS/mamp/liebherr-signage/www/kirby/src/Filesystem/File.php on line 284

```
when I check the file in the command prompt, i get this (using the `file` command)
```

file 114139_BananeXYZ--COMP_\&_exp=1.gltf
114139_BananeXYZ--COMP_&_exp=1.gltf: JSON data

file 114139_BananeXYZ--NORM_\&_exp=1.glb
114139_BananeXYZ--NORM_&_exp=1.glb: glTF binary model, version 2, length 2254996 bytes

```

That was my first issue. the second one, maybe less important: I am trying to create different file sections. I have one for videos, one fir images, and one for other documents, meaning mainly PDFs and 3D models. in the blueprint for the "other documents" filtering by extension does not help. this is not working:

```
accept:
    extension: pdf, glb, gltf
```
I am not sure what the extension parameter does, but it would be nice to be able to filter somehow

I hope someone can help me a bit :) i would like to use kirby4 for this new project. I have another project from this year where i also use 3D models, so at some point I would maybe upgrade that installation as well and it would be great to have the support back. 3D showcasing is probably going to become more relevant in the future and I hope you guys can solve this issue soon :)

![Bildschirmfoto 2023-10-27 um 13 14 44](https://github.com/getkirby/kirby/assets/9073054/14741c3a-7e8a-43cf-935f-60625758332b)

## To reproduce
Try to upload any GLTF or GLB file

## Your setup
Kirby 4 Beta2
php 8.1 on localhost
php 8.2 on test server

**Comment by afbora** [comment]
Works for me:

````yaml
accept: 
    extension: pdf, glb, gltf
````

Doesn't work for me either:
````yaml
accept: 
    mime:
      - model/gltf+json
      - model/gltf-binary
````

> Kirby\Filesystem\Mime::matches(): Argument `#1` ($test) must be of type string, null given, called in \kirby\v4-develop\kirby\src\Filesystem\File.php on line 284

**Comment by squareclouds** [comment]
oh! are you on windows maybe? on mac, when i do 

```
accept: 
    extension: pdf, glb, gltf
```

i cannot even select the files, only pdf works.

![Bildschirmfoto 2023-10-27 um 13 55 06](https://github.com/getkirby/kirby/assets/9073054/7a33dc7f-3493-4700-b134-941e67c486cd)

by the way, this also happens when i completely remove `accept` so that no filtering takes place. thats why i wonder why it worked on your side when you include the extensions... i am uploading now to a server and going to test on windows

**Comment by squareclouds** [comment]
hmmm on windows

```
accept: 
    extension: pdf, glb, gltf
```
    
also shows me nothing to select in the finder O_o can you please elaborate how you tested this?

**Comment by afbora** [comment]
Yes, I can't see `.gltf` files in file browser but I can upload the file (via drag-drop) without any error with `extension` option.

**Comment by afbora** [comment]
I've also tested on v3. Same for me. I can't see `.gltf` files in file browser but I can upload* the file with extension option. I can't upload with mime (`model/gltf+json`) option. But works* with `application/json` mime for `.gltf` files.

\* _Via drag-drop or selecting `(*.*)` in files browser_

**Comment by squareclouds** [comment]
you are right! but i had to install a fresh starter kit. so with extension i can drag n drop the files and they upload. but using the mime type the errors are thrown. at least i know now that i have that work around: using extension and then drag n dropping, because the file explorers dont work.

in my actual project this does not work though.... deactivating all plugins now..

**Comment by afbora** [comment]
Did you try extending file types?

https://getkirby.com/docs/reference/plugins/extensions/file-types

**Comment by squareclouds** [comment]
ok, new discoveries:

now it works on my installation, but i have another problem, will get to it in a second. but first:

now it works like you described also for me. but if you remove `accept` althougether, for instance so that the models can be selected in the file browser, this new yet pretty similar error appears

![Bildschirmfoto 2023-10-27 um 15 09 39](https://github.com/getkirby/kirby/assets/9073054/8b7853a1-74cb-4215-be78-3297c43d4706)

so it seems i need to explicitly accept the extensions, and then at least it works per drag n drop.

-----

now though.... this only works in my project when the relevant blueprint (site or page) only has one section!! that is why in the starter kit it was working right away.

this works:

```
sections:
  # imgs:
  #   extends: sections/files-imgs
  # vids:
  #   extends: sections/files-vids
  files:
    extends: sections/files-docs
```

but if i uncomment the other sections, like it was the original plan, having 3, it does not work anymore and the error is thrown. the starter kit is behaving the same way. if i create a second files section that has `extension: pdf, glb, gltf` and the other has image only, somehow kirby is putting them together and not allowing the gltfs in neither of them. so if one section has restrictions for lets say only image and the second one only GLTF, then the error occurs even with drag n drop and `extension`. the images can be uploaded in their image-section without problems though. and the same the videos

**Comment by squareclouds** [comment]
ok got it working now. for videos and images i had the file-blueprints like this:


```
accept:
  mime: image/*
  type: image
  maxsize: 15000000 # 15mb
```


```
accept:
  mime: video/mp4
  type: video
  maxsize: 500000000 # 500mb

```


i removed `type` in both of them and now the "other documents" part works with pdf and gltf/glb (drag n drop only, but its still a huge win)

**Comment by squareclouds** [comment]
ok got it working now. for videos and images i had the file-blueprints like this:


```
accept:
  mime: image/*
  type: image
  maxsize: 15000000 # 15mb
```


```
accept:
  mime: video/mp4
  type: video
  maxsize: 500000000 # 500mb

```


i removed `type` in both of them and now the "other documents" part works with pdf and gltf/glb (drag n drop only, but its still a huge win).

i realised though, that using this in site and having a subpage holding the actual files that has the same sections creates the problem again.

**site.yml**
```
sections:
      imgs:
        extends: sections/files-imgs
        parent: site.find('main-library')
      vids:
        extends: sections/files-vids
        parent: site.find('main-library')
      docs:
        extends: sections/files-docs
        parent: site.find('main-library')
```

**medialibrary.yml // this is a page type that will hold all media. there will be only one of this type**
```
sections:
  imgs:
    extends: sections/files-imgs
  vids:
    extends: sections/files-vids
  docs:
    extends: sections/files-docs
```

but the easiest fix here is to leave the medialibrary.yml without sections. still strange though, unless i am doing something wrong
