### ISSUE TITLE
[v4] Writer nodes dropdown shown even if only 1 node dropdown entry

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5883]
## Description
![CleanShot 2023-10-29 at 12 30 46@2x](https://github.com/getkirby/kirby/assets/29142128/3d662b69-a3d9-42b1-a475-ae262166488b)
```yaml
              benefits:
                label:
                  de: Vorteile
                  en: Benefits
                type: list
                marks: false
                nodes:
                  - bulletList
```

With the following blueprint, the paragraph entry is shown in a node list even though it is not selectable and just used as a "hidden" node.

## Your setup
**Kirby Version**  v4-beta.2
