### ISSUE TITLE
[v4] Blocks field: can't multiple selection when focused parent

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5897]
### Reproduce steps:
- Prepare nested blocks with `preview: fields` and `wysiwyg: true` setup
- Focus parent block
- Try to select multiple blocks in focused block with

https://github.com/getkirby/kirby/assets/3393422/26430c8f-159a-4ed8-90df-51f7865a5d4d

````yaml
fields:
  blocks:
    type: blocks
    fieldsets:
      test:
        name: Test
        preview: fields
        wysiwyg: true
        fields:
          blocks:
            type: blocks
````

_Originally posted by @afbora in https://github.com/getkirby/kirby/issues/5884#issuecomment-1786652553_
