### ISSUE TITLE
Date field saving format issue in blueprint

### ISSUE THREAD

**Issue by ment4list** [k-next/kirby#5919]
With a blueprint like this:

```yaml
fields:
    releaseYear:
        min: "1800/01/01"
        max: "2022/01/01"
        type: date
        display: YYYY
        format: "Y"
```

#### Expectation
What I expect to see is only the year part of the date being saved.

#### Actual result
It saves correctly to the page's content file but when the page is re-opened in the panel, the date is not the saved year.

If format is simply changed to `Y` (without quotes), the digit `1` is stored in the content file.

If the format is `Ymd`, it works. It saves the year, month, and date.
