### ISSUE TITLE
[v4] beta 3: can't add items to a structure field that contains a gap field

### ISSUE THREAD

**Issue by vibellio** [k-next/kirby#5931]
## Description
the issue title tells all details needed.
i can't add any new items to an empty structure field. 
in beta 2 this wasn't a problem.

## Your setup
4.0.0-beta.3

**Your system (please complete the following information)**
 - Device: MacBook Pro M2 Pro (2023)
 - OS: macOS 14.1 
 - Browser: Chromium Engine 
 - Version: 118.0.5993.70

**Comment by distantnative** [comment]
> the issue title tells all details needed.

I am afraid this actually isn't the case. I cannot reproduce your issue so far.

Please share your blueprint of the structure field that isn't working for you, so maybe that'll let us reproduce your issue and tackle it. Thank you :)

**Comment by vibellio** [comment]
true!

i had a second look and the problem is the field `type: gap`

```
globalLabels:
  type: structure
  label: Globale Labels
  sortBy: labelslug asc
  width: 2/3
  fields:
    labelSlug:
      type: slug
      label: 'Label ID'
      width: 1/3
    gap001:
      type: gap
      width: 2/3
    labelContent:
      type: text
      label: 'Label Inhalt'
      width: 1/2
```

as soon as i delete any field with `type: gap`, everything works just as expected!
but without gaps, any of my current structure fields, would look really messy.
in beta 2 and all versions before and kirby v3 this wasn't a problem.
are u going to fix this, or could you imagine which change in beta 3 is causing this behaviour?!

thank u!
