### ISSUE TITLE
[v4] Sections and fields misalign in combined panel layouts

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#5935]
## Description
When combining sections and fields, sections get a large top margin while fields do not. This results in unbalanced layouts.

**Expected behavior**  
Fields and section should align nicely.

**Screenshots**  
<img width="1269" alt="grafik" src="https://github.com/getkirby/kirby/assets/25466/da09abc8-faa8-456f-b7e1-45a3de934ae3">

## To reproduce
Blueprint for the given example
```yml
title: Plugin
num: zero
columns:
  - width: 1/3
    sections:
      header1:
        type: fields
        fields:
          headline1:
            type: headline
            label: Beschreibung
          description:
            label: Beschreibung
            type: textarea
            size: tiny
          introduction:
            label: Einleitung
            type: textarea
            size: small
      cover:
        label: Titelbild
        type: files
        max: 1
        layout: cards
        size: huge
        image:
          ratio: 16/9
          cover: true
  - width: 1/3
    fields:
      headline2:
        type: headline
        label: Metaangaben
      category:
        label: Kategorie
        type: tags
      source:
        label: Quellplugin
        type: select
        options:
          type: query
          query: page.sources
          text: '{{ item.value }}'
          value: '{{ item.key }}'
      type:
        label: Typ
        type: select
        options:
          - MIT
          - Plus
      price:
        label: Preis
        type: number
        after: €
        when:
          type: Plus
      feature:
        label: Feature
        type: toggle
  - width: 1/3
    sections:
      header3:
        type: fields
        fields:
          headline3:
            type: headline
            label: Dokumentation
      docs:
        label: Dokumentation
        type: pages
        image: false
        templates:
          - documentation
          - textreference
      versions:
        label: Versionen
        type: pages
        image: false
        templates:
          - version
```

## Your setup
**Kirby Version**  
Kirby 4 beta 3 – not sure how Kirby 3 does this in comparison.
