### ISSUE TITLE
Multilanguage Page Content not shown in Panel

### ISSUE THREAD

**Issue by rottstegge** [k-next/kirby#5975]
## Description
In a multilanguage setup running the latest Kirby 4 RC, I'm facing an issue with some multilang content inside a structure field that I believe to be a bug. Currently, there are two languages enabled: English (default) and German. 
In my blueprint I set up a structure field that is translatable:

```
intro_popup_slides:
  label:
    en: Popup Slides
    de: Popup Slides
  min: 1
  max: 10
  type: structure
  translate: true
  required: true
  fields:
    slide_headline:
      label:
        en: Headline
        de: Überschrift
      type: text
      maxlength: 60
    slide_mainttext:
      label:
        en: Main Text
        de: Haupttext
      type: textarea
      required: true
      maxlength: 450
```

While the field works as expected when I enter english Content, there is an issue when entering german content: The field value gets saved and appears inside the content files as expected. As soon as I refresh the panel though, the English content of the field is shown despite the panels language toggle being set to German.  

**Expected behavior**  
Show german content when the panels language toggle is set to German

## Your setup
**Kirby Version**  
Kirby 4 Release Candidate
PHP 8.1

Edit: This issue was already present using Kirby 4 beta 2 und persisted through the update to RC1
