### ISSUE TITLE
Structure field: Double-escaping for placeholders in hardcoded option text

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#5995]
## Description

When using placeholders inside the text for hardcoded options for the select field, the placeholder results are escaped and therefore the options in the select dropdown are double-escaped.

**Expected behavior**  

The select field never renders HTML, so no escaping should be done. Both placeholder marks should result in proper rendering.

**Screenshots**  

<img width="562" alt="Screenshot of the double-escaping bug" src="https://github.com/getkirby/kirby/assets/1595007/e14a29c4-36ef-4b47-bfbd-70f351339047">

## To reproduce

```yaml
fields:
  select:
    type: select
    options:
      escaped: "{{ page.something.or('String with <> HTML chars') }}"
      unescaped: "{< page.something.or('String with <> HTML chars') >}"
```

## Your setup
**Kirby Version**  
3.8.4.2, 3.9.8, 4.0.0-rc.2

**Additional context**  

The `Option\Options` class is a special case in `Field\FieldOptions` as it doesn’t get the `$safeMode` flag passed in any way; the `NodeText` class always uses `toSafeString()` when generating the text string. We need to find a way to pass the `$safeMode` flag along.

Switching from `toSafeString()` to `toString()` would however be a breaking change as the `{< placeholder >}` syntax is not supported by `toString()`. This syntax may have been used as a workaround as it does not come with the double-escaping bug, so we shouldn't break it.

Suggestion: We could use something like this for the `toString()` case to support both (maybe even generally as it won't do harm, only extend the supported set of placeholder marks):

```php
Str::template($template, $data, [
  'start' => '{[<{]?',
  'end'   => '[>}]?}'
]);
```

**Separately calling `Str::template()` with the other start and end marks would introduce a code execution vulnerability, it needs to be done in one step.**
