### ISSUE TITLE
[v4] Strange behavior of the slug-field (bug, regression)

### ISSUE THREAD

**Issue by gbdesign2023** [k-next/kirby#6002]
## Description
In Kirby 4 RC3 I have noticed a strange behavior in a structure field with slug field. 
If I click on an entry, the slug entry disappears and additional the order of the list changes. 
In addition, a word in the slug field is no longer converted: the field remains empty. 

https://github.com/getkirby/kirby/assets/140849227/fc3412f7-3724-4ee8-89bf-1a4179973645

Here is a comparison to Kirby 4 RC2, where everything still works as usual:

https://github.com/getkirby/kirby/assets/140849227/1d3c6ab9-3ff3-47ce-abae-2b43427a8da3

And here is the excerpt on my blueprint:
```
columns:
  - width: 1/1
    sections:
    
      contentTags:
        type: fields
        fields:
        
          labelglobalTags:
            label: "Schlüsselwörter (Tags)"
            type: headline
        
          globalTags:
            label: Schlüsselwörter
            type: structure
            sortBy: identifier asc
            fields:
              tag:
                label: Schlüsselwort
                type: text
                width: 1/2
              identifier:
                label: konvertierte Version
                type: slug
                sync: tag
                width: 1/2
```
