### ISSUE TITLE
[v4] Wizard button breaks field header layout

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#6008]
## Description

Adding a wizard to the slug field breaks the field header layout:

![CleanShot 2023-11-27 at 13 02 35@2x](https://github.com/getkirby/kirby/assets/7975568/75d329c7-c02e-4975-a3aa-5f80c8c3fb57)

## To reproduce

1. Create a slug field, ideally besides any other field.
2. Add a wizard to the field.

```yml
fields:
  text:
    width: 1/2
  slug:
    width: 1/2
    wizard:
      text: Lorem ipsum
      field: text
```

## Your setup
**Kirby Version**  
4.0.0-rc.4

**Your system (please complete the following information)**
 - OS: macOS
 - Browser: Chrome 119.0.6045.123
