### ISSUE TITLE
[v4] field type text still uses old user icon

### ISSUE THREAD

**Issue by elyukai** [k-next/kirby#6014]
## Description

When I use the `user` icon for a `text` field, the old user icon is displayed, i.e. not the one shown in the reference online.

**Expected behavior**  
The outline icon should be used.

**Screenshots**  
<img width="386" alt="Bildschirmfoto 2023-11-28 um 15 08 27" src="https://github.com/getkirby/kirby/assets/11094577/5c714181-b509-4991-8ae8-606e13c60b22">

## To reproduce

```yaml
tabs:
  content:
    # ...
    columns:
      main:
        # ...
        fields:
          # ...
          projectHead:
            type: text
            label:
              en: Project Head
              de: Projektleitung
            required: true
            icon: user
```

## Your setup
**Kirby Version**  
4.0.0

**Console output**  
N/A

**Your system (please complete the following information)**
 - Device: MacBook Pro 16″ Late 2021
 - OS: macOS 14.1.1
 - Browser: Safari
 - Version: 17.1

**Additional context**  
N/A
