### ISSUE TITLE
Problem with the position of the <thead> in the item table in blocks

### ISSUE THREAD

**Issue by DiaoRod** [k-next/kirby#6016]
## Description

There seems to be a problem with the position of the `<thead>` in the item [table in blocks ](https://getkirby.com/docs/reference/panel/blocks/table).

Looks like the css var `--header-sticky-offset` cannot resolve because `--scroll-top` is not set.

**Screenshots**  
<img width="401" alt="Screenshot 2023-11-28 at 16 12 54" src="https://github.com/getkirby/kirby/assets/152313527/8c491c2f-bd54-49f6-adcf-fb4091d79a46">

<img width="948" alt="Screenshot 2023-11-28 at 16 22 05" src="https://github.com/getkirby/kirby/assets/152313527/0ef7c279-a61a-420c-b687-01cdf1b90800">

## To reproduce

1. Add fieldset table ...
```
type: blocks
label: Block
fieldsets:
  - table
```

2. Then add table  like `/site/blueprints/blocks/table.yml`

```
name: Simple 3-column menu table
icon: menu
preview: table
fields:
  rows:
    type: structure
    columns:
      dish:
        width: 1/4
      description:
        width: 1/4
      price:
        width: 1/2
        align: right
        after: "USD"
    fields:
      dish:
        type: writer
        marks: false
        inline: true
      description:
        type: text
      price:
        type: number
```

## Your setup
**Kirby Version**  
4.0.0

**System**
 - OS: macOS 13.5.1 
 - Browser: Chrome 118.0.5993.70, Firefox 120.0
