### ISSUE TITLE
[v4] Color field in structure inside a block breaks the modal.

### ISSUE THREAD

**Issue by vincentrouleau** [k-next/kirby#6017]
https://github.com/getkirby/kirby/assets/11572524/4ad73376-c7df-4a63-a8cb-2a908283c990

![image](https://github.com/getkirby/kirby/assets/11572524/4b604181-5d7a-43c9-8c04-dd6f99a792f1)

**Comment by vincentrouleau** [comment]
Let me add that this is in the fresh 4.0 release.

**Comment by distantnative** [comment]
@hotdoy would be great if you could add your blueprint as actual text here, thanks!

**Comment by vincentrouleau** [comment]
Of course! @distantnative 

```
name:  Router
icon: grid
fields:
  items:
    type: structure
    fields:
      picture:
        type: files
        multiple: false
      label:
        type: text
        width: 2/3
      color:
        type: color
        width: 1/3
        mode: options
        options:
        - "#fff"
        - "#000"
      target: 
        type: link
```

That's for the block. You tell me if you also need the page BP.
