### ISSUE TITLE
Html field preview expands vertical (not being truncated)

### ISSUE THREAD

**Issue by foxacid** [k-next/kirby#6026]
## Description

Structure field previews are usually truncated to save space. There's a regression in V4 causing list fields not to be truncated anymore. Instead all content is displayed.

![image](https://github.com/getkirby/kirby/assets/12812201/299911f5-d51e-4f19-95bc-96dada538a2e)

Blueprint:
```

formats:
  type: structure
  fields:
    image: fields/image
    name:
      type: text
    description:
      type: textarea
    features:
      type: list
    platforms:
      type: text
    preview:
      type: url
    details:
      type: pages
      max: 1
      query: site.childrenAndDrafts
```
