### ISSUE TITLE
New create dialog does not recognize fields when defined in fields section

### ISSUE THREAD

**Issue by bezin** [k-next/kirby#6040]
## Description

I have a custom page blueprint with

```
sections:
  fields:
    somefield:
      type: text
```

My create dialog config looks like this:

```
create:
  title: Some title
  fields:
    - somefield
```

I get the error `Unknown field "somefield" in create dialog`

Apparently the fields defined in the fields section [are not merged here](https://github.com/getkirby/kirby/blob/baa3ad7d2788fbacaf157e56b17874e5d803d098/src/Panel/PageCreateDialog.php#L135-L136)

**Expected behavior**  
The create dialog contains `somefield`

**Kirby Version**  
Kirby 4.0.0 with PHP 8.2

**Comment by distantnative** [comment]
Cannot reproduce the issue - the field appears in the dialog for me:

<img width="623" alt="Screenshot 2023-12-09 at 16 17 39" src="https://github.com/getkirby/kirby/assets/3788865/bc67ed54-62d3-4603-8cf5-37644014f639">

**Comment by texnixe** [comment]
I think you have a syntax issue, should be

```
sections:
  fields:
    fields:
      somefield:
        type: text
```
