### ISSUE TITLE
Color field missing ability to use queried options

### ISSUE THREAD

**Issue by HYR** [k-next/kirby#6053]
## Description
Received permission from Bastian to add this as an issue.

Trying to move from a 3rd-party color field to the new native field. Currently, we pull the list of default colors available from the config for each site. The problem is that the new Color field doesn't support query language for pulling in options.

### Expected behavior
Expected the ability to pull in a list of colors from the config to my reusable field.

#### Config
```php
    return [
        'customizable' => [
            'palette-options' => [
                'Sunny rays'       => '#F8B195',
                'First-love blush' => '#F67280',
                'Cherry blossom'   => '#C06C84',
                'Morning gloom'    => '#6C5B7B',
                'Midnight rain'    => '#355C7D'
            ]
        ]
    ]
```

#### Field (color-palette.yml)
```yaml
label: Color
type: color
options:
  type: query
  query: kirby.option('customizable.palette-options')
  key: "{{ arrayItem.key }}"
  value: "{{ arrayItem.value }}"
width: 1/2
```

## Your setup
**Kirby Version**  
Kirby 4.0.1
