### ISSUE TITLE
Improve video block with support for local videos

### ISSUE THREAD

**Issue by dgsiegel** [k-next/kirby#6062]
## Description

While the current video block can include local videos by entering their direct URL it is quite tedious to do so. For a project of mine, I've added support for this locally - maybe you could re-use those parts?

First, I've extended the video blueprint similar to what the image block does:

```
name: field.blocks.video.name
icon: video
preview: video
fields:
  location:
    label: field.blocks.image.location
    type: radio
    columns: 2
    default: "web"
    options:
      kirby: "{{ t('field.blocks.image.location.internal') }}"
      web: "{{ t('field.blocks.image.location.external') }}"
  url:
    label: field.blocks.video.url.label
    type: url
    placeholder: field.blocks.video.url.placeholder
    when:
      location: web
  video:
    type: files
    query: model.videos
    multiple: false
    # you might want to add a template for videos here
    when:
      location: kirby
  poster:
    type: files
    query: model.images
    multiple: false
    image:
      back: black
    uploads:
      template: blocks/image
    when:
      location: kirby
  caption:
    label: field.blocks.video.caption
    type: writer
    inline: true
```

Next I've created a small plugin at `site/plugins/videopreview/index.php` in order to overwrite the video block preview:

```
<?php

Kirby::plugin('bii/videopreview', []);
```

Next, I've extended https://github.com/getkirby/kirby/blob/main/panel/src/components/Forms/Blocks/Types/Video.vue at `site/plugins/videopreview/index.js` in order to show the poster image and switch between local and remote videos:

```
panel.plugin("bii/videopreview", {
  blocks: {
    video: {
      computed: {
        captionMarks() {
          return this.field("caption", { marks: true }).marks;
        },
        video() {
          if (this.content.location === "web") {
            return this.$helper.embed.video(this.content.url ?? "", true);
          }

          if (this.content.video?.[0]?.url) {
            return this.content.video[0].url;
          }

          return false;
        },
        location() {
          return this.content.location;
        },
        poster() {
          if (this.content.poster?.[0]?.url) {
            return this.content.poster[0].url;
          }
        }
      },
      template: `
        <k-block-figure
          :caption="content.caption"
          :caption-marks="captionMarks"
          :empty-text="$t('field.blocks.video.placeholder') + ' …'"
          :is-empty="!video"
          empty-icon="video"
          @open="open"
          @update="update"
        >
          <k-frame ratio="16/9" v-if="location == 'web'">
            <iframe
              v-if="video"
              :src="video"
              referrerpolicy="strict-origin-when-cross-origin"
            />
          </k-frame>
          <k-frame ratio="16/9" v-if="location == 'kirby'">
            <video
              v-if="video"
              controls
              :src="video"
              :poster="poster"
            />
          </k-frame>
        </k-block-figure>
      `
    }
  }
});
```

Lastly, I prevent clicks on the video itself by adding the following to `site/plugins/videopreview/index.css`:

```
.k-block-figure video {
  pointer-events: none;
}
```

Everything works just fine for us like this, but it would be awesome if this could be integrated in Kirby as well.

## Your setup
**Kirby Version**  
4.0.1
