### ISSUE TITLE
Files section sort value NaN

### ISSUE THREAD

**Issue by AnnikaGruca-JUNO** [k-next/kirby#6067]
## Description
When uploading a file in a section without a defined file template and `sortable: false`,  `Sort: NaN` is inserted in the file’s content file. The file is then displayed at the end the section.

## Expected behaviour
In Kirby 3, the files were sorted by name.

## To reproduce

Can be reproduced in the Starterkit in `site/blueprints/pages/album.yml` from line 40:

```yml
  - width: 2/3
    sections:
      images:
        type: files
        layout: cards
        sortable: false # add this
        # template: image # remove this
```

## Your setup
**Kirby Version**  
4.0.1
