### ISSUE TITLE
Writer field topbar placeholder

### ISSUE THREAD

**Issue by bogdancondorachi** [k-next/kirby#6069]
## Description
I've tried the new `writer=>toolbar=>inline: false` to attach the toolbar to the top of the field in the text block. Then if you remove the `inline: false` option you're left with a placeholder where the toolbar used to be at the top.

From what I've seen the field is missing the `data-toolbar-inline: true` attr after you remove the `inline: field` and the following css values are applied:

```css
.k-writer:not([data-toolbar-inline=true]):not([data-disabled=true]) {
    grid-template-areas:
        "topbar"
        "content";
    grid-template-rows: var(--toolbar-size)1fr;
    gap: 0;
}
``` 

**Expected behavior**  
As the inline is back to true after removal of `inline: false` option, the placeholder should be removed as well.

**Screenshots**  
![image](https://github.com/getkirby/kirby/assets/39380741/d19fc433-a61d-41f7-9c75-8f6ff2ac2c99)

## To reproduce

1. Add the toolbar `inline: false` to the text block and then remove the option.

## Your setup
**Kirby Version**  
4.0.1

**Your system (please complete the following information)**
 - Device: Laptop
 - OS: Windows 11
 - Browser: Edge
 - Version: 120

**Additional context**  
I haven't tested if the same behavior happens inside a writer field as well.

**Comment by distantnative** [comment]
@bogdancondorachi Could you please share your blueprint that produces the described issue? I seem to miss something as I cannot reproduce it for me, no matter whether `inline: false` is added to `toolbar:` or just `toolbar` on it's own or `inline: true`...

**Comment by bogdancondorachi** [comment]
@distantnative Here's a test blueprint witch I can replicate the issue on a new starter-kit installation.
```
writerTest:
  type: writer
  toolbar:
    marks:
      - bold
      - "|"
      - link
``` 

When the toolbar prop is added the empty placeholder appears in the field. It's like the toolbar expects an inline value when it's initialized, not taking into account the default of inline. Without it, the placeholder appears even though the inline is true by default. Also happens if you leave the toolbar empty.

Maybe a missing check on the `:data-toolbar-inline`?
