### ISSUE TITLE
Command + S in structure editor in a block saves structure item’s title as block’s title

### ISSUE THREAD

**Issue by frankrausch** [k-next/kirby#6087]
## Description

I have a `blocks` template that contains a `structure`.

When I edit an item from the `structure` in Kirby 4’s panel and press the keyboard shortcut ⌘S, the `structure` item’s `title` is wrongly saved as the `block`’s `title` (= overwriting the title field of its parent). This doesn’t happen if I use the save icon in the toolbar.

**Expected behavior**  
- The save keyboard shortcut should not behave differently than the UI control for saving form data.
- Data should not be corrupted on save.

**Screenshots**  

## To reproduce

1. Create a template with a `blocks` field that contains a `structure` where both the block and the structure have a field called `title`.
2. Edit a `structure` item and press ⌘S or Ctrl + S while editing.
3. Observe that the `structure` item’s title overwrites the block’s title.

Here is a shortened version of the block template:

```yml
name: field.blocks.listblock1.name
fields:
  title: # <-- block title
    label: Headline
    type: text
  anchorTitle:
    label: Anchor Title
    help: used as ID to scroll to this block
    type: text
  text:
    label: Text
    type: textarea
    size: small
  items:
    label: Items
    type: structure
    fields:
      title: # <-- structure item title
        type: text
        required: true
      text1:
        type: textarea
      text2:
        type: textarea
```

## Your setup
**Kirby Version**  
4.0.2

**Console output**  

**Your system (please complete the following information)**
 - Device: Mac
 - OS: Sonoma
 - Browser: Firefox
 - Version: 120.0.1

**Additional context**  

Thanks!
