### ISSUE TITLE
Pages section with table layout doesn’t hide columns on mobile

### ISSUE THREAD

**Issue by linusrogge** [k-next/kirby#6106]
I use the following structure for a section to display entries:

```
sections:
  entries:
    type: pages
    query: page.entries
    layout: table
    columns:
      tags:
        type: tags
        width: 1/2
      date:
        width: 1/6
        align: right
        value: "{{ page.date.toDate('M d, Y') }}"
```

What I expect from the [documentation about the table layout](https://getkirby.com/docs/reference/panel/sections/pages#layout__table-layout) is that all columns other than the title are hidden on mobile, and they can be enabled with `mobile: true`.  Since Kirby 4, all columns remain and mostly cover the title, so I cannot even get to the child page (see screenshot 2).

I pointed this out [in the forum](https://forum.getkirby.com/t/mobile-option-on-table-layout-doesn-t-seem-to-apply/30008) already but it seems like it hasn’t been addressed yet.

<img width="1401" alt="Screenshot 2023-12-31 at 1 43 04 PM" src="https://github.com/getkirby/kirby/assets/38791104/98bc74c8-2ee9-4e15-a643-3712ad783d52">
<img width="441" alt="Screenshot 2023-12-31 at 1 43 16 PM" src="https://github.com/getkirby/kirby/assets/38791104/a8893537-da86-418e-968a-6ec225b92218">
