### ISSUE TITLE
Writer Field: Email link not highlighted after refresh

### ISSUE THREAD

**Issue by AnnikaGruca-JUNO** [k-next/kirby#6115]
## Description
Email links are not highlighted in the writer field if "email" is not listed as a writer mark and an email link is inserted via the link mark (in the link dialog).

## To reproduce
1. Have a writer field with marks: 
```yml
fields:
  text:
    type: writer
    nodes: false
    marks:
      - link
```
2. Select a word and apply the "link" mark to it, to open the link dialog
3. Choose the link type "Email" and enter a email address
4. Save the changes (link is still visible)
5. Reload the page – now the link isn't displayed anymore

If you now add the mark `email` to your writer field, the link is visible:
```diff
fields:
  text:
    type: writer
    nodes: false
    marks:
      - link
+     - email
```

## Your setup
**Kirby Version**  
4.0.2

**Comment by gbdesign2023** [comment]
The description says: "Sets the allowed HTML formats.". This is therefore not an error, as you explicitly only allow URLs with "marks: - link". If you omit the "marks" field properties, email links are highlighted again. However, you could declare it as an error that other link types can still be selected:

```
fields:
  text:
    type: writer
    nodes: false
    marks:
      - link
```

<img width="569" alt="Bildschirmfoto 2024-01-03 um 18 03 19" src="https://github.com/getkirby/kirby/assets/140849227/4bbcd21c-cb85-4585-97d4-d990f5f3e7f3">

**Comment by distantnative** [comment]
Indeed the result is kind of expected based on how the writer and underlying ProseMirror works.

However, I am wondering if with the new link field we really need the separate email mark and dialog. I think we could rather merge it to just the link mark/dialog (and then add the email link highlighting to the link mark too).

@bastianallgeier opinions?

**Comment by bastianallgeier** [comment]
I agree that we could merge it

**Comment by silllli** [comment]
I would vote for making the link types customizable though (just like the headings), for instance:

```yaml
fields:
  text:
    type: writer
    nodes: false
    marks:
      - link
    links:
      - email
      - tel
```
