### ISSUE TITLE
v4 color field previews

### ISSUE THREAD

**Issue by jaro-io** [k-next/kirby#6120]
## description
there is a difference when previewing `color` fields from a `structure` field vs. a `pages` section. for `structure` fields, the **color itself** is shown in the table preview. for `pages` sections, only the **color value** is shown in the table preview.

**expected behavior**  
i was expecting the table preview for `color` fields to be the same for both `structure` fields and `pages` sections. i don’t know if this is how you want it to be or not? i found it a little confusing though.

**screenshots** 
structure field
![structure](https://github.com/getkirby/kirby/assets/20298313/f1ba5dcb-cf50-47ac-842a-a4c2610e47b0)

pages section
![pages](https://github.com/getkirby/kirby/assets/20298313/e462978f-ddfe-4efa-b72f-c8edb9f6fecb)

## to reproduce
**structure field**
```yml
# categories.yml
sections:
    categories:
        type: fields
        fields:
            categories:
                type: structure
                fields:
                    title:
                        type: text
                    color:
                        type: color
```

**pages section**
```yml
# categories.yml
sections:
    categories:
        type: pages
        layout: table

# category.yml
sections:
    category:
        type: fields
        fields:
            color:
                type: color
```

## to fix
i already found an easy fix, which however does not seem to appear in the current [docs](https://getkirby.com/docs/reference/panel/sections/pages#layout__table-layout). maybe it would be nice to let everyone know that setting `type: color` for the column is allowed and works fine?

**pages section**
```yml
# categories.yml
sections:
    categories:
        type: pages
        layout: table
        columns:
            color:
                type: color
```

![fix](https://github.com/getkirby/kirby/assets/20298313/9157a0aa-4278-4ce7-921b-a6d53a7bc9a9)
