### ISSUE TITLE
Roles: blueprints get not extended when `::load()`

### ISSUE THREAD

**Issue by owzim** [k-next/kirby#6167]
## To reproduce

1. quickly boot up a kirby startekit:

```sh
git clone git@github.com:getkirby/starterkit.git
cd starterkit
composer install
php -S localhost:3001 kirby/router.php
```

2. create `site/blueprints/users/base.yml`:

```yml
fields:
  foo:
    type: text
permissions:
  users:
    create: false
    delete: false
    update: false
  access:
    settings: false
    users: false
```

3. create `site/blueprints/users/editor.yml`:

```yml
extends: users/base
title: editor
```

login with an editor user and go to http://localhost:3001/panel/users

1. you can see the fields are inherited

![image](https://github.com/getkirby/kirby/assets/1720088/c29818f2-fe20-4a92-8c87-06c8a9928685)

3. you can still add users, although `users.create: false`

![image](https://github.com/getkirby/kirby/assets/1720088/959bd521-8963-4196-9252-bae14e499804)

3. you can still edit other users fields, although: `users.update: false`

4. if you put the permissions in `site/blueprints/users/editor.yml` directly:

```yml
title: editor
permissions:
  users:
    create: false
    delete: false
    update: false
  access:
    settings: false
    users: false
```

Everything works as expected.

conclusion:

with `extends` fields are inherited, but permissions are not.
This is unexpected, since all other blueprints can be orchestrated in this manner.

## Your setup

kirby: `4.0.3` and `3.10.0`
php: `8.2.13`
