### ISSUE TITLE
Pages section: `query` and `help` using different entry points when `parent` set

### ISSUE THREAD

**Issue by arnaudjuracek** [k-next/kirby#6187]
## Description

_optional context: a website where panel users can be of role `actor` and be referenced in a `movie` page. When viewing a panel user page with the `actor` role, I’d like to have a pages section listing all the movies staring the current viewed actor._

After digging around with Kirby query language, I found out that the `user` keyword is not refering to the same object based on where the query string is used : 

```yml
# users/actor.yml
title: Actor

sections:
  starring:
    type: pages
    parent: site.find('movies')
    
    # won’t work because `user` is not the current viewed user
    # query: page.children.filterBy('actor', user.uid)
    
    query: site.dumpToLog(user)     # ❌ user is not the current viewed user, but the current *logged* user
    help: "{{site.dumpToLog(user}}" # ✅ user is the current viewed user
```

I tried various workaround with extensions to site/user/page methods, but in all cases I failed because I need to get a reference to the current viewed user.

Maybe the `page` object (which afaik is not used in query language in the user page context) should reference the current viewed user ?

## Your setup
**Kirby Version**  
`4.0.3`

**Comment by distantnative** [comment]
Does it work with `model`?

**Comment by arnaudjuracek** [comment]
Using `model` gives me the expected user page model when using in `help`, but returns the page computed by the `parent` key when used in `query`:

```yml
# users/actor.yml
title: Actor

sections:
  starring:
    type: pages
    parent: site.find('movies')
    query: site.dumpToLog(model)     # model of the movies page
    help: "{{site.dumpToLog(model}}" # model of the current view user page
```

I suppose that setting a `parent` changes the context of the query string in the `query`, but shouldn’t (?) change the `user`.

**Comment by distantnative** [comment]
@arnaudjuracek 

Ok it is a bit of a brain twister, but indeed:

`help` always runs the query from the current model (so the current view). For this `model` will refer to the view's user object. But `user` will as well, as the model adds its own alias also as entry term. So on a page view you have `model` and `page`, on a file view `model` and `file` and on a user view `model` and `user`.

The `query` runs in relation to the parent of the section. Without a parent set, that is the current view. But in your case there is one set and so `model` inside the `query` query refers to the movies page. 

And therefore, entry points added are `model` and `page` - no `user`. And now comes the twist: the Kirby query language also has a  `user` default function, which gets you the current user. And since this is not overwritten, this is why in your case you get the current user.


I am not sure if we should or could change this behavior. If it would be a little less confusing if we would bind also `help` to the parent... unclear.

**Comment by arnaudjuracek** [comment]
Having different entries for `help` and `query` when a `parent` is defined seems to me to be the desired behavior, as the `parent` only alters `query`. It may be unclear though that the `parent` prop only applies to `query`.

What threw me off was the `user` referring to a global object in one case and to the current `model` in the other, and your explanation of why was very clear, but may be not explicit enough in the docs.
As my use case is not really standard, I do not think you should change how `user` appears in various query contexts. It may be worth exploring in the Cookbooks advanced panel use cases using the `file` and `user` views.

I ended up relying on a custom User model method to create a virtual page acting as a proxy for the filter I needed : 

###### `ActorUser` model
```php
class ActorUser extends User {
  // Used as a hack to display movies starring a specific actor in its panel user page
  public function toPanelPage () : Page {
    return Page::factory([
      'slug' => 'movies',
      'model' => 'actor',
      // Data used in the ActorPage model to filter movies
      'content' => ['user' => $this->uuid()]
    ]);
  }
}
```

###### `ActorPage` model

```php
class ActorPage extends Page {
  public function children () : Pages {
    return parent::children()->filterBy('actors', '*=', $this->user());
  }
}
```

###### `users/actor.yml`

```yml
sections:
  …
  starring:
    type: pages
    parent: model.toPanelPage
```

The resulting panel section allows displaying `movies/` children filtered by the `user` viewed, and allows adding a movie directly from the user page, because the virtual page uses the `movies/` slug.

Handling such weird use cases by extending models feels really good in Kirby !
