### ISSUE TITLE
Structure field: rows displayed too high in specific circumstances

### ISSUE THREAD

**Issue by sebastiangreger** [k-next/kirby#6203]
## Description

I have a structure field that is displayed in a 1/2 width column. In K3, this field displays both the event title and start date, as desired:

```yml
columns:
  - width: 1/2
    sections:
      pages:
        type: pages
  - width: 1/2
    fields:
      events:
        type: structure
        columns:
          title:
            width: 1/2
          start:
            width: 1/2
        sortBy: start desc
        fields:
          title:
            type: text
          description:
            type: textarea
          start:
            type: date
          end:
            type: date

```

In K4.1.0-rc.2, the start date is no longer shown, instead the table rows are displayed with excessive white space. Adding `mobile: true` to the columns setting brings back the start dates and restores normal row height, but now there is a horizontal scroll bar (that, in FF at least, is visible on page load, then fades out).

This problem goes away as soon as the structure field is contained in a full-width column.

**Expected behavior**  
- Rows should be displayed at regular height
- The `mobile: true` setting should not render a scroll bar

**Screenshots**  
![structure-field-layout-bug](https://github.com/getkirby/kirby/assets/6355217/06dc2904-02d2-4de9-97cd-17dc409036e1)

## Your setup
**Kirby Version**  
K4.1.0-rc.2

**Your system (please complete the following information)**
 - Device: PC
 - OS: Linux Mint
 - Browser: FF
 - Version: 119.0

**Additional context**  
Playing around with the CSS, it seems that this rule causes the row height issue (removing `--button-height: 100%;` gets rid of the excess height):

```css
.k-table .k-table-options-column .k-options-dropdown-toggle {
	--button-width: 100%;
	--button-height: 100%;
	outline-offset: -2px;
}
```

Possibly somewhat related: #4415
