### ISSUE TITLE
Range field: Tooltip's `before` & `after` labels are not translatable

### ISSUE THREAD

**Issue by crisgfx** [k-next/kirby#6221]
## Description
I'm not sure if I'm setting it up wrong, but the `before` and `after` props of the `tooltip` are not translatable.

**Expected behavior**
Just like the field's `label`, `before` & `after` and `help` text, I'd expect the `tooltip`'s `before` and `after` props to be translatable as well.
  
```yaml
speed:
    label:
      de: Übergangsgeschwindigkeit
      en: Transition Time
    type: range
    min: 0
    max: 10
    step: .05
    tooltip:
      before:
        de: Genau
        en: Exactly
      after:
        de: Sekunden
        en: seconds
```

**Screenshots**  
<img width="787" alt="kirby-range-field" src="https://github.com/getkirby/kirby/assets/16305374/1dd977ca-68d8-4088-81cd-db834633f91f">

## To reproduce

1. Create a range field in Your blueprint.
2. Take the above yaml  as an example.

## Your setup
**Kirby Version**  
4.1.0-rc.3

**Additional context**  
This example of course is a bit silly – I just think for the sake of consistency, that these props should be translatable as well.

Tanks for reading!
