### ISSUE TITLE
[Panel] emoji page icons are getting cut off

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#6222]
## Description
Emoji page icons in page sections are getting cut off.
There is an `overflow: hidden` on all `k-frame` children so the emojis get cut off at line-height.

**Screenshot**  
![Screenshot 2024-01-29 at 17 08 09](https://github.com/getkirby/kirby/assets/60777/51250a1c-f04e-4759-b3d3-7c7ba31741b0)

**Potential Fix**
```css
[data-type="emoji"] {
  line-height: 1.5;
}
```

**Fix Screenshot**
![Screenshot 2024-01-29 at 17 15 22](https://github.com/getkirby/kirby/assets/60777/39a7d6e4-4fbe-43d0-8857-b9e82c20ecac)

## To reproduce

Add this to a pages section:
```yaml
image:
  query: icon
  back: hsl(0,0%,97%)
```
And add an emoji to a child page:
```yaml
title: Albums Page
icon: 📀
````
## Your setup
**Kirby Version**  
4.1.0-rc.3
