### ISSUE TITLE
Default values missing in page creation dialog

### ISSUE THREAD

**Issue by foxacid** [k-next/kirby#6229]
## Description
Default values work on of the page itself, but not in the page creation dialog.

**Expected behavior**  

Fields in the page creation dialog should be populated with the default values defined in the original fields.

## To reproduce

```
create:
  fields:
    - published

fields:
  published:
    type: date
    required: true
    default: today
```

![image](https://github.com/getkirby/kirby/assets/12812201/f74e46f6-e2a1-46a5-9ad0-807b8857ebd7)

(Field should be populated with today's date)
