### ISSUE TITLE
"Invalid Date" parsing dates in pages section with layout:table

### ISSUE THREAD

**Issue by sciloqi** [k-next/kirby#6230]
## Description
In the pages section, when using `layout:table` with custom columns, the date parsing shows "Invalid Date" for days > 12 and don't format as expected for days <= 12. Using date handler `intl`.

**Expected behavior**  
`Date: 2023-11-24 16:00:00`.toDate('dd.MM.Y') should be 24.11.2023 (is "Invalid Date")
`Date: 2021-10-05 00:00:00`.toDate('dd.MM.Y') should be 05.10.2021 (is "2021-05-10")

**Screenshots**  
![Bildschirmfoto 2024-01-31 um 18 12 57](https://github.com/getkirby/kirby/assets/23317040/44232804-e944-4c5e-8423-4a33c057abf9)

## To reproduce

1. Fresh starter-kit
2. add `intl` date handler to config.php
3. add `layout:table` with `columns: / date: / value: "{{ page.date.toDate('dd.MM.Y') }}` to blueprints/sections/notes.yml
4. See panel "site"

## Your setup
Kirby 4.1.0 (no problems with Kirby 4.0.3)

**Comment by afbora** [comment]
I can reproduce the issue on 4.1.0 either. Works great for 4.0.3

**Comment by distantnative** [comment]
I fear this is originating from https://github.com/getkirby/kirby/pull/6147

Before the PR, this would render as a text preview - now it's trying to render as a date preview and tripping up.

@sciloqi as quick fix adding `type: text` to your column definition should probably solve it for you

**Comment by afbora** [comment]
@distantnative Yes `type: text` works great.

**Comment by afbora** [comment]
I think also following usage give outputs same with `{{ page.date.toDate('dd.MM.Y') }}`

````yaml
columns:
  date:
    display: DD.MM.YYYY
````

**Comment by janstuemmel** [comment]
Bug still exists (kirby@4.2.0) when day ist < 10 in `2024-09-05` for example. 

![Bildschirmfoto_2024-04-16_19-23-27](https://github.com/getkirby/kirby/assets/7893682/f2918a4d-b85a-4b3b-9a7a-74bbb675def8)

For the first cell "Date Start" data is `Datestart: 2024-04-09`, kriby will print `2024-09-04 `. So i think there is any confusion with day and month. This happens only in table columns i think. 

However, it is still fixable with `type: text`.

Please reopen @distantnative

**Comment by distantnative** [comment]
@janstuemmel What's your blueprint?

**Comment by janstuemmel** [comment]
Works with `type: text`...

```yml
# events.yml

title: Events

tabs:
  events:
    label: Events
    columns:
      - width: 2/3
        sections:
          events: 
            extends: sections/events
            query: page.children.sortBy("dateStart", "asc").filterBy("dateEnd", "date >=", "today")

# ...
```

```yml
# sections/events.yml

label: Events
type: pages
template: event
limit: 10
sortable: false
status: published
layout: table
search: true
columns:
  dateStart:
    label: Datum Start
    #  type: text # <- fixes display of date
    value: "{{ page.dateStart.toDate('dd.MM.Y') }}"
    width: 1/7
  dateEnd:
    label: Datum Ende
    # type: text # <- fixes display of date
    value: "{{ page.dateEnd.toDate('dd.MM.YY') }}"
    width: 1/7
```

```php
<?php

return [
  'date.handler' => 'intl',
  'locale' => 'de_DE.UTF-8',
  // ...
];
```

**Comment by distantnative** [comment]
And your event.yml?

**Comment by janstuemmel** [comment]
```yml
# pages/event.yml
title: Event

create:
  slug: "{{ page.dateStart.toDate('Y-m-d') }}-{{ page.title.slug }}"
  fields:
    - dateStart
    - dateEnd
  redirect: false
  status: draft

status:
  draft: false
  listed: true
  sort: false

columns:
 # ...
  - fields:
      dateStart:
        type: date
        label: Datum Start
        display: DD.MM.YYYY
        required: true
      dateEnd:
        type: date
        label: Datum Ende
        display: DD.MM.YYYY
        required: true
```

Example event content: 

```
Datestart: 2024-04-10

----

Dateend: 2024-04-29
```

**Comment by distantnative** [comment]
So your field is defining the display as `DD.MM.YYYY` which is also used for the date preview in the table to make sense and display the value as date, but then your value query returns the value as string `dd.mm.Y`. That doesn't match and likely trips up the date parser. Can you try to get rid of the `value` line and just add `display: dd.mm.Y` in the column definition? I think then the column can use just the standard field value (instead your custom preformatted one that trips up the redundante date parsing) and display it with the format you like.

**Comment by janstuemmel** [comment]
```yml
```

**Comment by janstuemmel** [comment]
Like this?
 
```yml
# sections/events.yml

label: Events
type: pages
template: event
limit: 10
sortable: false
status: published
layout: table
search: true
columns:
  dateStart:
    label: Datum Start
    #  type: text # <- fixes display of date
    # value: "{{ page.dateStart.toDate('dd.MM.Y') }}"
    display: dd.mm.Y
    width: 1/7
  dateEnd:
    label: Datum Ende
    # type: text # <- fixes display of date
    value: "{{ page.dateEnd.toDate('dd.MM.YY') }}"
    width: 1/7
```

That leads to a empty "Date Start" column. And it makes sense, since value is undefined

![Bildschirmfoto_2024-04-16_22-18-44](https://github.com/getkirby/kirby/assets/7893682/56a9ec47-0d36-4ad3-bc54-f0817ab3d91c)

What works though is:

```yml
columns:
  dateStart:
    label: Datum Start
    # type: text
    value: "{{ page.dateStart }}"
    display: DD.MM.YY
    width: 1/7
```
