### ISSUE TITLE
Object Field: container query issue

### ISSUE THREAD

**Issue by bogdancondorachi** [k-next/kirby#6241]
## Description
If you are trying to place the `object field` inside a container that's lower than `2/3` the preview is slightly different and its values are not displayed inside it.

```css
@container (max-width: 40rem) {
  .k-table :where(th,td):not(.k-table-index-column):not(.k-table-options-column) {
    width: auto!important;
  }
}
``` 

**Screenshots**  
![image](https://github.com/getkirby/kirby/assets/39380741/14b34c39-5423-4759-8f85-0f6bb1b9a1e9)

## To reproduce
```yaml
sections:
  profile:
    type: fields
    fields:
      contact:
        type: object
        fields:
          photo:
            type: files
          name:
            type: text
          email:
            type: email
          phone:
            type: tel
``` 

## Setup
**Kirby Version 4.1.0**

 - OS: Windows 11
 - Browser: Edge
 - Version: 121
