### ISSUE TITLE
[4.1.0][Panel] Tab emoji icon not working

### ISSUE THREAD

**Issue by maxchene** [k-next/kirby#6276]
## Description
By setting an emoji value for icon property in tab blueprint, the selected emoji won't show. But string values (available icons list) still work.

```yaml
title: My blueprint

tabs:
  content:
    label: Content
    icon: 🎓 # icon is not displayed
   
  seo:
    label: SEO
    icon: search # still works
```
It used to work on kirby 3, and the official documentation states:
The icon is optional. Please check out the [list of available icons](https://getkirby.com/docs/reference/panel/icons). You can also use an emoji by pasting it directly into the blueprint.

**Expected behavior**  
I expected that emoji icons to be displayed in tabs like they id in kirby 3.

## Your setup
**Kirby Version 4.1.0**  

**Console output**  
```html
<span class="k-button-icon">
    <svg aria-hidden="true" data-type="🎓" class="k-icon">
        <use xlink:href="#icon-🎓"></use>
    </svg>
</span>
```
