### ISSUE TITLE
Table layout has super wide column for thumbnail and status at smaller width

### ISSUE THREAD

**Issue by miragecraft** [k-next/kirby#6304]
## Description
![image](https://github.com/getkirby/kirby/assets/1615599/26359146-5b1f-429b-a764-77997196f082)

This is my blueprint for this section
```yaml
type: pages
label: Entries
layout: table
limit: 50
columns:
  date:
    width: 6.7rem
    value: "{{ page.date.toDate('M j, Y') }}"
    align: right
  tags:
    type: tags
    width: 1/5
template: entry
empty: No entries yet
sortBy: date desc
```

## Your setup
**Kirby Version**  
4.1.0
