### ISSUE TITLE
Autofocus in modal should also focus non-native input elements

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#6347]
## Description
I have a structure with two tags fields at the beginning:

```yml
credits:
  type: structure
  fields:
    role:
      type: tags
    name:
      type: tags
    website:
      type: url
```

Whenever I add a new entry and the fields slide in from the side, the website field gets focused.

**Expected behavior**  
The first field – the role field – should get focused.

**Screenrecording**  

https://github.com/getkirby/kirby/assets/60777/7cd6fe2e-d40f-4fc1-b7db-ef2bd9b37577

## Your setup
**Kirby Version**  
4.1.2

**Comment by afbora** [comment]
Not sure this is bug or intended but not just for tags field, same for also structure, object, blocks and layout field.

**Comment by gbdesign2023** [comment]
@mrflix You can specify which field should be automatically focused on the field properties: 
`autofocus: true `
https://getkirby.com/docs/reference/panel/fields/text#field-properties
Please note: Only the first field with this name is considered.

**Comment by mrflix** [comment]
Thanks for the hint, Gerrit. I added `autofocus: true` to the first field (role) and that made the second field (name) autofocus when adding a new row to the structure O_o

**Comment by gbdesign2023** [comment]
Of course, this is not the purpose of the autofocus option if it does not work. Let's wait and see what the developers have to say.

**Comment by distantnative** [comment]
> I added autofocus: true to the first field (role) and that made the second field (name) autofocus when adding a new row to the structure

I cannot reproduce this.

When I add

```yaml
credits:
  type: structure
  fields:
    role:
      type: tags
      autofocus: true
    name:
      type: tags
    website:
      type: url
 ```
 
 the first field gets focused:
<img width="808" alt="Screenshot 2024-03-23 at 15 51 53" src="https://github.com/getkirby/kirby/assets/3788865/a853f0fb-a202-46aa-9817-cbfe7ea987d0">

 Without setting an explicit autofocus, dialogs and drawers will attempt to focus the first element from this list of selectors: 
 
 ```js
		 "[autofocus]",
		"[data-autofocus]",
		"input",
		"textarea",
		"select",
		"[contenteditable=true]",
		"[type=submit]",
		"button"
```
 
 Since the tags field/input is rather special, the native `input` element of the text fields grabs the focus instead.
