### ISSUE TITLE
Nested drawer: Ctrl + S with date fields clears content

### ISSUE THREAD

**Issue by bezin** [k-next/kirby#6390]
## Description
I have a custom block with a structure field, that has several fields (text, color, list, two date fields)
When I edit a structure item and hit CTRL+S, the structure form is closed and I see the editing mask for the block again, but all content is gone – at least visually. When I close the drawer and save the changes, everything works as expected (the content is still there incl. my intentionally made changens). 

This does not happen, when I exclude the date fields. However, the changes I made were not in the date fields, but in a text field.

**Expected behavior**  
I expect CTRL+S to close the structure field edit mask and return to the block edit mask without loosing the content. 

## Your setup
Kirby 4.2.0 on PHP 8.3, running on Ubuntu in WSL (Windows 11) with Symfony Webserver (in Brave)
Also tested with Kirby 4.3.0 on PHP 8.3, running on MacOS 14.5 with Symfony Webserver (in Firefox)

**Comment by distantnative** [comment]
@bezin Could you please share your blueprint?

**Comment by bezin** [comment]
Sure thing, here you are:

```
# site/blueprints/blocks/timeline.yml
name:
  en: Timeline
  de: Zeitleiste
fields:
  headline:
    label:
      en: Headline
      de: Überschrift
    type: text
    width: 1/2
    required: true
  phases:
    label:
      en: Project phases
      de: Projektphasen
    columns:
      title: true
      color: true
      from: true
      till: true
    type: structure
    fields:
      title:
        type: text
        required: true
        width: 1/2
      color:
        label:
          en: Color
          de: Farbe
        type: color
        required: true
        width: 1/2
      from:
        label:
          en: From
          de: Von
        type: date
        calendar: false
        required: true
        width: 1/2
      till:
        label:
          en: Till
          de: Bis
        type: date
        calendar: false
        required: true
        width: 1/2
      objectives:
        type: list
        required: true
```

When you use it like this, `ctrl + s` clears the data in the view. However, when you uncomment `from` and `till` (both, one is not enough), everything works as expected.

**Comment by Afplaktape** [comment]
I ran into the same problem with this blueprint. While working in the nested structure, it overrides structure 1 when I'm in a field and press cmd+s.

```
title: Nested structure

fields:
  structure1:
    type: structure
    label: Structure 1
    fields:
      title:
        type: text
      structure2:
        type: structure
        fields:
          title:
            type: text
          date:
            type: date
            default: today
``` 

PHP: 8.3.7
Kirby: 4.2.0

Edit: When I remove the datefield, everything works the way it should work

**Comment by bezin** [comment]
@distantnative Please let me know if you need further information to investigate

**Comment by distantnative** [comment]
@bezin 

I tried it again but it all seems to work for me on 4.3


https://github.com/getkirby/kirby/assets/3788865/d20c29ba-d6fa-49b0-86c6-2c1ed90b5911

Are there any steps you do differently?

**Comment by bezin** [comment]
Hi! I tried it with 4.3, but the issue is still there. See next comment for more information.

~However, when I add a new structure item like you do, it does indeed work. But try editing the first structure item. Actually you do not need to edit anything: Just open the first structure item and hit cmd+S.
Also: I use the structure field in a block (as I wrote in the opening comment), hence all happens inside a drawer (if that makes any difference).~

**Comment by distantnative** [comment]
Opening the first structure item and hitting Cmd+S works just fine, nothing disappears either.

And yes using it nested in a block can make a difference. Please post the actual blueprint that causes the problem.

**Comment by bezin** [comment]
Here is the blueprint I used:

```
name: Timeline
fields:
  headline:
    type: text
    width: 1/2
    required: true
  phases:
    columns:
      title: true
      from: true
      till: true
    sortable: false
    type: structure
    fields:
      title:
        type: text
        required: true
        width: 1/2
      from:
        type: date
        calendar: false
        required: true
        width: 1/2
        disabled: true
      till:
        type: date
        calendar: false
        required: true
        width: 1/2
        disabled: true
```

1. Add this blueprint to your project.
2. Add a block of this type to a page.
3. Enter a headline
4. Hit cmd+s: the drawer will close as expected. 
5. Edit the block aka open the drawer again
6. Add a new phase
7. Just hit cmd+s without adding anything: You will go one step back and see that the headline field has been emptied. 

Now remove the fields `from` and `till` and try again: Now everything works as expected.

**Comment by distantnative** [comment]
Please post your whole blueprint, incl. the blocks field and all. Posting only parts makes us guess your setup and run in circles when trying to replicate the issue.

**Comment by bezin** [comment]
Here you go:

```
//site/blueprints/pages/test.yml
title: test
tabs:
  content:
    icon: page
    label:
      en: Content
      de: Inhalt
    preset: page
    files: false

    fields:
      builder:
        label:
          en: Blocks
          de: Blöcke
        pretty: true
        type: blocks
        fieldsets:
          timeline:
            name: Timeline
            fields:
              headline:
                type: text
                width: 1/2
                required: true
              phases:
                columns:
                  title: true
                  from: true
                  till: true
                sortable: false
                type: structure
                fields:
                  title:
                    type: text
                    required: true
                    width: 1/2
                  from:
                    type: date
                    calendar: false
                    required: true
                    width: 1/2
                    disabled: true
                  till:
                    type: date
                    calendar: false
                    required: true
                    width: 1/2
                    disabled: true
```

This happens with date fields:
https://github.com/getkirby/kirby/assets/4400435/f98c2e88-a973-428e-aff4-a5100195fd6e


This happens without date fields:
https://github.com/getkirby/kirby/assets/4400435/ed6ff691-d5d9-406b-b551-1484e064cbcc

Everytime the drawer is closed, I had hit cmd+s (sorry, new to Mac, don't know how to show the hot keys yet ;-))

Speaking of MacOS: When I opened the issue, I was on Windows with Brave, now I test with MacOs and Firefox. Happens anyway.
