### ISSUE TITLE
Page tables load very slow in 4.2

### ISSUE THREAD

**Issue by timkinali** [k-next/kirby#6404]
## Description
After updating to 4.2, some page sections with `layout: table` load extremely slow. 100 pages ~10 seconds, 30 pages ~6 seconds. The issue goes away when changing layout to list, cardlets or cards. Confirmed by other users too.

In the forum it was suggested by @rasteiner  that the toggle field preview fix in this commit https://github.com/getkirby/kirby/commit/75eb89cc27d35c0cd0da06680077462119bd2e88 can be the cause:
"It seems to introduce a new instantiation (new Form($model)) which is run for every row in the table." 

## Your setup
**Kirby Version**  
Kirby 4.2

**Additional context**  
More details in the forum post https://forum.getkirby.com/t/page-sections-load-slow-kirby-4-2-issue/31373/3

**Comment by tobimori** [comment]
interesting! noticed the same with dreamform submissions since they use the table layout.

**Comment by distantnative** [comment]
Tricky one... Indeed before 4.2 the rows weren't processed by the Form class. But that produced wrong values, no defaults etc. – we'll have to see if/how we can make it more performant while using the Form class.

**Comment by rasteiner** [comment]
PS: I haven't like bisected it or anything, mine was just guess by looking at what changed with table layouts between 4.1 and 4.2. 
Maybe the problem's somewhere else. 

Anyway if it really were the `new Form($model)`... 
10s/100items = 0.1s/item 
That's more than expected for a simple "new Form" (even if that triggers loading the blueprint), so I guess there is some `O(n²)` recursion going on somewhere.

**Comment by distantnative** [comment]
I haven't looked closer at it either yet. But I'd also think this is the main think that changed regarding table values.

**Comment by rasteiner** [comment]
Looked at this again, but it's actually not so easy to reproduce (like: I personally didn't get it to reproduce).

I've created a test setup with the worst things I could imagine, but a pages section with `layout: table` and `limit: 100` still loads in ~70ms on my rather slow test server (php 8.2 in debian docker image on ubuntu) and 4.2.0. 

here's the blueprints I've used:
Parent:
```yml
title: Test many children
sections:
  pages:
    layout: table
    limit: 100
    columns:
      title: true
      toggle: true
```

Child:
```yml
title: Child

sections:
  files:
    type: files
    layout: cards
  pages:
    type: pages
    layout: table
    parent: page.parent
    limit: 100
  fields:
    type: fields
    fields:
      toggle:
        label: Checkbox
        type: toggle
      info:
        text: the website has {{ site.index.count() }} pages
```

Could you share the blueprints of the parent and child pages? Maybe also some information on the server where this problem shows?

**Comment by gbdesign2023** [comment]
> Could you share the blueprints of the parent and child pages?

In my case, ALL children and grandchildren are read out. Of course, I cannot post any blueprints of this. I have posted the blueprint with the table in the forum:
https://forum.getkirby.com/t/page-sections-load-slow-kirby-4-2-issue/31373/10

It feels like the display takes twice as long on the iPhone as on the desktop PC.

**Comment by georgobermayrsaf** [comment]
+1 form my side. Have the same issue with pages tables sections. Its not related the the columns I display. The load is way slower in table layout than in one of the other layouts. In my current setups loads take more than 30s for such a section, vs 70ms for a non-table section.

**Comment by rasteiner** [comment]
> +1 form my side. Have the same issue with pages tables sections. Its not related the the columns I display. The load is way slower in table layout than in one of the other layouts. In my current setups loads take more than 30s for such a section, vs 70ms for a non-table section.

could you share the blueprints of both the pages section as well as the page blueprint of the pages being displayed in it?

**Comment by timkinali** [comment]
Here's a video... You can see tables loading slow while lists and cards load fast. The table pagination is also slow. 
https://www.dropbox.com/scl/fi/lkrtspfguygmiv6ytv9jh/Sk-rminspelning-2024-05-08-kl.-13.30.00.mov?rlkey=k6grulvztglaj9qyuqg2u0b83&st=25dkctjh&dl=0

I also disabled all plugins with no change.

**Comment by distantnative** [comment]
@timkinali Could you please still share your blueprints? That would help reproducing and finding the issue (and hopefully a solution).

**Comment by georgobermayrsaf** [comment]
> could you share the blueprints of both the pages section as well as the page blueprint of the pages being displayed in it?

The section blueprint is rather simple:

```yml
label: Subpages
type: pages
templates:
  - storytelling
  - product
  - website.academy.entrypoint
  - website.events.entrypoint
  - website.journal.entrypoint
  - website.jobs.entrypoint
  - website.news.entrypoint
  - website.pressreleases.entrypoint
  - website.webinars.entrypoint
  - loginarea.entrypoint
  - search.results
layout: table
search: true
columns:
  template:
    label: Template
    value: '{{ page.intendedTemplate }}'
    type: tags
  path:
    label: Path
    value: '{{ page.websiteId }}'
  lastUpdate:
    label: Last Update
    value: '{{ page.modified("d/m/Y H:i") }}'
query: page.index(true)
sortBy: title asc
image:
  query: page.teaser.image.toFile
  ratio: 1/1
  cover: true
```

But the issue is the same with just:
```yml
label: Subpages
type: pages
layout: table
```

I'm afraid I can't share the page blueprint. The setup is too complex with too many extended fields, block field sets and so on. There are all kinds of field types in the blueprint.
