### ISSUE TITLE
Calendar not working with empty date field included in a structure field

### ISSUE THREAD

**Issue by animaux** [k-next/kirby#6422]
## Description

When having an empty date field inside a structure field and trying to use the calendar date picker, only a small black square is showing up.  After entering a value by hand the calendar works as expected.

**Expected behavior**  

The calendar date picker should open.

**Screenshots**  

![Skjermbilde 2024-04-30 kl  14 42 08](https://github.com/getkirby/kirby/assets/446874/5119ead9-bc50-4652-bfb4-9186360502f6)

## To reproduce

Create a page with the following field in the blueprint:

``` yaml
termine:
  label: Termine
  type: structure
  fields:
    datum:
      label: Datum
      type: date
      width: 1/3
      required: true
```

## Your setup

**Kirby Version**  
4.2.0 (PHP 8.3.6)

**Console output**  

`RangeError: Array length must be a positive integer of safe magnitude.`

**Your system (please complete the following information)**
 - Device: mac Mini 2018 (Intel)
 - OS: macOS 14.4.1
 - Browser: Safari
 - Version: 17.4.1
