### ISSUE TITLE
URLs of link fields are not truncated in table layout columns

### ISSUE THREAD

**Issue by philipptrenz** [k-next/kirby#6510]
## Description

When using a table layout for pages with an url field in a column, the url link within this column gets truncated. When using a link field with an URL, the whole url string is displayed and wrapped into multiple lines, if too long.

```yml
          redirects:
            type: pages
            layout: table
            columns:
             linkField:    # <- this one is shown in full length, wrapped into multiple lines 
                type: link
                value: "{{ page.link }}"
             urlField:    # <- this one is shown truncated 
                type: url
                value: "{{ page.link }}"
```

**Expected behavior**  

I expect that url and link field types are displayed equally in a page table layout column: Getting truncated if too long.

**Screenshots**  

![Bildschirmfoto 2024-06-27 um 11 43 23](https://github.com/getkirby/kirby/assets/11627598/13c2e2f9-fdf7-4a5f-b0be-b13a9de7e742)

## To reproduce

See blueprint snippet above.

## Your setup
**Kirby Version**  

4.3.0
