### ISSUE TITLE
Files & Pages field: singular empty text when multiple: false

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#6565]
I'm a big fan of being able to change the empty text of file and page fields and sections.

I just stumbled upon that the files & pages field always uses a plural empty text:

"No pages selected yet"
"No files selected yet"

Even when `multiple: false` is set to restrict the field to only select one file/page.
In that case it should say:

"No page selected yet"
"No file selected yet"

**Comment by gbdesign2023** [comment]
@mrflix I would not describe this as an error, as there is an option to specify the text yourself if no page or file has been selected yet:

```
fields:
  related:
    label: Related Pages
    type: pages
    multiple: false
    empty: "No page selected yet"
```

https://getkirby.com/docs/reference/panel/fields/files#field-properties
https://getkirby.com/docs/reference/panel/fields/pages#field-properties

There are certainly also special scenarios where a distinction between singular and plural integrated into the core system is undesirable.
