### ISSUE TITLE
Table layout pages section: interactive previews are not updating content

### ISSUE THREAD

**Issue by twiro** [k-next/kirby#6582]
### Description:

If a **toggle field** is included as a **column** in a **list of pages in table layout** the preview of the field behaves buggy/irritating:

### Blueprint:

```
example_a:
  label: Table
  type: pages
  layout: table
  columns:
    toggle:
      label: Toggle Field Table Preview
```
### Screenshot of the resulting table:

![Bildschirmfoto 2024-07-29 um 14 26 24](https://github.com/user-attachments/assets/e8bb48f5-7737-40a3-84e7-9a4538a758bd)

### Expected behavior / Problem:

With that preview given _(especially as the UI feels fully functional)_ **I'd expect the toggle value to get saved whenever I use a toggle in the table** – only, it doesn't!

### More Context:

Looks like this preview was originally [implementend for the structure field](https://github.com/getkirby/kirby/pull/2141) and works there. _(Haven't tested that actually)_

## B) Example B

In the forum I ran across the idea to use `type: text` for the preview of a toggle field in table layout, but that doesn't result in a satisfying experience either:

### Blueprint:

```
example_b:
  label: Table
  type: pages
  layout: table
  columns:
    toggle:
      label: Toggle Field Table Preview
      type: text
```
### Screenshot of the resulting table:

<img width="743" alt="Bildschirmfoto 2024-07-29 um 14 27 01" src="https://github.com/user-attachments/assets/dc50a37d-902a-46e1-9fde-5b7c86475932">

### Expected behavior / Problem:

If changing the preview of a toggle field to text in a table column is actually possible, I'd expect to see the toggle text values I defined in my blueprint (**`Ja`**, **`Nein`**) or at least the default text values for the given language (**`an`**, **`aus`**) – but all i get is **`true`** and **`false`**.

## C) Example C

Thinking about the text values of the toggle field preview a little more neither **`true`** and **`false`** nor the default text values of the given language (**`an`** and **`aus`**) do feel really convincing here  – if the values can be customized in the blueprint, the only really satisfying solution for the field preview would be to have it customazible there too. If not automatically, then at least by redefining the values in the columns-settings of the table:

### Blueprint:

```
example_c:
  label: Table
  type: pages
  layout: table
  columns:
    toggle:
      label: Toggle Field Table Preview
      type: toggle
      text:
        - "Nein"
        - "Ja"
```
### Screenshot of the resulting table:

![Bildschirmfoto 2024-07-29 um 14 26 24](https://github.com/user-attachments/assets/9136afe1-4d4f-4b1a-a89c-601e06d399e2)

### Expected behavior / Problem:

Apart from the missing saving-functionality described in example A, I'd expect to see **`Ja`** and **`Nein`** used instead of  **`an`** and **`aus`**.

## Setup / System

- Kirby Version: 4.3.0  
 - OS: macOS 10.15.7
 - Browser: Firefox
 - Version: 128

**Comment by distantnative** [comment]
@twiro For me, this really boils down to the issue in (A). As you spotted yourself, the preview was initially created for the structure field and then they are getting re-used now for the tables layout of sections. However, we need to fix them that they either really update the page content or that in sections they are display only without any interaction.

(B) works as intended and expected, displaying the content field value as text. We aren't looking up the field type in addition when the column type is defined, it gets treated as that type.

(C) I don't see much value here currently in re-implemnting the logic twice. You can define the texts for the different states on the actual field.

**Comment by ckamper** [comment]
Hey, as I just ran into this issue and all the other forum posts describing the issue link here, I would like to drop a quick workaround here:
```
columns:
  pin:
    label: Angepinnt?
    type: html
    value: "{{ page.pin.isTrue ? 'Ja' : 'Nein' }}"
```
This way, editors are not tempted to click the toggle
