### ISSUE TITLE
Page creation dialogue: "add" button is no longer displayed [regression]

### ISSUE THREAD

**Issue by gbdesign2023** [k-next/kirby#6597]
Since Kirby 4.3.0 the page creation dialogue no longer works as before.  

If I complete my blueprint as described here ...
https://getkirby.com/docs/reference/panel/blueprints/page#page-creation-dialog

```
title: Product
create:
  title:
    label: Product name
  fields:
    - price
    - brand
  redirect: false
  status: listed
```

... the "add" button no longer appears on the parent page:

<img width="736" alt="430" src="https://github.com/user-attachments/assets/eba281aa-555a-4ed9-b0a4-1af16e583d16">

Only when I delete the line "status: listed", the "add" button is displayed again. 
However, the newly created page is then saved as a draft, which is undesirable. 

This still worked with Kirby 4.2.0:
<img width="734" alt="420" src="https://github.com/user-attachments/assets/e2cb0c1a-37ce-43b0-9feb-297a63daf5e3">

I have already started a discussion about this:
https://forum.getkirby.com/t/add-button-is-no-longer-displayed-to-add-new-page/32136
