### ISSUE TITLE
Blocks with `preview: fields`: Block name and tabs do not wrap

### ISSUE THREAD

**Issue by hariom147** [k-next/kirby#6634]
## Description
When using `preview: fields` for blocks with a long title and/or many tabs, the block-title and the tabs do not wrap for narrow layouts, but instead move _into_ eachother.

**Expected behavior**  
When space runs out, block-title and tabs should wrap, as to stay readable and clickable.

**Screenshots**  
![Screenshot 2024-08-20 at 11 46 26](https://github.com/user-attachments/assets/8979b220-af63-40b6-8bfa-52546f21ffd3)

## To reproduce
Use this modified blueprint of the default quote-block in the starterkit.

```
name: Block with a longer than usual name
icon: quote
wysiwyg: true
preview: fields
tabs:
  tab1:
    fields:
      text:
        label: field.blocks.quote.text.label
        placeholder: field.blocks.quote.text.placeholder
        type: writer
        inline: true
        icon: quote
      citation:
        label: field.blocks.quote.citation.label
        placeholder: field.blocks.quote.citation.placeholder
        type: writer
        inline: true
        icon: user
  tab2:
    fields:
      info1:
        type: info
        text: Donec id elit non mi porta gravida at eget metus. Nulla vitae elit libero, a pharetra augue. Sed posuere consectetur est at lobortis.

  tab3:
    label: Tab with a really long name
    fields:
      info1:
        type: info
        text: Donec id elit non mi porta gravida at eget metus. Nulla vitae elit libero, a pharetra augue. Sed posuere consectetur est at lobortis.
```
