### ISSUE TITLE
File `create.format` blueprint option also converts mp4 to broken webp

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#6715]
```yaml
create:
  width: 1920
  height: 1920
  format: webp
```

> If the file blueprint also accept non-image files, those will be skipped and their format/extension left untouched.

This should leave mp4 files unchanged, but it doesn't.

Original report: https://forum.getkirby.com/t/convert-image-formats-on-upload-file-blueprint-option-does-not-ignore-video-files-produces-broken-files-as-a-result/32600
