### ISSUE TITLE
Dynamic icon option for Toggles field is ignored

### ISSUE THREAD

**Issue by philipmarnef** [k-next/kirby#6780]
Dynamic options for a Toggles field work for 'text' and 'value' but the 'icon' key is ignored and only the label text is shown.

Providing an options array in the blueprint with text/value/icon works, doing the same with a query does not.

Kirby 4.1.1
No console errors.

blueprint:
```
              test1:
                label: Test
                type: toggles
                labels: false
                options:
                  - text: Option 1
                    value: o1
                    icon: text-left
                  - text: Option 2
                    value: o2
                    icon: text-right

              test2:
                label: Test
                type: toggles
                labels: false
                grow: false
                options: 
                  type: query
                  query: page.testArray
                  text: "{{ item.text }}"
                  value: "{{ item.value }}"
                  icon: "{{ item.icon }}"
```

page method:
```
'testArray' => function () {
	return [
		[
			'text' => 'Option 1',
			'value' => 'o1',
			'icon' => 'text-left',
		],
		[
			'text' => 'Option 2',
			'value' => 'o2',
			'icon' => 'text-right',
		],
	];
},
```

Test 1 displays fine, Test 2 shows the (correct) labels instead of Icons
