### ISSUE TITLE
Panel throws Type Error in Pages Select Search Field when searching for Virtual Pages

### ISSUE THREAD

**Issue by rottstegge** [k-next/kirby#6798]
## Description
When using the search function of a Pages Select Field  that queries for a number of Virtual Pages, Kirby throws the following Type Error:

```
Kirby\Toolkit\Str::lower(): Argument #1 ($string) must be of type ?string, array given, called in […]projectfolder/kirby/config/components.php on line 226
```

Details from Console
```
file: "/kirby/src/Toolkit/Str.php",
route: "pages/([a-zA-Z0-9\.\-_%= \+\@\(\)]+)/fields/([a-zA-Z0-9\.\-_%= \+\@\(\)]+)(?:/(.*))?"
```
The error is only being thrown once more than one character is entered into the search field. When only a single character is entered, the search results stay empty, but no error is thrown.

**Expected behavior**  
Show results appropriate to the Search Term

## To reproduce
The Pages Select Field is setup like this:

```
            fields:
              events_highlights:
                label:
                  en: Event Highlights
                  de: Programm Highlights
                type: pages
                layout: cards
                size: small
                subpages: false
                query: site.children.listed.filterBy('intendedTemplate', 'events').children.listed.filterBy('intendedTemplate', 'event')
```

The Pages being queried are Virtual Pages, they don't exist inside the file system. They are created from the cached response to an API call, the API being a venue management platform. The Pages select field is part of the Homepage Blueprint while the queried pages (using the Template Event) are children of a page using the Template Events.

## Your setup
Kirby 4.3.1
Running on a local Server (non-https)
