### ISSUE TITLE
[v5] View buttons with link should accept Query language similiar to page preview

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#6861]
## Description
![CleanShot 2024-12-10 at 13 16 16@2x](https://github.com/user-attachments/assets/eae7df72-a590-46c8-b3e3-66fa6ae4db5f)

This doesn't work - yet Query language works in `options.preview`.
```yaml
buttons:
  preview:
    icon: youtube
    text: socialstar.youtube.video
    theme: red
    link: "https://youtu.be/{{ page.uuid.id }}"
```

Same for the text, so it works with translations.

## Your setup
**Kirby Version**  v5-beta.1

**Comment by medienbaecker** [comment]
I've noticed the view buttons do not accept a translation array either, is this the same issue?

```yml
buttons:
  email:
    text:
      de: Kontakt
      en: Contact
    icon: email
    link: mailto:mail@example.com
    theme: info
```

This throws `Kirby\Panel\Ui\Buttons\ViewButton::__construct(): Argument #16 ($text) must be of type ?string, array given`.

Also, looking at the other stuff in my blueprint I'm wondering why this is `text` instead of `label`. I personally find it confusing/inconsistent.
