### ISSUE TITLE
Writer field: getting console error when no buttons available for inline mode

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#6863]
## Description

Getting console error when no marks or nodes available for inline mode. Try to select a text in writer field and check the console.

````yaml
writer:
    type: writer
    marks: false
    nodes: false
````

> TypeError: this.$el.getBoundingClientRect is not a function

## Your setup
**Kirby Version**  

4.5.0
