### ISSUE TITLE
Block field: Tabs overlapping block title

### ISSUE THREAD

**Issue by johannahoerrmann** [k-next/kirby#6864]
## Description
In the panel, when setting up a block with tabs and checkboxes in a 1/3 width sidebar, I quickly have issues with tab text overlapping the block title as well as checkbox items overflowing the block.

**Expected behavior**  
Tabs: I would expect the tabs nav to at least move below the block title. It could even break into more than one line of tab text to remain readable and usable.
Checkboxes: I would expect long words to wrap.

**Screenshots**  

<img width="267" alt="grafik" src="https://github.com/user-attachments/assets/d0c84a66-05f8-4d4f-a965-efb4d64b3711" />

## To reproduce

1. Set up panel with 2 columns, 2/3 and 1/3 width
2. Set up block field in sidebar with following block

Block setup:
```
name:
  en: People
  de: Personen
icon: user
preview: fields
wysiwyg: true
tabs:
  selection:
    label:
      en: Selection
      de: Auswahl
  titel:
    label:
      en: Title
      de: Titel
  layout:
    fields:
      columns:
        type: checkboxes
        label:
          en: Included information
          de: Angezeigte Informationen
        default:
          - position
          - unit
          - room
          - phone
          - email
        options:
          - value: position
            text: Position
          - value: unit
            text:
              de: Organisationseinheiten
              en: Units of Organisation
          - value: room
            text:
              en: Room
              de: Raum
          - value: phone
            text:
              de: Telefon
              en: Phone number
          - value: fax
            text:
              en: Fax
              de: Fax
          - value: email
            text:
              de: E-Mail
              en: E-mail

```

## Your setup
**Kirby Version**  
4.5.0

**Console output**  
–

**Your system (please complete the following information)**
 - Device: iMac
 - OS: macOS 15.1.1
 - Browser: Firefox
 - Version: 133.0.3
