### ISSUE TITLE
Structure with disallowed duplication has no delete label

### ISSUE THREAD

**Issue by adamkiss** [k-next/kirby#6870]
## Description
When you turn off row duplication for a structure field, the delete label is empty for whatever reason.

Observed in v4.2.0, v4.5.0 and v5-beta.1.

**Expected behavior**  
Duplication is disallowed, delete button is visible normally.

**Screenshots**  

![CleanShot 2024-12-16 at 22 53 34@2x](https://github.com/user-attachments/assets/bbd37f39-aca7-4c8a-8185-c7d05e15ac3a)
![CleanShot 2024-12-16 at 22 53 52@2x](https://github.com/user-attachments/assets/b6cc4860-abf2-4257-bc6a-de34626f76e7)

## To reproduce

Minimal test working in every site I tried this in (four total):
```yml
test:
  type: structure
  label: Structure test
  duplicate: false
  fields:
    whatever:
      type: text
```
