### ISSUE TITLE
[V5] image block inside of layout row does not get stored after image upload and save

### ISSUE THREAD

**Issue by ralfgoeke** [k-next/kirby#6873]
## Description
When I'm adding a new layout row, a new image block and then upload an image inside of it, it uploads correctly but the block is not stored to the layout. I can select it and apply the just uploaded image afterwards, though.

**Expected behavior**  
Right upon upload and save, the image should be applied to the block inside the layout without an extra step. Worked in V4.5, I just checked that.

**Screenshots**  
Here's a little screen recording: https://share.cleanshot.com/MrtRK1Kg

## To reproduce

In plainkit (V5 Beta1) add this:

```yaml
# site/blueprints/pages/default.yml

title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          layout:
            label: Layouts
            type: layout
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files
```

Open panel, got to Home, add a layout and an image block inside it. Upload an image. 

## Your setup
**Kirby Version**  
5.0.0-beta.1

**Console output**  
none

**Your system (please complete the following information)**
 - Device: Macbook
 - OS: macOS 15.1.1
 - Browser: Firefox, Chrome
 - Version: current

**Additional context**  
Running DDEV on nginx, PHP 8.3
