### ISSUE TITLE
[v5] Query language not workin in panel view buttons

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#6888]
## Description
I finally tested the [view buttons](https://getkirby.com/releases/5/view-buttons) in a project now.

I expected the query language to work for the button properties. Especially for "text" and "link", but also for other options like "theme" and "icon" it would be great to keep them flexible. Think dates, approval processes, environments, …

```yml
buttons:
  design:
    icon: palette
    text: Design
    link: '{{ page.design_url }}'
  contact:
    icon: email
    text: Contact
    link: '{{ site.email }}'
    theme: info
```

## Your setup
**Kirby Version**  
5.0.0-beta.1
