### ISSUE TITLE
[v5] Radio field value resets after file upload

### ISSUE THREAD

**Issue by jirichlebus** [k-next/kirby#6889]
## Description
When using `when` conditions in blueprints with a `radio` field controlling the visibility of other fields, the value of the `radio` field resets unexpectedly during `drag & drop` file uploads in a `files` field. This causes a frustrating user experience where the field linked to the `when` condition disappears, even though the file upload is successful.

## To reproduce
1) Create a blueprint with the following structure:

```
sections:
  test:
    type: fields
    fields:
      radioField:
        label: Select an option
        type: radio
        default: option1
        options:
          option1: Option 1
          option2: Option 2
      conditionalField:
        label: Upload an image
        type: files
        when:
          radioField: option2
```
2) In the panel, select Option 2 in the radioField (do not save changes).
3) Drag & drop a file into the conditionalField.
4) Observe that the radioField value resets to option1, causing the conditionalField to disappear (although the file was correctly uploaded to Kirby).

## Expected Behavior
The value of the radioField should not reset during the file upload process, and the conditionalField should remain visible.

## Actual Behavior
The radioField value resets to its default (option1).
The conditionalField disappears immediately after the file is uploaded, even though the file upload itself is successful.

## Setup
Kirby Version v5.0-beta.1
