### ISSUE TITLE
Support `buttonName: true` as shortcut for view buttons

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#6926]
Symfony YAML parser hates

```YAML
buttons:
  - preview
  analytics:
    icon: chart
    text: Analytics
    link: https://my-analytics.com/for/this/page
    theme: aqua-icon
  - promote
  - status
```

So allow the following as well 

```yaml
buttons:
  preview: true
  analytics:
    icon: chart
    text: Analytics
    link: https://my-analytics.com/for/this/page
    theme: aqua-icon
  promote: true
  status: true
```
