### ISSUE TITLE
Panel API routes not working with FrankenPHP in Kirby 4

### ISSUE THREAD

**Issue by lassereinboeng** [k-next/kirby#6975]
## Description

Hi everyone!
I hope the category "bug" is the right one for this issue.
Me (and at least one other user) are trying to use Kirby with FrankenPHP locally (see https://forum.getkirby.com/t/frankenphp-kirby-cms/33460) but we both can't get it to work properly.
It would be lovely to be able to use Kirby 4+ and FrankenPHP together. It somehow seems to work with Kirby 3 though.

I would like to debug the issue but don't know where to start. If you don't have the capacity to look into the issue, I would love to know where to start looking. Thanks! 😊

Have a nice day and thank you in advance!
Lasse

**Expected behavior**  

When creating a new project with the Kirby starterkit and running it on FrankenPHP, users should be able to install the panel and be able to login after that.

**Screenshots**  

<img width="782" alt="Image" src="https://github.com/user-attachments/assets/1acdc5eb-1a4c-4873-b9dd-6e81586722bd" />

## To reproduce

**Edit:** You can reproduce the issue even faster with just running `docker run -p 80:80 -p 443:443 -p 443:443/udp -v $PWD:/app/public dunglas/frankenphp` from the project root. So no extra files are necessary.

1. Create a new project with the starterkit (e.g. `composer create-project getkirby/starterkit frankenphp-test`)
2. Create a Dockerfile in the project root with the following content:
 ```Dockerfile
FROM dunglas/frankenphp:php8.3-alpine

RUN install-php-extensions \
  gd \
  ctype \
  curl \
  dom \
  filter \
  hash \
  iconv \
  json \
  libxml \
  mbstring \
  openssl \
  SimpleXML \
  exif \
  fileinfo \
  intl \
  apcu \
  memcached \
  PDO \
  zip \
  zlib \

```
3. Create a Caddyfile with the following content:
```Caddyfile
{
	debug
	frankenphp
}

localhost {
	root * public/
	php_server
	file_server
}
```
4. Create a `docker-compose.yaml`File with the following content:
```yaml
services:
  php:
    build: .
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ./:/app/public
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    tty: true
volumes:
  caddy_data:
  caddy_config:
```
5. Run the service with `docker compose up --build`
6. Head to `https://localhost` in the browser (and accept insecure website).
7. Go to `/panel` and try to create an admin user.
8. See the API error message from the screenshot above.
9. Try again to go to `panel` and login or to access it. I experienced more API exceptions.

## Your setup
**Kirby Version**  `4.6.0`
