### ISSUE TITLE
Structure: support for subfields translate: false

### ISSUE THREAD

**Issue by AlexanderBoenninger** [k-next/kirby#7030]
## Description
In a multilanguage page, the files in a files field, that is nested in a structure field get lost for the second language, when saving the page. The structure field is set to `translate: false`.

**Expected behavior**  
I expect the files to stay there, since the `translate: false` should cause, that the entries are not touched for the sec. language.

## To reproduce

1. I have e.g. 2 languages and a structure field inside a Block with files (not sure if it matters). The structure field is `translate: false`
2. I fill it with entries files and other information. 
3. Switch to the next language. Enter content. The structure field is still filled and not editable (as expected). 
4. save the page. 
5. Structure field is empty. 

Setup
**Kirby Version**  
"name": "getkirby/cms",
            "version": "4.6.1",

**Console output**  
no output

**Your system (please complete the following information)**
on all devices

**Additional context**  
I use the kirby translator from @johannschopplich and thought i might be a bug in the plugin, but it was not:
https://github.com/kirby-tools/community/issues/29#issuecomment-2674197422

**Comment by afbora** [comment]
I can't reproduce the issue with just structure field. Do you mean structure field in blocks field? Could you share you full blueprint file please?

**Comment by AlexanderBoenninger** [comment]
AH Yes it seems to be necessary that it is in a block! 
Thanks.

**Comment by distantnative** [comment]
@AlexanderBoenninger Would be really great if you could provide us your blueprint - really helps us in replicating the issue instead of guessing around. Thank you.

**Comment by AlexanderBoenninger** [comment]
Sure!

**Block:**
```
name: Bilder Slider
icon: images
preview: fields
wysiwyg: true

tabs:
  content:
    fields:
      entrys:
        extends: fields/img_slider
        min: 2
      ratio:
        label: field.blocks.image.ratio
        type: select
        placeholder: Auto
        width: 1/2
        options:
          1/1: "1:1"
          16/9: "16:9"
          21/9: "21:9"
          4/3: "4:3"
          3/2: "3:2"
          3/1: "3:1"
          1/3: "1:3"
          2/3: "2:3"
          3/4: "3:4"
          9/21: "9:21"
          9/16: "9:16"
      crop:
        label: Bild in Fläche einpassen
        type: toggle
        width: 1/2
  settings:
    fields:
      headline_2:
        label: Abstand
        type: headline
        numbered: false
      space_top:
        extends: fields/space
        label: Abstand Oben
      space_bottom:
        extends: fields/space
        label: Abstand Unten
      space_left:
        extends: fields/space
        label: Abstand Links
      space_right:
        extends: fields/space
        label: Abstand Rechts
      space_page_margin:
        type: toggle
        default: false
        text:
          - nein
          - ja
      headline_3:
        label: Position
        type: headline
        numbered: false
      position:
        extends: fields/position
        label: ...


```

 **fields/img_slider:**
```
type: structure
label: Karussel Content
translation: false

fields:
  format:
    type: toggles
    default: "Bild"
    options:
      - Video
      - Bild
  video:
    extends: fields/video
    when:
      format: Video
  bild:
    label: Karussel Bild
    when:
      format: Bild
    type: files
    size: full
    info: "{{ file.dimensions }}"
    layout: cards
    max: 1
    templalte: casefile
    uploads: casefile
    query: site.pages.children.images
    image:
      ratio: 4/3
      back: white
  height_img:
    label: Höhe des Bildes/Videos
    help: "in keinen Displays und wenn nur ein Item da ist"
    after: "%"
    type: range
    default: 100
    min: 10
    max: 100
    step: 1
    width: 1/2
```

**Comment by distantnative** [comment]
@AlexanderBoenninger I only got back to this now as your examples included a lot of extends etc. which makes it hard for us to arrive at a testable minimal setup. I found some time eventually and what I noticed is that in your example you write `translation: false` but the option is named `translate: false`.

My main thought is though that your issue is that you are trying to set `translate: false` on the structure field, but your parent blocks field has no such option applied. So the blocks can actually differ between the languages, which is probably why you see first the default language's content being copied over, but then still be able to be altered.

Minimal setup that I used for testing (for future reference(:

```yaml
fields:
  blocks:
    type: blocks
    fieldsets:
      test:
        preview: fields
        wysiwyg: true
        fields:
          test:
            type: structure
            translate: false
            fields:
              test:
                type: files
```
