### ISSUE TITLE
[v5] Entries Field breaks when field has label

### ISSUE THREAD

**Issue by linusrogge** [k-next/kirby#7039]
## Description

When adding a `label` to the `field` option of the new `type: entries` field, the UI breaks and shows the label, leading to overflowing rows.

<img width="712" alt="Image" src="https://github.com/user-attachments/assets/c2aa29fd-0de6-4a6b-97fb-10bb60886f49" />

```yaml
services:
    type: entries
    label: Am Haus
    width: 1/2
    field:
      type: text
      label: Service
      placeholder: z.B. Tapezieren
```

## To reproduce

1. Create an entries field like above with a label
2. Add one or more entities

## Your setup
**Kirby Version**  

5.0.0-beta.3

**Console output**  

**Your system (please complete the following information)**
 - Device:  MacBook Pro
 - OS:  MacOS 15.2
 - Browser:  Arc (Chrome)
 - Version:  1.83.0
