### ISSUE TITLE
Status button: use custom status label also for title

### ISSUE THREAD

**Issue by bezin** [k-next/kirby#7043]
## Description
The change status button title attribute is not translated according to the page blueprint. It still contains the German label `Ungelistet` for `unlisted` status, wheras I set label and text to be something else. This also happens for the other translated label, too (`listed` => `Freigegeben`)

**Expected behavior**  
The button text and title communicate the same status.

## Screenshot
![Image](https://github.com/user-attachments/assets/1ffd0356-ec34-4a04-a832-9799f277b4b7)

## To reproduce

1. Have a page blueprint with the following status configuration:

```
status:
  draft:
    label: Entwurf
    text: Im Entwurfstadium können Sie die Inhalte frei bearbeiten
  unlisted:
    label: In Prüfung
    text: Ihre Inhalte werden geprüft und ggf. redaktionell bearbeitet. Sie können nun keine Änderungen mehr vornehmen
  listed:
    label: Freigegeben
    text: Ihre Inhalte sind für das Programm freigegeben
```
2. Edit the page in the panel and change status to `In Prüfung` 
3. Hover over the change status button with your pointer 

The title attribute shows `Ungelistet` rather than `In Prüfung`.

## Your setup
Kirby 4.6.1
MacOS 15.3.1
PHP 8.4
