### ISSUE TITLE
Deleted files stay selected in files fields

### ISSUE THREAD

**Issue by bezin** [k-next/kirby#7052]
## Description
When you delete a file from a files section, it will still be selected in any files field it has been selected before. The behavior probably has been like this forever, but it seemed rather odd to me. Also one can argue about what the best behavior is in this case?

[Video](https://github.com/user-attachments/assets/3e335b37-4548-4348-b680-febefadc2bb3)

## To reproduce
1. Have a page with the following blueprint: 

```yml
sections:
  fields:
    fields:
      coverimage:
        type: files
        label: Bild
  files:
    label: Bilder
```
2. Upload a file via the field or section.
3. Select the file in the field, if uploaded through the section.
4. Delete the file from the section.

The field is not updated. 

## Your setup
**Kirby Version**  4.6.1
