### ISSUE TITLE
users preview does not work with html as text

### ISSUE THREAD

**Issue by ugogon** [k-next/kirby#7065]
## Description
Given a custom text property within a user field within a structure field: this text is not rendered as html but as text.

## To reproduce
Blueprint:
```
sections:
  fields:
    label: Teams
    type: structure
    fields:
      member:
          label: Members
          text: "{{ user.name }} <em>({{ user.nickname }})</em>"
          type: users
```
Result:

![Image](https://github.com/user-attachments/assets/b7613e58-570b-4513-891d-212116216cb0)

## Your setup
Tested with Kirby version 4.0.2 and 4.6.1
