### ISSUE TITLE
Error for files field with both ratio and cover: true

### ISSUE THREAD

**Issue by linusrogge** [k-next/kirby#7083]
## Description
It is currently not possible to have a files field and set both a `ratio` and `cover: true`. The following config throws an error.

```yaml
thumbnail:
  type: files
  multiple: false
  layout: cards
  image:
    ratio: 1.5
    cover: true
```

<img width="446" alt="Image" src="https://github.com/user-attachments/assets/fe6346bf-4fda-4fdf-84da-0147a6bc453a" />

## Your setup
**Kirby Version**  
v4.6.1
