### ISSUE TITLE
Number input: support for `step: any`

### ISSUE THREAD

**Issue by pReya** [k-next/kirby#7110]
Not sure if this is a bug or a feature (I tend towards "bug"). Anway: Currently there seems to be no way to allow/validate an input of arbitrary precision for a `number` field.

E.g. I want to have a number field that allows/successfully validates the values `55`, `55.1` and `55.123456` (basically any positive number).

If I set this up naively like this in my blueprint:

```
          lat:
            type: number
            label: Geografische Breite
            required: true
            min: 0
```

This will only validate successfully `55`. Both `55.1` and `55.123456` will always show the red "invalid" indicator next to the field. (But: I can still press "save" – I'm not getting an error, even though the field is not valid and it is required -> that's why I think this is definitely a bug)

I can add the `step` prop to validate a number with a fixed precision, but this will then stop me from entering a number with a higher precision.

This was tested on `5.0.0-beta.4`.
