### ISSUE TITLE
inconsistent value formatting in pages section using the table layout

### ISSUE THREAD

**Issue by maxhoffmann** [k-next/kirby#7151]
## Description

When I set the pages section of my blog index to display each subpage as a table and with the `published` field being formatted, it doesn’t consistently apply the formatting of the date.

**Expected behavior**  

Every subpage’s `published` field is correctly formatted.

**Screenshots**  

<img width="340" alt="Image" src="https://github.com/user-attachments/assets/7cb6d846-c3fb-435a-8a6a-d4c5ddfe31cc" />

## To reproduce

Create a pages section like so:

```yml
pages:
  type: pages
  sortBy: published desc
  layout: table
  columns:
    title:
      label: Titel
    published:
      value: "{{ page.published.toDate('d.m.Y') }}"
```

Create a bunch of subpages with a `published` field`:

```yml
published:
  type: date
  display: DD.MM.YYYY
```

## Your setup
**Kirby Version**  

`4.7.0`

**Console output**  

No console errors

**Your system (please complete the following information)**
 - Device: MacBook Pro M1
 - OS: macOS 15.3.2
 - Browser: Vivaldi
 - Version: 7.3

**Additional context**  
Changing and saving the date of broken formatted pages, doesn’t fix the issue. In the table the date keeps being displayed unformatted.
