### ISSUE TITLE
Blueprints > Fields > Select > Placeholder doe not support translations

### ISSUE THREAD

**Issue by stairjoke** [k-next/kirby#7189]
## Description
The `placeholder`-property of the `select`-field does not allow translations. When adding a translation, Kirby shows an error.

This does not work:

```YAML
fruit:
    type: select
    label:
      de: Was willst du essen?
      en: What do you want to eat?
    placeholder:
      de: nichts gewählt
      en: nothing selected
    options:
      banana:
        de: Banane
        en: Banana
      apple:
        de: Apfel
        en: Apple
      kiwi: Kiwi
```

This works:

```YAML
fruit:
    type: select
    label:
      de: Was willst du essen?
      en: What do you want to eat?
    placeholder: untranslatable
    options:
      banana:
        de: Banane
        en: Banana
      apple:
        de: Apfel
        en: Apple
      kiwi: Kiwi
```

**Expected behavior**  
When adding a translation, Kirby should use the appropriate string in the panel.

**Screenshots**  
![Screenshot of error in the panel. Error in kirby/src/Toolkit/Component.php on line 165](https://github.com/user-attachments/assets/61a4289d-1ac1-4133-a269-ea3f85bf803c)

## To reproduce
Add a blueprint—I added a file blueprint—with a select and add a translated placeholder text.

## Your setup
**Kirby Version**  
```JSON
{
  "info": {
    "kirby": "4.7.0",
    "php": "8.4.6",
    "server": "PHP/8.4.6 (Development Server)",
    "license": "Unregistriert",
    "languages": [
      "de"
    ]
  },
  "security": [
    "Die Seite läuft lokal mit abgeschwächten Sicherheitschecks",
    "Debugging muss im öffentlichen Betrieb ausgeschaltet sein",
    "Der Vue Template Compiler ist aktiviert"
  ],
  "plugins": [
    {
      "name": "bnomei/feed",
      "version": "5.0.2"
    },
    {
      "name": "stairjoke/custom-markdown",
      "version": "?"
    }
  ]
}
```

**Console output**  
Empty.

**Your system (please complete the following information)**
 - Device: MacBook Pro M1
 - OS: macOS 15.4.1
 - Browser: Safari
 - Version: 18.4 (20621.1.15.11.10)

**Additional context**  
The page I’m working on has translations enabled, and the only language set up is German. I use translations in blueprints in many places, this is the only place it has failed yet.
