### ISSUE TITLE
Panel UI Bug: Multiselect Field overflows out of box for longer text

### ISSUE THREAD

**Issue by samyouel** [k-next/kirby#7221]
## Description
For some reason after updating from Kirby v3 to v4 my multiselect fields overflow out of the box, when the text of the selected items is too long.
Is this just me or anyone else experiencing this?
https://shottr.cc/s/1OaI/SCR-20250514-qfh.png (for some reason the image upload in GitHub isn't working)

**Expected behavior**  
I think it would make sense if the ellipsis css that is applied to the `k-tag` button inside the multi select also works, meaning that the text just gets truncated like this:
https://shottr.cc/s/1P67/SCR-20250514-qfh.png

## Your setup
**Kirby Version**  4

**Your system (please complete the following information)**
 - Device: Mac Pro
 - Browser: Chrome

**Comment by samyouel** [comment]
Currently, I've added this custom CSS to make it work, it's not particularly amazing, but maybe it can be a starting point for you guys :)

```css
.k-input[data-type='multiselect'] {
  justify-content: space-between;
}

.k-input[data-type='multiselect'] > span.k-input-icon {
  max-width: 10%;
}

.k-input[data-type='multiselect'] > span.k-input-element {
  max-width: 90%;
}
.k-input[data-type='multiselect'] > span.k-input-element button.k-tag, .k-input[data-type='multiselect'] > span.k-input-element .k-tags {
  max-width: 100%;
}
```
