### ISSUE TITLE
[v5] Fields called "title" in my custom block blueprint do not show up in panel after updating from v5 beta to v5rc.

### ISSUE THREAD

**Issue by verstecken** [k-next/kirby#7232]
## Description

I have some custom blocks and they all have a "title" field.

```
name: Quiz
preview: fields
wysiwyg: true
fields:
  title:
    label: Überschrift für diese Challenge
    type: text
  beschreibung:
    label: Beschreibe was zu tun ist.
```

The form field disappears from panel from the blocks section after updating from v5 beta to v5rc.

I know about this:
https://getkirby.com/docs/guide/blueprints/fields#naming-fields

But I am able to echo the field by $block->title(). Still - I can see the data is in the content txt-file. But the Text-Input in the panel is missing.

Is this a bug or not? 

## Your setup
**Kirby Version**  
5.0.0-rc.1
