### ISSUE TITLE
[v5] Select field preview displays value and not text

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#7273]
## Description

The `k-tags-field-preview` used for the `k-structure-field` used to display the human-readable option text in v4. Now the value to be stored is displayed.

**Expected behavior**  

The preview should display the human-readable text again.

**Screenshots**  

<img width="798" alt="Select field inside a structure field displaying the correct text" src="https://github.com/user-attachments/assets/3235fdad-1288-48c7-9558-fdf2e7f58ff4" />
<img width="478" alt="Field preview displaying the value instead" src="https://github.com/user-attachments/assets/994daa70-accd-4f0d-b1cb-becd648c7b60" />

## To reproduce

```yml
fields:
  structure:
    type: structure
    fields:
      select:
        type: select
        options:
          some_value: Some value
          another_value: Another value
```

## Your setup
**Kirby Version**  

5.0.0-rc.3

**Console output**  

None
