### ISSUE TITLE
Conditional field in structure looses content when condition is not default

### ISSUE THREAD

**Issue by doldenroller** [k-next/kirby#7333]
## Description
If there is a field with a condition in a structure field, the content doesn't get stored if that condition isn't the default value of the field that triggers it (e.g. a radiofield). It shows up short when the structure is closed, but as soon as you save the page the field is empty again.

In the contentfolder the `_changes`-folder gets not created and even existing content from other structureentries gets deleted.

**Expected behavior**
The content should be stored and saved.

**Screenshots**
In the first video there is a simple condition with radiobuttons. `Image` is the default value in this case. All fields that have this condition can be saved. The other fields with `Video` as condition loose there content.

https://github.com/user-attachments/assets/4bb25655-b2e8-4985-9f9d-36824a5f1447

In the second video the default value is switched, then you can save the content of fields with the `Video` condition. But all other content is lost.

https://github.com/user-attachments/assets/252a8757-b441-487c-9691-dc7307da20a9

## To reproduce

1. Install a fresh plainkit
2. Add structurefield to the blueprint
3. In the structurefield add some conditional fields and a radiofield to trigger the conditions
4. Try to add content and save the page

## Your setup
**Kirby Version**
Kirby 5.0.0

**Console output**
No error in the console

**Your system (please complete the following information)**

 - Device: Mac
 - OS: macOS
 - Browser: Firefox Developer
 - Version: 140

**Comment by afbora** [comment]
Could you share us your blueprint, please?

**Comment by doldenroller** [comment]
Sure, this is the structurefield:

````
imgentries:
label: Entries
type: structure

fields:
  img:
    label: Image
    type: text
    when:
      mediatype: img

  caption:
    label: Caption Image
    type: textarea
    buttons: false
    when:
      mediatype: img

  vid:
    label: Video
    type: text
    when:
      mediatype: video

  captionvideo:
    label: Caption Video
    type: textarea
    buttons: false
    when:
      mediatype: video

  mediatype:
    label: Entry Type
    type: radio
    columns: 2
    default: video
    options:
      img: Image
      video: Video

````
