### ISSUE TITLE
Files always sortable via dropdown

### ISSUE THREAD

**Issue by doldenroller** [k-next/kirby#7334]
## Description
If sorting in `files`-sections is disabled with `sortable: false` in the blueprint, the sortinghandles disappear as expected. But in the dropdown sorting is still there.

**Expected behavior**
Sorting should not be possible.

**Screenshots**

<img width="603" alt="Image" src="https://github.com/user-attachments/assets/9f80b479-b41d-4e0a-89f2-533be822f1b1" />

**The Blueprint**

````
sections:
  fileoverview:
    headline: Dateien
    type: files
    layout: cards
    sortable: false
    size: small
    batch: true
````

## To reproduce

1. Add a `files`-section to page-blueprint
2. Disable sorting with `sortable: false`
3. Click on the three dots of a file to open the dropdown
4. Files can still be sorted

## Your setup
**Kirby Version**
Kirby 5.0.0

**Console output**
No error in the console

**Your system (please complete the following information)**

 - Device: Mac
 - OS: macOS
 - Browser: Firefox Developer
 - Version: 140
