### ISSUE TITLE
Default value of field of type textarea does not support translation

### ISSUE THREAD

**Issue by stairjoke** [k-next/kirby#7343]
## Description
It is currently impossible to add a default value for a textarea in multiple languages in a blueprint. Attempting to do so results in an error message.

**Expected behavior**  
Adding the following to a field of type textarea should add a default value in multiple languages:
```YAML
text:
  type: textarea
  default:
    de: |
      Deutscher Standardtext mit link zur (link: https://getkirby.com/docs/reference/panel/fields/textarea text: Textarea Docs-Seite)
    en: |
      English default text with link to the (link: https://getkirby.com/docs/reference/panel/fields/textarea text: textarea docs-page)
````

**Screenshots**  

![Image](https://github.com/user-attachments/assets/531b43b4-0c7a-4419-b878-175ccb64b3cd)

## To reproduce
1. Add a field of type textarea to a blueprint
2. add a default value with translations
3. open any page of the kind

## Your setup
```JSON
**Kirby Version**  
{
  "info": {
    "kirby": "5.0.0",
    "php": "8.4.8",
    "server": "PHP/8.4.8 (Development Server)",
    "license": "Unregistriert",
    "languages": [
      "de"
    ]
  },
  "security": [
    "Die Seite läuft lokal mit abgeschwächten Sicherheitschecks",
    "Debugging muss im öffentlichen Betrieb ausgeschaltet sein"
  ],
  "plugins": [
    {
      "name": "bnomei/feed",
      "version": "5.0.2"
    },
    {
      "name": "stairjoke/auto-assign-file-metadata",
      "version": "1"
    },
    {
      "name": "stairjoke/custom-markdown",
      "version": "1"
    },
    {
      "name": "sylvainjule/colorextractor",
      "version": "2.0.0"
    }
  ]
}
```

**Console output**  

**Your system (please complete the following information)**
 - Device: MacBook Pro M1 pro
 - OS: macOS 15.6
 - Browser: Safari
 - Version: 18.5 (20621.2.5.11.8)

**Additional context**  
It also fails with unformatted text, as in `de: DE` instead of `de: | DE`.
