### ISSUE TITLE
Adding `max: 0` to an extended field: Invalid icon visible although field is valid

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [k-next/kirby#7347]
## Description
In a page blueprint, I extend a `blocks` and a `pages` field like this:

```yml
# site/blueprints/fields/blocks.yml
type: blocks
label: Blocks
max: 1
```
```yml
# site/blueprints/fields/page.yml
type: pages
label: Target page
max: 1
```

```yml
# site/blueprints/pages/default.yml
fields:
  text:
    extends: fields/blocks
    max: false
  target:
    extends: fields/page
    max: 0
```

In both fields, I remove the validator. Both the int and the bool value work, I can add more than one block or page.

But the red x is still visible, although the page can be saved:

<img width="758" alt="Image" src="https://github.com/user-attachments/assets/a6082af6-1590-4b5e-8b6f-b0f387ceee87" />

---

This also happens when I just add `max: 0` to a field. (Although it does not make sense to add it here.)

```yml
# site/blueprints/pages/default.yml
fields:
  target:
    type: pages
    max: 0
```

**Expected behavior**  
Seems to be a regression: In Kirby 4, the red x is not visible.

## Your setup
**Kirby Version**  
5.0.0

**Your system (please complete the following information)**
Chrome 138 on macOS 15.5
